각각 22년, 23년, 24년 데이터 가공

In [1]:
import numpy as np 
import pandas as pd

In [ ]:
# year22 = pd.read_csv('data_2022.csv')
# year23 = pd.read_csv('data_2023.csv')
# year24 = pd.read_csv('data_2024.csv')

In [ ]:
# year22
# year23
# year24

        시군구    행정동    행정동_ID      행정기관코드     기준_날짜  지하철_승객_수    연도
0       종로구  청운효자동  11010720  1111051500  20221231       0.0  2022
1       종로구  청운효자동  11010720  1111051500  20221230       0.0  2022
2       종로구  청운효자동  11010720  1111051500  20221229       0.0  2022
3       종로구  청운효자동  11010720  1111051500  20221228       0.0  2022
4       종로구  청운효자동  11010720  1111051500  20221227       0.0  2022
...     ...    ...       ...         ...       ...       ...   ...
266080  강동구   둔촌2동  11250710  1174070000  20220105   10749.0  2022
266081  강동구   둔촌2동  11250710  1174070000  20220104   10749.0  2022
266082  강동구   둔촌2동  11250710  1174070000  20220103   10307.0  2022
266083  강동구   둔촌2동  11250710  1174070000  20220102    2746.0  2022
266084  강동구   둔촌2동  11250710  1174070000  20220101    2192.0  2022

[266085 rows x 7 columns]

In [ ]:
# # '기준_날짜'를 문자열로 변환하기
# year22['기준_날짜'] = year22['기준_날짜'].astype(str) 
# year22['기준_날짜'] = pd.to_datetime(year22['기준_날짜'],format='%Y%m%d').dt.strftime('%Y%m%d')
# year22['기준_날짜']

# # '기준_날짜'를 문자열로 변환하기
# year23['기준_날짜'] = year23['기준_날짜'].astype(str) 
# year23['기준_날짜'] = pd.to_datetime(year23['기준_날짜'],format='%Y%m%d').dt.strftime('%Y%m%d')
# year23['기준_날짜']

# # '기준_날짜'를 문자열로 변환하기
# year24['기준_날짜'] = year24['기준_날짜'].astype(str) 
# year24['기준_날짜'] = pd.to_datetime(year24['기준_날짜'],format='%Y%m%d').dt.strftime('%Y%m%d')
# year24['기준_날짜']

0         20221231
1         20221230
2         20221229
3         20221228
4         20221227
            ...
266080    20220105
266081    20220104
266082    20220103
266083    20220102
266084    20220101
Name: 기준_날짜, Length: 266085, dtype: object

날짜 변환

In [ ]:
# # YYYY-MM-DD 형식으로 변환
# year22['기준_날짜'] = year22['기준_날짜'].astype(str)
# year22['기준_날짜'] = pd.to_datetime(year22['기준_날짜'], format='%Y%m%d').dt.strftime('%Y년%m월%d일')
# print(year22['기준_날짜'].head())# 결과 확인


# # YYYY-MM-DD 형식으로 변환
# year23['기준_날짜'] = year23['기준_날짜'].astype(str)
# year23['기준_날짜'] = pd.to_datetime(year23['기준_날짜'], format='%Y%m%d').dt.strftime('%Y년%m월%d일')
# print(year23['기준_날짜'].head())


# # YYYY-MM-DD 형식으로 변환
# year24['기준_날짜'] = year24['기준_날짜'].astype(str)
# year24['기준_날짜'] = pd.to_datetime(year24['기준_날짜'], format='%Y%m%d').dt.strftime('%Y년%m월%d일')
# print(year24['기준_날짜'].head())

0    2022년12월31일
1    2022년12월30일
2    2022년12월29일
3    2022년12월28일
4    2022년12월27일
Name: 기준_날짜, dtype: object

In [ ]:
# year22
# year23
# year24

        시군구    행정동    행정동_ID      행정기관코드        기준_날짜  지하철_승객_수    연도
0       종로구  청운효자동  11010720  1111051500  2022년12월31일       0.0  2022
1       종로구  청운효자동  11010720  1111051500  2022년12월30일       0.0  2022
2       종로구  청운효자동  11010720  1111051500  2022년12월29일       0.0  2022
3       종로구  청운효자동  11010720  1111051500  2022년12월28일       0.0  2022
4       종로구  청운효자동  11010720  1111051500  2022년12월27일       0.0  2022
...     ...    ...       ...         ...          ...       ...   ...
266080  강동구   둔촌2동  11250710  1174070000  2022년01월05일   10749.0  2022
266081  강동구   둔촌2동  11250710  1174070000  2022년01월04일   10749.0  2022
266082  강동구   둔촌2동  11250710  1174070000  2022년01월03일   10307.0  2022
266083  강동구   둔촌2동  11250710  1174070000  2022년01월02일    2746.0  2022
266084  강동구   둔촌2동  11250710  1174070000  2022년01월01일    2192.0  2022

[266085 rows x 7 columns]

In [ ]:
# year22.to_csv('year22.csv', index=False, encoding='utf-8')
# year23.to_csv('year23.csv', index=False, encoding='utf-8')
# year24.to_csv('year24.csv', index=False, encoding='utf-8')