In [2]:
import numpy as np 
import pandas as pd

In [3]:
year22 = pd.read_csv('year22_df_all.csv')
year23 = pd.read_csv('year23_df_all.csv')
year24 = pd.read_csv('year24_df_all.csv')

In [9]:
year22, year23, year24

(        연도   분기   행정동   시군구      총_승객수
 0     2022  1분기  가락1동   송파구  1687061.0
 1     2022  1분기  가락2동   송파구   939791.0
 2     2022  1분기   가산동   금천구  3436767.0
 3     2022  1분기  갈현1동   은평구  2646206.0
 4     2022  1분기  갈현2동   은평구   539771.0
 ...    ...  ...   ...   ...        ...
 1667  2022  3분기  화곡본동   강서구        0.0
 1668  2022  3분기   황학동    중구        0.0
 1669  2022  3분기   회기동  동대문구        0.0
 1670  2022  3분기   후암동   용산구        0.0
 1671  2022  3분기  휘경2동  동대문구        0.0

 [1672 rows x 5 columns],
         연도   분기   행정동   시군구      총_승객수
 0     2023  1분기  가락1동   송파구  2177590.0
 1     2023  1분기  가락2동   송파구  1146664.0
 2     2023  1분기   가산동   금천구  4036852.0
 3     2023  1분기  갈현1동   은평구  2979181.0
 4     2023  1분기  갈현2동   은평구   661646.0
 ...    ...  ...   ...   ...        ...
 1667  2023  3분기  화곡본동   강서구        0.0
 1668  2023  3분기   황학동    중구        0.0
 1669  2023  3분기   회기동  동대문구        0.0
 1670  2023  3분기   후암동   용산구        0.0
 1671  2023  3분기  휘경2동  동대문구        0.0

 [1672 rows x 5 columns],
         연도   분기   행정동   시군구      총_승객수
 0     2024  1분기  가락1동   송파구  2260444.0
 1     2024  1분기  가락2동   송파구  1180218.0
 2     2024  1분기   가산동   금천구  4112467.0
 3     2024  1분기  갈현1동   은평구  2943302.0
 4     2024  1분기  갈현2동   은평구   684093.0
 ...    ...  ...   ...   ...        ...
 1677  2024  3분기  화곡본동   강서구        0.0
 1678  2024  3분기   황학동    중구        0.0
 1679  2024  3분기   회기동  동대문구        0.0
 1680  2024  3분기   후암동   용산구        0.0
 1681  2024  3분기  휘경2동  동대문구        0.0

 [1682 rows x 5 columns])

In [10]:
year22['행정동'].unique()
year23['행정동'].unique()
year24['행정동'].unique()

array(['가락1동', '가락2동', '가산동', '갈현1동', '갈현2동', '개봉1동', '개포2동', '거여1동',
       '공덕동', '공릉1동', '공릉2동', '공항동', '광장동', '광희동', '구로2동', '구로3동', '구로5동',
       '구의1동', '구의2동', '구의3동', '금호1가동', '금호4가동', '길동', '길음1동', '남가좌1동',
       '남영동', '남현동', '내곡동', '노량진1동', '녹번동', '논현1동', '논현2동', '능동', '당산1동',
       '당산2동', '대림3동', '대방동', '대조동', '대치2동', '대치4동', '대학동', '대흥동', '도곡1동',
       '도곡2동', '도봉2동', '독산1동', '동화동', '둔촌1동', '둔촌2동', '등촌1동', '등촌3동',
       '마장동', '마천1동', '망우본동', '면목3.8동', '면목4동', '면목본동', '명동', '명일1동',
       '명일2동', '목1동', '목2동', '목3동', '묵2동', '문래동', '문정2동', '미아동', '반포1동',
       '반포2동', '반포4동', '반포본동', '발산1동', '방배1동', '방배2동', '방배3동', '방이1동',
       '방이2동', '방학1동', '방화1동', '방화2동', '번1동', '보라매동', '보문동', '불광1동',
       '사근동', '사당2동', '사당4동', '사직동', '삼선동', '삼성1동', '삼성2동', '삼양동', '상계1동',
       '상계2동', '상계3.4동', '상계5동', '상계8동', '상도1동', '상도2동', '상봉1동', '상봉2동',
       '상암동', '서강동', '서교동', '서림동', '서빙고동', '서원동', '서초1동', '서초2동', '서초3동',
       '석관동', '석촌동', '성내1동', '성내2동', '성산2동', '성수1가1동', '성수1가2동', '성수2가3동',
       '소공동', '송천동', '송파1동', '수궁동', '수색동', '수서동', '수유1동', '수유2동', '숭인2동',
       '시흥1동', '신길1동', '신길6동', '신길7동', '신내1동', '신당동', '신대방2동', '신도림동',
       '신림동', '신사1동', '신사2동', '신사동', '신정3동', '신정4동', '신정7동', '신촌동', '아현동',
       '안암동', '암사2동', '압구정동', '약수동', '양재1동', '양재2동', '양평1동', '양평2동',
       '여의동', '역삼1동', '영등포동', '영등포본동', '오금동', '오류1동', '오륜동', '옥수동',
       '왕십리2동', '용강동', '용답동', '용산2가동', '용신동', '우이동', '우장산동', '월계2동',
       '월계3동', '월곡2동', '을지로동', '응봉동', '이문1동', '이문2동', '이태원1동', '이화동',
       '인헌동', '일원본동', '자양4동', '잠실2동', '잠실4동', '잠실6동', '잠실7동', '잠실본동',
       '잠원동', '장위2동', '장지동', '장충동', '전농1동', '정릉1동', '정릉4동', '제기동',
       '종로1.2.3.4가동', '종로5.6가동', '중계2.3동', '중곡3동', '중화2동', '증산동', '진관동',
       '창1동', '창5동', '창신3동', '천연동', '천호1동', '청룡동', '충현동', '필동', '하계2동',
       '한강로동', '한남동', '행당1동', '행당2동', '홍제1동', '화곡1동', '화양동', '회현동', '효창동',
       '휘경1동', '흑석동', '암사3동', '오류2동', '가락본동', '가리봉동', '가양2동', '가양3동',
       '가회동', '개봉2동', '개봉3동', '개포1동', '개포4동', '거여2동', '고덕1동', '고덕2동',
       '고척1동', '고척2동', '교남동', '구로1동', '구로4동', '구산동', '군자동', '금호2.3가동',
       '길음2동', '낙성대동', '난곡동', '난향동', '남가좌2동', '노량진2동', '다산동', '답십리1동',
       '답십리2동', '대림1동', '대림2동', '대치1동', '도림동', '도봉1동', '도화동', '독산2동',
       '독산3동', '독산4동', '돈암1동', '돈암2동', '동선동', '등촌2동', '마천2동', '망우3동',
       '망원1동', '망원2동', '면목2동', '면목5동', '면목7동', '목4동', '목5동', '무악동', '묵1동',
       '문정1동', '미성동', '반포3동', '방배4동', '방배본동', '방학2동', '방학3동', '번2동',
       '번3동', '보광동', '부암동', '북가좌1동', '북가좌2동', '북아현동', '불광2동', '사당1동',
       '사당3동', '사당5동', '삼각산동', '삼성동', '삼전동', '삼청동', '상계10동', '상계6.7동',
       '상계9동', '상도3동', '상도4동', '서초4동', '성내3동', '성북동', '성산1동', '성수2가1동',
       '성현동', '세곡동', '송정동', '송중동', '송파2동', '수유3동', '숭인1동', '시흥2동', '시흥3동',
       '시흥4동', '시흥5동', '신길3동', '신길4동', '신길5동', '신내2동', '신당5동', '신대방1동',
       '신수동', '신원동', '신월1동', '신월2동', '신월3동', '신월4동', '신월5동', '신월6동',
       '신월7동', '신정1동', '신정2동', '신정6동', '쌍문1동', '쌍문2동', '쌍문3동', '쌍문4동',
       '암사1동', '역삼2동', '역촌동', '연남동', '연희동', '염리동', '염창동', '왕십리도선동', '용문동',
       '원효로1동', '원효로2동', '월계1동', '월곡1동', '위례동', '은천동', '응암1동', '응암2동',
       '응암3동', '이촌1동', '이촌2동', '이태원2동', '인수동', '일원1동', '자양1동', '자양2동',
       '자양3동', '잠실3동', '장안1동', '장안2동', '장위1동', '장위3동', '전농2동', '정릉2동',
       '정릉3동', '조원동', '종암동', '중계1동', '중계4동', '중계본동', '중곡1동', '중곡2동',
       '중곡4동', '중림동', '중앙동', '중화1동', '창2동', '창3동', '창4동', '창신1동', '창신2동',
       '천호2동', '천호3동', '청구동', '청담동', '청량리동', '청림동', '청운효자동', '청파동', '평창동',
       '풍납1동', '풍납2동', '하계1동', '합정동', '행운동', '혜화동', '홍은1동', '홍은2동',
       '홍제2동', '홍제3동', '화곡2동', '화곡3동', '화곡4동', '화곡6동', '화곡8동', '화곡본동',
       '황학동', '회기동', '후암동', '휘경2동', '개포3동', '상일1동', '상일2동', '항동'],
      dtype=object)

In [11]:
print(year24.isna().sum())

연도       0
분기       0
행정동      0
시군구      0
총_승객수    0
dtype: int64

In [12]:
# 항동, 상일동에 데이터 있는지 확인

hang_dong = year24[year24['행정동'].str.contains('항동')]

print("행정동 목록에서 '항동'이 포함된 동:")
print(hang_dong)

# 결과: 둘다 행정동 데이터 없음

행정동 목록에서 '항동'이 포함된 동:
        연도   분기  행정동  시군구      총_승객수
11    2024  1분기  공항동  강서구  4840158.0
230   2024  2분기  공항동  강서구  5016708.0
449   2024  3분기  공항동  강서구  4810764.0
670   2024  4분기  공항동  강서구  2655168.0
1264  2024  4분기   항동  구로구        0.0
1665  2024  3분기   항동  구로구        0.0

In [13]:
# 총_승객수 값이 0.0 제외 
year22_df = year22[year22['총_승객수'] != 0.0]
year22_df

year23_df = year23[year23['총_승객수'] != 0.0]
year23_df

year24_df = year24[year24['총_승객수'] != 0.0]
year24_df

       연도   분기   행정동   시군구       총_승객수
0    2024  1분기  가락1동   송파구   2260444.0
1    2024  1분기  가락2동   송파구   1180218.0
2    2024  1분기   가산동   금천구   4112467.0
3    2024  1분기  갈현1동   은평구   2943302.0
4    2024  1분기  갈현2동   은평구    684093.0
..    ...  ...   ...   ...         ...
875  2024  4분기   화양동   광진구   2406614.0
876  2024  4분기   회현동    중구  53971340.0
877  2024  4분기   효창동   용산구    460143.0
878  2024  4분기  휘경1동  동대문구    873080.0
879  2024  4분기   흑석동   동작구    449863.0

[880 rows x 5 columns]

In [14]:
# 다른구 같은 동 확인
def same_dong(df, dong_name, gu_name):
    same_dong = df[df['행정동'] == dong_name] 
    other_gus = same_dong[same_dong['시군구'] !=gu_name] 
    unique_gus = other_gus[['시군구','행정동']].drop_duplicates().reset_index(drop=True)
    return unique_gus 

dong_name = "신사동"
gu_name = "강남구"

same_dong_in_other_gus = same_dong(year22_df, dong_name, gu_name)
print(f"'{dong_name}'이(가) '{gu_name}' 외에 속한 구 목록:")
print(same_dong_in_other_gus)

'신사동'이(가) '강남구' 외에 속한 구 목록:
   시군구  행정동
0  관악구  신사동

In [15]:
# shinsadong = year22_df[year22_df['행정동'] == '신사동'] 

# print("신사동 목록:")
# print(shinsadong)

shinsadong = year22_df[year22_df['시군구'] == '강남구'] 

print("강남구 목록:")
print(shinsadong)

강남구 목록:
       연도   분기   행정동  시군구      총_승객수
6    2022  1분기  개포2동  강남구   923472.0
30   2022  1분기  논현1동  강남구  3619428.0
31   2022  1분기  논현2동  강남구  3116423.0
38   2022  1분기  대치2동  강남구  4446201.0
39   2022  1분기  대치4동  강남구  4084910.0
41   2022  1분기  도곡1동  강남구   822611.0
42   2022  1분기  도곡2동  강남구  1447548.0
87   2022  1분기  삼성1동  강남구  2428233.0
88   2022  1분기  삼성2동  강남구   443247.0
120  2022  1분기   수서동  강남구  1696413.0
141  2022  1분기  압구정동  강남구  6465168.0
148  2022  1분기  역삼1동  강남구  6324960.0
172  2022  1분기  일원본동  강남구  1346454.0
220  2022  2분기  개포2동  강남구  1159352.0
244  2022  2분기  논현1동  강남구  4115404.0
245  2022  2분기  논현2동  강남구  3569560.0
252  2022  2분기  대치2동  강남구  5296217.0
253  2022  2분기  대치4동  강남구  4836779.0
256  2022  2분기  도곡1동  강남구   984897.0
257  2022  2분기  도곡2동  강남구  1691090.0
303  2022  2분기  삼성1동  강남구  2976529.0
304  2022  2분기  삼성2동  강남구  1310698.0
337  2022  2분기   수서동  강남구  2058964.0
360  2022  2분기  압구정동  강남구  7340028.0
367  2022  2분기  역삼1동  강남구  7392066.0
391  2022  2분기  일원본동  강남구  1659574.0
439  2022  3분기  개포2동  강남구  1155496.0
463  2022  3분기  논현1동  강남구  4177101.0
464  2022  3분기  논현2동  강남구  3598362.0
471  2022  3분기  대치2동  강남구  5652945.0
472  2022  3분기  대치4동  강남구  4971757.0
475  2022  3분기  도곡1동  강남구   978506.0
476  2022  3분기  도곡2동  강남구  1739801.0
522  2022  3분기  삼성1동  강남구  3152087.0
523  2022  3분기  삼성2동  강남구  1736545.0
556  2022  3분기   수서동  강남구  2051576.0
579  2022  3분기  압구정동  강남구  7485478.0
586  2022  3분기  역삼1동  강남구  7752335.0
610  2022  3분기  일원본동  강남구  1671298.0
658  2022  4분기  개포2동  강남구  1258934.0
682  2022  4분기  논현1동  강남구  4452143.0
683  2022  4분기  논현2동  강남구  3789207.0
690  2022  4분기  대치2동  강남구  5922552.0
691  2022  4분기  대치4동  강남구  5130365.0
694  2022  4분기  도곡1동  강남구  1022877.0
695  2022  4분기  도곡2동  강남구  1814659.0
741  2022  4분기  삼성1동  강남구  3328585.0
742  2022  4분기  삼성2동  강남구  1795749.0
775  2022  4분기   수서동  강남구  2224583.0
798  2022  4분기  압구정동  강남구  8033634.0
805  2022  4분기  역삼1동  강남구  8059140.0
829  2022  4분기  일원본동  강남구  1788296.0

In [16]:
# --분기별로 어느 행정동이 상위에 드는지 확인 (2022년)

# 그룹화 : 연도, 분기, 행정동 별로 총_승객수 합산
dong23 = year22_df.groupby(['연도', '분기', '행정동'])['총_승객수'].sum().reset_index()

# 2022년, 분기별로 총_승객수가 가장 많은 행정동 찾기
top_dong23 = dong23.loc[dong23.groupby(['연도','분기'])['총_승객수'].idxmax()]
top_dong23 = top_dong23.reset_index(drop=True)

print(top_dong23)


# --분기별로 어느 행정동이 상위에 드는지 확인 (2023년)

# 그룹화 : 연도, 분기, 행정동 별로 총_승객수 합산
dong23 = year23_df.groupby(['연도', '분기', '행정동'])['총_승객수'].sum().reset_index()

# 2022년, 분기별로 총_승객수가 가장 많은 행정동 찾기
top_dong23 = dong23.loc[dong23.groupby(['연도','분기'])['총_승객수'].idxmax()]
top_dong23 = top_dong23.reset_index(drop=True)

print(top_dong23)


# --분기별로 어느 행정동이 상위에 드는지 확인 (2024년)

# 그룹화 : 연도, 분기, 행정동 별로 총_승객수 합산
dong24 = year24_df.groupby(['연도', '분기', '행정동'])['총_승객수'].sum().reset_index()

# 2022년, 분기별로 총_승객수가 가장 많은 행정동 찾기
top_dong24 = dong24.loc[dong24.groupby(['연도','분기'])['총_승객수'].idxmax()]
top_dong24 = top_dong24.reset_index(drop=True)

print(top_dong24)

     연도   분기          행정동        총_승객수
0  2022  1분기  종로1.2.3.4가동  204072623.0
1  2022  2분기  종로1.2.3.4가동  262468038.0
2  2022  3분기  종로1.2.3.4가동  261778012.0
3  2022  4분기  종로1.2.3.4가동  297351297.0
     연도   분기          행정동        총_승객수
0  2023  1분기  종로1.2.3.4가동  283336989.0
1  2023  2분기  종로1.2.3.4가동  297794881.0
2  2023  3분기  종로1.2.3.4가동  286423604.0
3  2023  4분기  종로1.2.3.4가동  304948224.0
     연도   분기          행정동        총_승객수
0  2024  1분기  종로1.2.3.4가동  288272238.0
1  2024  2분기  종로1.2.3.4가동  301060252.0
2  2024  3분기  종로1.2.3.4가동  281990664.0
3  2024  4분기  종로1.2.3.4가동  167175256.0

2022년 분기별 행정동 상위 순위

In [17]:
# --2022년 1분기 행정동 승객_수 top 5--

dong22_q1 = year22_df[(year22_df['연도'] == 2022) & (year22_df['분기'] == '1분기')]
top5_dong22_q1 = dong22_q1.nlargest(11, '총_승객수') 
top5_dong22_q1 = top5_dong22_q1.reset_index(drop=True)
print(top5_dong22_q1)

# --2022년 2분기 행정동 승객_수 top 5--
dong22_q2 = year22_df[(year22_df['연도'] == 2022) & (year22_df['분기'] == '2분기')]
top5_dong22_q2 = dong22_q2.nlargest(11, '총_승객수')
top5_dong22_q2 = top5_dong22_q2.reset_index(drop=True) 
print(top5_dong22_q2)

# --2022 3분기 행정동 승객_수 top 5--
dong22_q3 = year22_df[(year22_df['연도'] == 2022) & (year22_df['분기'] == '3분기')]
top5_dong22_q3 = dong22_q3.nlargest(11, '총_승객수')
top5_dong22_q3 = top5_dong22_q3.reset_index(drop=True)
print(top5_dong22_q3)

# --2022 4분기 행정동 승객_수 top 5--
dong22_q4 = year22_df[(year22_df['연도'] == 2022) & (year22_df['분기'] == '4분기')]
top5_dong22_q4 = dong22_q4.nlargest(11, '총_승객수')
top5_dong22_q4 = top5_dong22_q4.reset_index(drop=True)
print(top5_dong22_q4)

      연도   분기          행정동  시군구        총_승객수
0   2022  1분기  종로1.2.3.4가동  종로구  204072623.0
1   2022  1분기           명동   중구   88215902.0
2   2022  1분기          회현동   중구   60503140.0
3   2022  1분기          사직동  종로구   39997812.0
4   2022  1분기          소공동   중구   34687788.0
5   2022  1분기         을지로동   중구   33664620.0
6   2022  1분기          서교동  마포구   27006204.0
7   2022  1분기          삼선동  성북구   22908897.0
8   2022  1분기          광희동   중구   20937730.0
9   2022  1분기         한강로동  용산구   19556235.0
10  2022  1분기           필동   중구   19038767.0
      연도   분기          행정동  시군구        총_승객수
0   2022  2분기  종로1.2.3.4가동  종로구  262468038.0
1   2022  2분기           명동   중구  111819629.0
2   2022  2분기          회현동   중구   79415300.0
3   2022  2분기          사직동  종로구   55106448.0
4   2022  2분기          소공동   중구   43463652.0
5   2022  2분기         을지로동   중구   41408670.0
6   2022  2분기          서교동  마포구   32302323.0
7   2022  2분기          삼선동  성북구   28231497.0
8   2022  2분기         한강로동  용산구   25756585.0
9   2022  2분기          광희동   중구   25361120.0
10  2022  2분기           필동   중구   23799963.0
      연도   분기          행정동  시군구        총_승객수
0   2022  3분기  종로1.2.3.4가동  종로구  261778012.0
1   2022  3분기           명동   중구  119513428.0
2   2022  3분기          회현동   중구   81067410.0
3   2022  3분기          사직동  종로구   53803128.0
4   2022  3분기          소공동   중구   45413868.0
5   2022  3분기         을지로동   중구   42512350.0
6   2022  3분기          서교동  마포구   33122673.0
7   2022  3분기          삼선동  성북구   26932473.0
8   2022  3분기         한강로동  용산구   26744680.0
9   2022  3분기          광희동   중구   26372410.0
10  2022  3분기           필동   중구   22788128.0
      연도   분기          행정동  시군구        총_승객수
0   2022  4분기  종로1.2.3.4가동  종로구  297351297.0
1   2022  4분기           명동   중구  148864740.0
2   2022  4분기          회현동   중구   93211930.0
3   2022  4분기          사직동  종로구   61652196.0
4   2022  4분기          소공동   중구   53062068.0
5   2022  4분기         을지로동   중구   46511990.0
6   2022  4분기          서교동  마포구   36189705.0
7   2022  4분기          삼선동  성북구   30162915.0
8   2022  4분기          광희동   중구   30150380.0
9   2022  4분기         한강로동  용산구   29219090.0
10  2022  4분기           필동   중구   26068823.0

2022년 분기별 행정동 하위 순위

In [18]:
# 1분기
dong22_q1 = year22_df[(year22_df['연도'] == 2022) & (year22_df['분기'] == '1분기')]
bottom_dong22_q1 = dong22_q1.nsmallest(11, '총_승객수')
bottom_dong22_q1 = bottom_dong22_q1.reset_index(drop=True)
print(bottom_dong22_q1)

# 2분기
dong22_q2 = year22_df[(year22_df['연도'] == 2022) & (year22_df['분기'] == '2분기')]
bottom_dong22_q2 = dong22_q2.nsmallest(11, '총_승객수')
bottom_dong22_q2 = bottom_dong22_q2.reset_index(drop=True)
print(bottom_dong22_q2)

# 3분기
dong22_q3 = year22_df[(year22_df['연도'] == 2022) & (year22_df['분기'] == '3분기')]
bottom_dong22_q3 = dong22_q3.nsmallest(11, '총_승객수')
bottom_dong22_q3 = bottom_dong22_q3.reset_index(drop=True)
print(bottom_dong22_q3)

# 4분기
dong22_q3 = year22_df[(year22_df['연도'] == 2022) & (year22_df['분기'] == '3분기')]
bottom_dong22_q3 = dong22_q3.nsmallest(11, '총_승객수')
bottom_dong22_q3 = bottom_dong22_q3.reset_index(drop=True)
print(bottom_dong22_q3)

      연도   분기    행정동   시군구     총_승객수
0   2022  1분기    수색동   은평구   69804.0
1   2022  1분기    응봉동   성동구   70744.0
2   2022  1분기   방배2동   서초구   83540.0
3   2022  1분기   반포본동   서초구   96305.0
4   2022  1분기   수유1동   강북구  139805.0
5   2022  1분기   수유2동   강북구  171651.0
6   2022  1분기   망우본동   중랑구  183394.0
7   2022  1분기   불광1동   은평구  193249.0
8   2022  1분기  남가좌1동  서대문구  209056.0
9   2022  1분기   반포2동   서초구  231971.0
10  2022  1분기   구로2동   구로구  240003.0
      연도   분기    행정동  시군구     총_승객수
0   2022  2분기    신림동  관악구   21350.0
1   2022  2분기   보라매동  관악구   62946.0
2   2022  2분기    대학동  관악구   64785.0
3   2022  2분기    수색동  은평구   85614.0
4   2022  2분기    응봉동  성동구   90893.0
5   2022  2분기   반포본동  서초구  108549.0
6   2022  2분기   방배2동  서초구  115438.0
7   2022  2분기  신대방2동  동작구  122912.0
8   2022  2분기    서림동  관악구  128109.0
9   2022  2분기   수유1동  강북구  163906.0
10  2022  2분기   수유2동  강북구  202866.0
      연도   분기   행정동  시군구     총_승객수
0   2022  3분기   신림동  관악구   53302.0
1   2022  3분기   수색동  은평구   84491.0
2   2022  3분기   응봉동  성동구   84556.0
3   2022  3분기  반포본동  서초구   99980.0
4   2022  3분기  방배2동  서초구  113564.0
5   2022  3분기  수유1동  강북구  161516.0
6   2022  3분기   대학동  관악구  162603.0
7   2022  3분기  보라매동  관악구  199951.0
8   2022  3분기  수유2동  강북구  201779.0
9   2022  3분기  불광1동  은평구  231724.0
10  2022  3분기  망우본동  중랑구  260449.0
      연도   분기   행정동  시군구     총_승객수
0   2022  3분기   신림동  관악구   53302.0
1   2022  3분기   수색동  은평구   84491.0
2   2022  3분기   응봉동  성동구   84556.0
3   2022  3분기  반포본동  서초구   99980.0
4   2022  3분기  방배2동  서초구  113564.0
5   2022  3분기  수유1동  강북구  161516.0
6   2022  3분기   대학동  관악구  162603.0
7   2022  3분기  보라매동  관악구  199951.0
8   2022  3분기  수유2동  강북구  201779.0
9   2022  3분기  불광1동  은평구  231724.0
10  2022  3분기  망우본동  중랑구  260449.0

2023년 분기별 행정동 상위 순위

In [19]:
# 2023 1분기 행정동 승객_수 top 5
dong23_q1 = year23_df[(year23_df['연도'] == 2023) & (year23_df['분기'] == '1분기')]
top5_dong23_q1 = dong23_q1.nlargest(11, '총_승객수')
top5_dong23_q1 = top5_dong23_q1.reset_index(drop=True)
print(top5_dong23_q1)

# 2023 2분기 행정동 승객_수 top 5
dong23_q2 = year23_df[(year23_df['연도'] == 2023) & (year23_df['분기'] == '2분기')]
top5_dong23_q2 = dong23_q2.nlargest(11, '총_승객수')
top5_dong23_q2 = top5_dong23_q2.reset_index(drop=True)
print(top5_dong23_q2)

# 2023 3분기 행정동 승객_수 top 5
dong23_q3 = year23_df[(year23_df['연도'] == 2023) & (year23_df['분기'] == '3분기')]
top5_dong23_q3 = dong23_q3.nlargest(11, '총_승객수')
top5_dong23_q3 = top5_dong23_q3.reset_index(drop=True)
print(top5_dong23_q3)

# 2023 4분기 행정동 승객_수 top 5
dong23_q4 = year23_df[(year23_df['연도'] == 2023) & (year23_df['분기'] == '4분기')]
top5_dong23_q4 = dong23_q4.nlargest(11, '총_승객수')
top5_dong23_q4 = top5_dong23_q4.reset_index(drop=True)
print(top5_dong23_q4)

      연도   분기          행정동  시군구        총_승객수
0   2023  1분기  종로1.2.3.4가동  종로구  283336989.0
1   2023  1분기           명동   중구  141536365.0
2   2023  1분기          회현동   중구   88051490.0
3   2023  1분기          사직동  종로구   55186296.0
4   2023  1분기          소공동   중구   49501776.0
5   2023  1분기         을지로동   중구   45274020.0
6   2023  1분기          서교동  마포구   35358108.0
7   2023  1분기          광희동   중구   28814590.0
8   2023  1분기         한강로동  용산구   27848800.0
9   2023  1분기          삼선동  성북구   27614439.0
10  2023  1분기           필동   중구   24713942.0
      연도   분기          행정동  시군구        총_승객수
0   2023  2분기  종로1.2.3.4가동  종로구  297794881.0
1   2023  2분기           명동   중구  156980658.0
2   2023  2분기          회현동   중구   95372620.0
3   2023  2분기          사직동  종로구   60734460.0
4   2023  2분기          소공동   중구   52781916.0
5   2023  2분기         을지로동   중구   47887110.0
6   2023  2분기          서교동  마포구   36752784.0
7   2023  2분기          광희동   중구   31865660.0
8   2023  2분기          삼선동  성북구   30613752.0
9   2023  2분기         한강로동  용산구   29019600.0
10  2023  2분기           필동   중구   28252015.0
      연도   분기          행정동  시군구        총_승객수
0   2023  3분기  종로1.2.3.4가동  종로구  286423604.0
1   2023  3분기           명동   중구  157035214.0
2   2023  3분기          회현동   중구   92201320.0
3   2023  3분기          사직동  종로구   57735588.0
4   2023  3분기          소공동   중구   51557772.0
5   2023  3분기         을지로동   중구   47261730.0
6   2023  3분기          서교동  마포구   36073611.0
7   2023  3분기          광희동   중구   31583160.0
8   2023  3분기         한강로동  용산구   29231570.0
9   2023  3분기          삼선동  성북구   28062720.0
10  2023  3분기           필동   중구   26505127.0
      연도   분기          행정동  시군구        총_승객수
0   2023  4분기  종로1.2.3.4가동  종로구  304948224.0
1   2023  4분기           명동   중구  172860939.0
2   2023  4분기          회현동   중구   99693980.0
3   2023  4분기          사직동  종로구   64914792.0
4   2023  4분기          소공동   중구   55885368.0
5   2023  4분기         을지로동   중구   49241650.0
6   2023  4분기          서교동  마포구   38175147.0
7   2023  4분기          광희동   중구   33084970.0
8   2023  4분기          삼선동  성북구   30730662.0
9   2023  4분기         한강로동  용산구   30173610.0
10  2023  4분기           필동   중구   29270472.0

2023년 분기별 행정동 하위 순위

In [20]:
# 2023년 1분기 하위 5개 행정동
dong23_q1 = year23_df[(year23_df['연도'] == 2023) & (year23_df['분기'] == '1분기')]
bottom5_dong23_q1 = dong23_q1.nsmallest(5, '총_승객수').reset_index(drop=True)
print("2023년 1분기 하위 5개 행정동:")
print(bottom5_dong23_q1)

# 2023년 2분기 하위 5개 행정동
dong23_q2 = year23_df[(year23_df['연도'] == 2023) & (year23_df['분기'] == '2분기')]
bottom5_dong23_q2 = dong23_q2.nsmallest(5, '총_승객수').reset_index(drop=True)
print("2023년 2분기 하위 5개 행정동:")
print(bottom5_dong23_q2)

# 2023년 3분기 하위 5개 행정동
dong23_q3 = year23_df[(year23_df['연도'] == 2023) & (year23_df['분기'] == '3분기')]
bottom5_dong23_q3 = dong23_q3.nsmallest(5, '총_승객수').reset_index(drop=True)
print("2023년 3분기 하위 5개 행정동:")
print(bottom5_dong23_q3)

# 2023년 4분기 하위 5개 행정동
dong23_q4 = year23_df[(year23_df['연도'] == 2023) & (year23_df['분기'] == '4분기')]
bottom5_dong23_q4 = dong23_q4.nsmallest(5, '총_승객수').reset_index(drop=True)
print("2023년 4분기 하위 5개 행정동:")
print(bottom5_dong23_q4)

2023년 1분기 하위 5개 행정동:
     연도   분기   행정동  시군구     총_승객수
0  2023  1분기   신림동  관악구   54395.0
1  2023  1분기   수색동  은평구   78301.0
2  2023  1분기  반포본동  서초구   86064.0
3  2023  1분기   응봉동  성동구   87498.0
4  2023  1분기  방배2동  서초구  115755.0
2023년 2분기 하위 5개 행정동:
     연도   분기   행정동  시군구     총_승객수
0  2023  2분기   신림동  관악구   57026.0
1  2023  2분기   수색동  은평구   84062.0
2  2023  2분기   응봉동  성동구   92252.0
3  2023  2분기  반포본동  서초구   93272.0
4  2023  2분기  방배2동  서초구  122533.0
2023년 3분기 하위 5개 행정동:
     연도   분기   행정동  시군구     총_승객수
0  2023  3분기   신림동  관악구   56833.0
1  2023  3분기   응봉동  성동구   83765.0
2  2023  3분기  반포본동  서초구   88100.0
3  2023  3분기   수색동  은평구   92638.0
4  2023  3분기  방배2동  서초구  121512.0
2023년 4분기 하위 5개 행정동:
     연도   분기   행정동  시군구     총_승객수
0  2023  4분기   신림동  관악구   58755.0
1  2023  4분기   응봉동  성동구   89038.0
2  2023  4분기  반포본동  서초구   93899.0
3  2023  4분기   수색동  은평구  120040.0
4  2023  4분기  방배2동  서초구  123950.0

2024년 분기별 행정동 상위 순위

In [21]:
# 2024 1분기 행정동 승객_수 top 5
dong24_q1 = year24_df[(year24_df['연도'] == 2024) & (year24_df['분기'] == '1분기')]
top5_dong24_q1 = dong24_q1.nlargest(11, '총_승객수')
top5_dong24_q1 = top5_dong24_q1.reset_index(drop=True)
print(top5_dong24_q1)

# 2024 2분기 행정동 승객_수 top 5
dong24_q2 = year24_df[(year24_df['연도'] == 2024) & (year24_df['분기'] == '2분기')]
top5_dong24_q2 = dong24_q2.nlargest(11, '총_승객수')
top5_dong24_q2 = top5_dong24_q2.reset_index(drop=True)
print(top5_dong24_q2)

# 2024 분기 행정동 승객_수 top 5
dong24_q3 = year24_df[(year24_df['연도'] == 2024) & (year24_df['분기'] == '3분기')]
top5_dong24_q3 = dong24_q3.nlargest(11, '총_승객수')
top5_dong24_q3 = top5_dong24_q3.reset_index(drop=True)
print(top5_dong24_q3)

      연도   분기          행정동  시군구        총_승객수
0   2024  1분기  종로1.2.3.4가동  종로구  288272238.0
1   2024  1분기           명동   중구  157680847.0
2   2024  1분기          회현동   중구   94525950.0
3   2024  1분기          사직동  종로구   58165512.0
4   2024  1분기          소공동   중구   52071564.0
5   2024  1분기         을지로동   중구   47596290.0
6   2024  1분기          서교동  마포구   36991983.0
7   2024  1분기          광희동   중구   30967940.0
8   2024  1분기         한강로동  용산구   28717210.0
9   2024  1분기          삼선동  성북구   28375020.0
10  2024  1분기           필동   중구   27448773.0
      연도   분기          행정동  시군구        총_승객수
0   2024  2분기  종로1.2.3.4가동  종로구  301060252.0
1   2024  2분기           명동   중구  164419755.0
2   2024  2분기          회현동   중구   98038770.0
3   2024  2분기          사직동  종로구   60819792.0
4   2024  2분기          소공동   중구   52797096.0
5   2024  2분기         을지로동   중구   48111770.0
6   2024  2분기          서교동  마포구   37825560.0
7   2024  2분기          광희동   중구   32717030.0
8   2024  2분기          삼선동  성북구   31269465.0
9   2024  2분기         한강로동  용산구   29872095.0
10  2024  2분기           필동   중구   29385807.0
      연도   분기          행정동  시군구        총_승객수
0   2024  3분기  종로1.2.3.4가동  종로구  281990664.0
1   2024  3분기           명동   중구  161997809.0
2   2024  3분기          회현동   중구   94007060.0
3   2024  3분기          사직동  종로구   56356704.0
4   2024  3분기          소공동   중구   50313588.0
5   2024  3분기         을지로동   중구   46869900.0
6   2024  3분기          서교동  마포구   36985461.0
7   2024  3분기          광희동   중구   32290640.0
8   2024  3분기         한강로동  용산구   29412105.0
9   2024  3분기          삼선동  성북구   28334304.0
10  2024  3분기           필동   중구   27054093.0

2024년 분기별 행정동 하위 순위

In [22]:
# 2024년 1분기 하위 5개 행정동
dong24_q1 = year24_df[(year24_df['연도'] == 2024) & (year24_df['분기'] == '1분기')]
bottom5_dong24_q1 = dong24_q1.nsmallest(5, '총_승객수').reset_index(drop=True)
print("2024년 1분기 하위 5개 행정동:")
print(bottom5_dong24_q1)

# 2024년 2분기 하위 5개 행정동
dong24_q2 = year24_df[(year24_df['연도'] == 2024) & (year24_df['분기'] == '2분기')]
bottom5_dong24_q2 = dong24_q2.nsmallest(5, '총_승객수').reset_index(drop=True)
print("2024년 2분기 하위 5개 행정동:")
print(bottom5_dong24_q2)

# 2024년 3분기 하위 5개 행정동
dong24_q3 = year24_df[(year24_df['연도'] == 2024) & (year24_df['분기'] == '3분기')]
bottom5_dong24_q3 = dong24_q3.nsmallest(5, '총_승객수').reset_index(drop=True)
print("2024년 3분기 하위 5개 행정동:")
print(bottom5_dong24_q3)

# 2024년 4분기 하위 5개 행정동
dong24_q4 = year24_df[(year24_df['연도'] == 2024) & (year24_df['분기'] == '4분기')]
bottom5_dong24_q4 = dong24_q4.nsmallest(5, '총_승객수').reset_index(drop=True)
print("2024년 4분기 하위 5개 행정동:")
print(bottom5_dong24_q4)

2024년 1분기 하위 5개 행정동:
     연도   분기   행정동  시군구     총_승객수
0  2024  1분기   신림동  관악구   58591.0
1  2024  1분기   응봉동  성동구   87499.0
2  2024  1분기  반포본동  서초구   97674.0
3  2024  1분기   수색동  은평구  117327.0
4  2024  1분기  방배2동  서초구  118094.0
2024년 2분기 하위 5개 행정동:
     연도   분기   행정동  시군구     총_승객수
0  2024  2분기   신림동  관악구   62950.0
1  2024  2분기   응봉동  성동구   88859.0
2  2024  2분기  반포본동  서초구  110457.0
3  2024  2분기   수색동  은평구  122999.0
4  2024  2분기  방배2동  서초구  131399.0
2024년 3분기 하위 5개 행정동:
     연도   분기   행정동  시군구     총_승객수
0  2024  3분기   신림동  관악구   66244.0
1  2024  3분기   응봉동  성동구   79096.0
2  2024  3분기  반포본동  서초구  105198.0
3  2024  3분기   수색동  은평구  112709.0
4  2024  3분기  방배2동  서초구  120378.0
2024년 4분기 하위 5개 행정동:
     연도   분기   행정동  시군구    총_승객수
0  2024  4분기   신림동  관악구  35761.0
1  2024  4분기   응봉동  성동구  44259.0
2  2024  4분기  반포본동  서초구  60622.0
3  2024  4분기   수색동  은평구  63042.0
4  2024  4분기  방배2동  서초구  66888.0

In [ ]:
# 2024년 3,4분기 삭제 
year24_zero_q34 = year24[year24['분기'] != '3분기']
year24_zero_q34 = year24[year24['분기'] != '4분기']
print("3분기 데이터 삭제:")
print("4분기 데이터 삭제:")
print(year24_zero_q34)

3분기 데이터 삭제:
4분기 데이터 삭제:
        연도   분기   행정동   시군구      총_승객수
0     2024  1분기  가락1동   송파구  2260444.0
1     2024  1분기  가락2동   송파구  1180218.0
2     2024  1분기   가산동   금천구  4112467.0
3     2024  1분기  갈현1동   은평구  2943302.0
4     2024  1분기  갈현2동   은평구   684093.0
...    ...  ...   ...   ...        ...
1677  2024  3분기  화곡본동   강서구        0.0
1678  2024  3분기   황학동    중구        0.0
1679  2024  3분기   회기동  동대문구        0.0
1680  2024  3분기   후암동   용산구        0.0
1681  2024  3분기  휘경2동  동대문구        0.0

[1259 rows x 5 columns]

In [ ]:
# year24_zero_q34['분기'].isna().sum()
year24_zero_q34.to_csv('yeay24_zero_q3.csv', index=False, encoding='utf-8')
print('삭제 완료')

삭제 완료

In [32]:
year22.columns

Index(['연도', '분기', '행정동', '시군구', '총_승객수'], dtype='object')

In [ ]:
# # 데이터 병합 
# 공통컬럼 = ['연도', '분기', '행정동', '시군구', '총_승객수']
# merged_22_23 = pd.merge(year22,year23, on=공통컬럼, how='outer')
# merged_year_all = pd.merge(merged_22_23, year24_zero_q3, on=공통컬럼, how='outer')
# print(merged_year_all)

# # csv파일로 저장 
# merged_year_all.to_csv('merged_year_all.csv', index=False)
# print("병합된 데이터프레임을 'merged_year_all_csv' 파일로 저장함")

        연도   분기   행정동   시군구      총_승객수
0     2022  1분기  가락1동   송파구  1687061.0
1     2022  1분기  가락2동   송파구   939791.0
2     2022  1분기  가락본동   송파구        0.0
3     2022  1분기  가리봉동   구로구        0.0
4     2022  1분기   가산동   금천구  3436767.0
...    ...  ...   ...   ...        ...
4598  2024  4분기   효창동   용산구   460143.0
4599  2024  4분기   후암동   용산구        0.0
4600  2024  4분기  휘경1동  동대문구   873080.0
4601  2024  4분기  휘경2동  동대문구        0.0
4602  2024  4분기   흑석동   동작구   449863.0

[4603 rows x 5 columns]
병합된 데이터프레임을 'merged_year_all_csv' 파일로 저장함