In [78]:
import numpy as np 
import pandas as pd

19, 20, 21년도파일과 지하철 파일 4개 불러오기

In [79]:
sw19 = pd.read_csv('file/subway_2019.csv', encoding='euc-kr')
sw20 = pd.read_csv('file/subway_2020.csv', encoding='euc-kr')
sw21 = pd.read_csv('file/subway_2021.csv', encoding='euc-kr')
dong_st = pd.read_csv('file/dong_station.csv', encoding='euc-kr')

In [80]:
sw19
sw20
sw21
dong_st

    station_name line   gu  dong   gu_dong
0            NaN  NaN  강남구  개포1동  강남구_개포1동
1          대모산입구  분당선  강남구  개포2동  강남구_개포2동
2             구룡  분당선  강남구  개포2동  강남구_개포2동
3            개포동  분당선  강남구  개포2동  강남구_개포2동
4             대청  3호선  강남구  개포3동  강남구_개포3동
..           ...  ...  ...   ...       ...
593   봉화산(서울의료원)  6호선  중랑구  신내1동  중랑구_신내1동
594          NaN  NaN  중랑구  신내2동  중랑구_신내2동
595          NaN  NaN  중랑구  중화1동  중랑구_중화1동
596           중화  7호선  중랑구  중화2동  중랑구_중화2동
597           중랑  중앙선  중랑구  중화2동  중랑구_중화2동

[598 rows x 5 columns]

In [81]:
# 컬럼명 바꾸기 
dong_st.columns = ['지하철역', '호선명', '시군구', '행정동', '구_동']
dong_st

           지하철역  호선명  시군구   행정동       구_동
0           NaN  NaN  강남구  개포1동  강남구_개포1동
1         대모산입구  분당선  강남구  개포2동  강남구_개포2동
2            구룡  분당선  강남구  개포2동  강남구_개포2동
3           개포동  분당선  강남구  개포2동  강남구_개포2동
4            대청  3호선  강남구  개포3동  강남구_개포3동
..          ...  ...  ...   ...       ...
593  봉화산(서울의료원)  6호선  중랑구  신내1동  중랑구_신내1동
594         NaN  NaN  중랑구  신내2동  중랑구_신내2동
595         NaN  NaN  중랑구  중화1동  중랑구_중화1동
596          중화  7호선  중랑구  중화2동  중랑구_중화2동
597          중랑  중앙선  중랑구  중화2동  중랑구_중화2동

[598 rows x 5 columns]

In [82]:
print(dong_st['호선명'].unique())
print(sw19['호선명'].unique())

[nan '분당선' '3호선' '신분당선(연장2)' '7호선' '수도권 광역급행철도' '2호선' '9호선(연장)' '9호선'
 '5호선' '8호선' '4호선' '우이신설선' '공항철도1호선' '김포골드라인' '서해선' '신림선' '경인선' '경부선'
 '6호선' '경원선' '1호선' '중앙선' '경의중앙선' '신분당선' '경춘선']
['1호선' '2호선' '3호선' '4호선' '5호선' '6호선' '7호선' '8호선' '9호선' '9호선2~3단계' '경강선'
 '경부선' '경원선' '경의선' '경인선' '경춘선' '공항철도 1호선' '과천선' '분당선' '수인선' '안산선' '우이신설선'
 '일산선' '장항선' '중앙선']

In [83]:
# 구_동 컬럼 삭제 
dong_st.drop(columns={'구_동'}, inplace=True)
dong_st

           지하철역  호선명  시군구   행정동
0           NaN  NaN  강남구  개포1동
1         대모산입구  분당선  강남구  개포2동
2            구룡  분당선  강남구  개포2동
3           개포동  분당선  강남구  개포2동
4            대청  3호선  강남구  개포3동
..          ...  ...  ...   ...
593  봉화산(서울의료원)  6호선  중랑구  신내1동
594         NaN  NaN  중랑구  신내2동
595         NaN  NaN  중랑구  중화1동
596          중화  7호선  중랑구  중화2동
597          중랑  중앙선  중랑구  중화2동

[598 rows x 4 columns]

In [84]:
print(sw19.columns)
print(dong_st.columns)

Index(['사용월', '호선명', '지하철역', '유임승차인원', '무임승차인원', '유임하차인원', '무임하차인원', '작업일자'], dtype='object')
Index(['지하철역', '호선명', '시군구', '행정동'], dtype='object')

In [85]:
# 작업일자 컬럼 삭제 
sw19.drop(columns='작업일자', inplace=True)
sw20.drop(columns='작업일자', inplace=True)
sw21.drop(columns='작업일자', inplace=True)

In [86]:
print(dong_st, sw19, sw20, sw21)

           지하철역  호선명  시군구   행정동
0           NaN  NaN  강남구  개포1동
1         대모산입구  분당선  강남구  개포2동
2            구룡  분당선  강남구  개포2동
3           개포동  분당선  강남구  개포2동
4            대청  3호선  강남구  개포3동
..          ...  ...  ...   ...
593  봉화산(서울의료원)  6호선  중랑구  신내1동
594         NaN  NaN  중랑구  신내2동
595         NaN  NaN  중랑구  중화1동
596          중화  7호선  중랑구  중화2동
597          중랑  중앙선  중랑구  중화2동

[598 rows x 4 columns]          사용월  호선명  지하철역   유임승차인원  무임승차인원   유임하차인원  무임하차인원
0     201912  1호선   제기동   285500  330880   276924  350887
1     201912  1호선  종로5가   577725  289976   595317  279234
2     201912  1호선  종로3가   675882  412567   643348  385274
3     201912  1호선    종각  1275450  192545  1219017  180799
4     201912  1호선    시청   740715  124589   747266  125967
...      ...  ...   ...      ...     ...      ...     ...
7370  201901  중앙선    오빈     5489    3794     5252    3829
7371  201901  중앙선    망우   172521   69556   167062   70878
7372  201901  중앙선    도농   216211   58716   187739   55895
7373  201901  중앙선    덕소   139275   50107   135740   50007
7374  201901  중앙선    양수    38629   16598    38962   16754

[7375 rows x 7 columns]          사용월  호선명  지하철역  유임승차인원  무임승차인원  유임하차인원  무임하차인원
0     202012  1호선   제기동  193158  192893  189518  206219
1     202012  1호선   동대문  169229   88712  158990   87422
2     202012  1호선   서울역  708925  133421  674149  123397
3     202012  1호선  종로3가  305614  187492  275379  175042
4     202012  1호선  종로5가  284517  180822  288101  174176
...      ...  ...   ...     ...     ...     ...     ...
7191  202001  중앙선   운길산   13512    6141   12273    6106
7192  202001  중앙선    용문   34349   31140   34971   31016
7193  202001  중앙선    팔당   19533    6073   19476    5931
7194  202001  중앙선    신원    3044    2517    2683    2184
7195  202001  중앙선    양평   63231   30793   64149   30880

[7196 rows x 7 columns]          사용월  호선명          지하철역  유임승차인원  무임승차인원  유임하차인원  무임하차인원
0     202112  1호선  청량리(서울시립대입구)  310669  220908  311345  221568
1     202112  1호선          종로5가  359249  220044  362984  210306
2     202112  1호선          종로3가  407934  249355  375067  234742
3     202112  1호선            종각  755897  116282  740655  108719
4     202112  1호선           제기동  217819  226280  208609  241771
...      ...  ...           ...     ...     ...     ...     ...
7282  202101  중앙선            양정   11604    4423    9672    3948
7283  202101  중앙선            덕소   91503   30070   91806   30576
7284  202101  중앙선            용문   18880   18177   19008   18107
7285  202101  중앙선            양평   38720   16674   37894   16687
7286  202101  중앙선            양수   24279   11584   24136   11769

[7287 rows x 7 columns]

처음 가져왔던 데이터 전처리 후 두 데이터를 '지하철역'과 '호선명'으로 병합

In [87]:
# '지하철역'과 '호선명'으로 데이터 병합 
station_merge19 = pd.merge(sw19, dong_st, how='outer', on=['지하철역', '호선명'])
station_merge20 = pd.merge(sw20, dong_st, how='outer', on=['지하철역', '호선명'])
station_merge21 = pd.merge(sw21, dong_st, how='outer', on=['지하철역', '호선명'])

print(station_merge19, station_merge20, station_merge21)

           사용월    호선명      지하철역   유임승차인원   무임승차인원   유임하차인원   무임하차인원  시군구   행정동
0     201912.0  우이신설선  4.19민주묘지  61832.0  32442.0  59882.0  30206.0  강북구   우이동
1     201911.0  우이신설선  4.19민주묘지  74480.0  32496.0  74086.0  30133.0  강북구   우이동
2     201910.0  우이신설선  4.19민주묘지  77817.0  35133.0  76453.0  32335.0  강북구   우이동
3     201909.0  우이신설선  4.19민주묘지  71959.0  31068.0  70973.0  28508.0  강북구   우이동
4     201908.0  우이신설선  4.19민주묘지  50245.0  32013.0  47766.0  29384.0  강북구   우이동
...        ...    ...       ...      ...      ...      ...      ...  ...   ...
7624       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  면목5동
7625       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  면목7동
7626       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구   묵1동
7627       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  신내2동
7628       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  중화1동

[7629 rows x 9 columns]            사용월    호선명      지하철역   유임승차인원   무임승차인원   유임하차인원   무임하차인원  시군구   행정동
0     202012.0  우이신설선  4.19민주묘지  38101.0  24248.0  37715.0  21876.0  강북구   우이동
1     202011.0  우이신설선  4.19민주묘지  47094.0  28318.0  46851.0  25855.0  강북구   우이동
2     202010.0  우이신설선  4.19민주묘지  45957.0  31491.0  44921.0  27925.0  강북구   우이동
3     202009.0  우이신설선  4.19민주묘지  37894.0  27137.0  37524.0  24332.0  강북구   우이동
4     202008.0  우이신설선  4.19민주묘지  38134.0  25599.0  37443.0  23839.0  강북구   우이동
...        ...    ...       ...      ...      ...      ...      ...  ...   ...
7445       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  면목5동
7446       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  면목7동
7447       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구   묵1동
7448       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  신내2동
7449       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  중화1동

[7450 rows x 9 columns]            사용월    호선명      지하철역   유임승차인원   무임승차인원   유임하차인원   무임하차인원  시군구   행정동
0     202112.0  우이신설선  4.19민주묘지  47280.0  29715.0  45573.0  27003.0  강북구   우이동
1     202111.0  우이신설선  4.19민주묘지  51474.0  31567.0  48888.0  28506.0  강북구   우이동
2     202110.0  우이신설선  4.19민주묘지  47136.0  33743.0  45146.0  29650.0  강북구   우이동
3     202109.0  우이신설선  4.19민주묘지  42324.0  31747.0  40940.0  27938.0  강북구   우이동
4     202108.0  우이신설선  4.19민주묘지  39970.0  30537.0  39142.0  26783.0  강북구   우이동
...        ...    ...       ...      ...      ...      ...      ...  ...   ...
7550       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  면목5동
7551       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  면목7동
7552       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구   묵1동
7553       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  신내2동
7554       NaN    NaN       NaN      NaN      NaN      NaN      NaN  중랑구  중화1동

[7555 rows x 9 columns]

병합하면서 변환된 .0(float) 열을 int로 변환

In [88]:
station_merges = [station_merge19, station_merge20, station_merge21]

for df in station_merges: 
    for col in df.select_dtypes(include='float').columns:
        df[col] = df[col].fillna(0).astype(int)


print(station_merge19, station_merge20, station_merge21)

         사용월    호선명      지하철역  유임승차인원  무임승차인원  유임하차인원  무임하차인원  시군구   행정동
0     201912  우이신설선  4.19민주묘지   61832   32442   59882   30206  강북구   우이동
1     201911  우이신설선  4.19민주묘지   74480   32496   74086   30133  강북구   우이동
2     201910  우이신설선  4.19민주묘지   77817   35133   76453   32335  강북구   우이동
3     201909  우이신설선  4.19민주묘지   71959   31068   70973   28508  강북구   우이동
4     201908  우이신설선  4.19민주묘지   50245   32013   47766   29384  강북구   우이동
...      ...    ...       ...     ...     ...     ...     ...  ...   ...
7624       0    NaN       NaN       0       0       0       0  중랑구  면목5동
7625       0    NaN       NaN       0       0       0       0  중랑구  면목7동
7626       0    NaN       NaN       0       0       0       0  중랑구   묵1동
7627       0    NaN       NaN       0       0       0       0  중랑구  신내2동
7628       0    NaN       NaN       0       0       0       0  중랑구  중화1동

[7629 rows x 9 columns]          사용월    호선명      지하철역  유임승차인원  무임승차인원  유임하차인원  무임하차인원  시군구   행정동
0     202012  우이신설선  4.19민주묘지   38101   24248   37715   21876  강북구   우이동
1     202011  우이신설선  4.19민주묘지   47094   28318   46851   25855  강북구   우이동
2     202010  우이신설선  4.19민주묘지   45957   31491   44921   27925  강북구   우이동
3     202009  우이신설선  4.19민주묘지   37894   27137   37524   24332  강북구   우이동
4     202008  우이신설선  4.19민주묘지   38134   25599   37443   23839  강북구   우이동
...      ...    ...       ...     ...     ...     ...     ...  ...   ...
7445       0    NaN       NaN       0       0       0       0  중랑구  면목5동
7446       0    NaN       NaN       0       0       0       0  중랑구  면목7동
7447       0    NaN       NaN       0       0       0       0  중랑구   묵1동
7448       0    NaN       NaN       0       0       0       0  중랑구  신내2동
7449       0    NaN       NaN       0       0       0       0  중랑구  중화1동

[7450 rows x 9 columns]          사용월    호선명      지하철역  유임승차인원  무임승차인원  유임하차인원  무임하차인원  시군구   행정동
0     202112  우이신설선  4.19민주묘지   47280   29715   45573   27003  강북구   우이동
1     202111  우이신설선  4.19민주묘지   51474   31567   48888   28506  강북구   우이동
2     202110  우이신설선  4.19민주묘지   47136   33743   45146   29650  강북구   우이동
3     202109  우이신설선  4.19민주묘지   42324   31747   40940   27938  강북구   우이동
4     202108  우이신설선  4.19민주묘지   39970   30537   39142   26783  강북구   우이동
...      ...    ...       ...     ...     ...     ...     ...  ...   ...
7550       0    NaN       NaN       0       0       0       0  중랑구  면목5동
7551       0    NaN       NaN       0       0       0       0  중랑구  면목7동
7552       0    NaN       NaN       0       0       0       0  중랑구   묵1동
7553       0    NaN       NaN       0       0       0       0  중랑구  신내2동
7554       0    NaN       NaN       0       0       0       0  중랑구  중화1동

[7555 rows x 9 columns]

NaN 값 0으로 채우기

In [89]:
station_merge19.fillna(0, inplace=True)
station_merge20.fillna(0, inplace=True)
station_merge21.fillna(0, inplace=True)

station_merge19
# station_merge20
# station_merge21

         사용월    호선명      지하철역  유임승차인원  무임승차인원  유임하차인원  무임하차인원  시군구   행정동
0     201912  우이신설선  4.19민주묘지   61832   32442   59882   30206  강북구   우이동
1     201911  우이신설선  4.19민주묘지   74480   32496   74086   30133  강북구   우이동
2     201910  우이신설선  4.19민주묘지   77817   35133   76453   32335  강북구   우이동
3     201909  우이신설선  4.19민주묘지   71959   31068   70973   28508  강북구   우이동
4     201908  우이신설선  4.19민주묘지   50245   32013   47766   29384  강북구   우이동
...      ...    ...       ...     ...     ...     ...     ...  ...   ...
7624       0      0         0       0       0       0       0  중랑구  면목5동
7625       0      0         0       0       0       0       0  중랑구  면목7동
7626       0      0         0       0       0       0       0  중랑구   묵1동
7627       0      0         0       0       0       0       0  중랑구  신내2동
7628       0      0         0       0       0       0       0  중랑구  중화1동

[7629 rows x 9 columns]

In [90]:
station_merge19.dtypes

사용월        int32
호선명       object
지하철역      object
유임승차인원     int32
무임승차인원     int32
유임하차인원     int32
무임하차인원     int32
시군구       object
행정동       object
dtype: object

In [91]:
# 총 승하차인원 컬럼 생성 

# 데이터 프레임 리스트
station_all = [station_merge19, station_merge20, station_merge21]

# 각 데이터 프레임에 대해 합산 컬럼 추가 
for df in station_all: 
    df['총승하차인원'] = df[['유임승차인원', '무임승차인원', '유임하차인원', '무임하차인원']].sum(axis=1)

station_merge19 
station_merge20
station_merge21

,사용월,호선명,지하철역,유임승차인원,무임승차인원,유임하차인원,무임하차인원,시군구,행정동,총승하차인원
0,202112,우이신설선,4.19민주묘지,47280,29715,45573,27003,강북구,우이동,149571
1,202111,우이신설선,4.19민주묘지,51474,31567,48888,28506,강북구,우이동,160435
2,202110,우이신설선,4.19민주묘지,47136,33743,45146,29650,강북구,우이동,155675
3,202109,우이신설선,4.19민주묘지,42324,31747,40940,27938,강북구,우이동,142949
4,202108,우이신설선,4.19민주묘지,39970,30537,39142,26783,강북구,우이동,136432
...,...,...,...,...,...,...,...,...,...,...
7550,0,0,0,0,0,0,0,중랑구,면목5동,0
7551,0,0,0,0,0,0,0,중랑구,면목7동,0
7552,0,0,0,0,0,0,0,중랑구,묵1동,0
7553,0,0,0,0,0,0,0,중랑구,신내2동,0
7554,0,0,0,0,0,0,0,중랑구,중화1동,0

'총 승객수' 컬럼 생성후, '유임승차인원, 무임승차인원, 유임하차인원, 무임하차인원', 필요 x --> 삭제

In [92]:
# station_merge19.drop(columns=['유임승차인원','무임승차인원','유임하차인원','무임하차인원'], inplace=True)
# station_merge20.drop(columns=['유임승차인원','무임승차인원','유임하차인원','무임하차인원'], inplace=True)
# station_merge21.drop(columns=['유임승차인원','무임승차인원','유임하차인원','무임하차인원'], inplace=True)

# --> 

columns_to_drop = ['유임승차인원', '무임승차인원', '유임하차인원', '무임하차인원']
station_merges = [station_merge19, station_merge20, station_merge21]

for df in station_merges: 
    df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

In [93]:
# 삭제 확인
print(station_merge19.columns)
print(station_merge20.columns)
print(station_merge21.columns)

Index(['사용월', '호선명', '지하철역', '시군구', '행정동', '총승하차인원'], dtype='object')
Index(['사용월', '호선명', '지하철역', '시군구', '행정동', '총승하차인원'], dtype='object')
Index(['사용월', '호선명', '지하철역', '시군구', '행정동', '총승하차인원'], dtype='object')

In [94]:
# 데이터프레임 리스트 
station_merge_all = [station_merge19, station_merge20, station_merge21]

# 각 데이터프레임에서 '월' 추출 및 '분기' 계산 
for df in station_merge_all: 
    # '월' 추출
    df['월'] = df['사용월'].astype(str).str[-2:].astype(int)

    # '분기' 계산
    df['분기'] = df['월'].apply(lambda x: f"{(x-1)//3 + 1}분기")

# 결과 확인 (각 데이터프레임의 일부만 출력)
for df in station_all: 
    print(df[['사용월', '월', '분기']].head())

      사용월   월   분기
0  201912  12  4분기
1  201911  11  4분기
2  201910  10  4분기
3  201909   9  3분기
4  201908   8  3분기
      사용월   월   분기
0  202012  12  4분기
1  202011  11  4분기
2  202010  10  4분기
3  202009   9  3분기
4  202008   8  3분기
      사용월   월   분기
0  202112  12  4분기
1  202111  11  4분기
2  202110  10  4분기
3  202109   9  3분기
4  202108   8  3분기

In [95]:
print(station_merge19, station_merge20, station_merge21)

         사용월    호선명      지하철역  시군구   행정동  총승하차인원   월   분기
0     201912  우이신설선  4.19민주묘지  강북구   우이동  184362  12  4분기
1     201911  우이신설선  4.19민주묘지  강북구   우이동  211195  11  4분기
2     201910  우이신설선  4.19민주묘지  강북구   우이동  221738  10  4분기
3     201909  우이신설선  4.19민주묘지  강북구   우이동  202508   9  3분기
4     201908  우이신설선  4.19민주묘지  강북구   우이동  159408   8  3분기
...      ...    ...       ...  ...   ...     ...  ..  ...
7624       0      0         0  중랑구  면목5동       0   0  0분기
7625       0      0         0  중랑구  면목7동       0   0  0분기
7626       0      0         0  중랑구   묵1동       0   0  0분기
7627       0      0         0  중랑구  신내2동       0   0  0분기
7628       0      0         0  중랑구  중화1동       0   0  0분기

[7629 rows x 8 columns]          사용월    호선명      지하철역  시군구   행정동  총승하차인원   월   분기
0     202012  우이신설선  4.19민주묘지  강북구   우이동  121940  12  4분기
1     202011  우이신설선  4.19민주묘지  강북구   우이동  148118  11  4분기
2     202010  우이신설선  4.19민주묘지  강북구   우이동  150294  10  4분기
3     202009  우이신설선  4.19민주묘지  강북구   우이동  126887   9  3분기
4     202008  우이신설선  4.19민주묘지  강북구   우이동  125015   8  3분기
...      ...    ...       ...  ...   ...     ...  ..  ...
7445       0      0         0  중랑구  면목5동       0   0  0분기
7446       0      0         0  중랑구  면목7동       0   0  0분기
7447       0      0         0  중랑구   묵1동       0   0  0분기
7448       0      0         0  중랑구  신내2동       0   0  0분기
7449       0      0         0  중랑구  중화1동       0   0  0분기

[7450 rows x 8 columns]          사용월    호선명      지하철역  시군구   행정동  총승하차인원   월   분기
0     202112  우이신설선  4.19민주묘지  강북구   우이동  149571  12  4분기
1     202111  우이신설선  4.19민주묘지  강북구   우이동  160435  11  4분기
2     202110  우이신설선  4.19민주묘지  강북구   우이동  155675  10  4분기
3     202109  우이신설선  4.19민주묘지  강북구   우이동  142949   9  3분기
4     202108  우이신설선  4.19민주묘지  강북구   우이동  136432   8  3분기
...      ...    ...       ...  ...   ...     ...  ..  ...
7550       0      0         0  중랑구  면목5동       0   0  0분기
7551       0      0         0  중랑구  면목7동       0   0  0분기
7552       0      0         0  중랑구   묵1동       0   0  0분기
7553       0      0         0  중랑구  신내2동       0   0  0분기
7554       0      0         0  중랑구  중화1동       0   0  0분기

[7555 rows x 8 columns]

In [96]:
# 년도별 역갯수 
print(station_merge19['지하철역'].nunique())
print(station_merge20['지하철역'].nunique())
print(station_merge21['지하철역'].nunique())

522
534
539

In [97]:
# 사용월 컬럼에서 뒤의 두자리 제거 
# station_merge19
# station_merge20
# station_merge21

def remove_last_two_digits(df):
    df['사용월'] = df['사용월'].astype(str).str[:4]
    return df

station_merge19 = remove_last_two_digits(station_merge19)
station_merge20 = remove_last_two_digits(station_merge20)
station_merge21 = remove_last_two_digits(station_merge21)

print(station_merge19,station_merge20,station_merge21)

       사용월    호선명      지하철역  시군구   행정동  총승하차인원   월   분기
0     2019  우이신설선  4.19민주묘지  강북구   우이동  184362  12  4분기
1     2019  우이신설선  4.19민주묘지  강북구   우이동  211195  11  4분기
2     2019  우이신설선  4.19민주묘지  강북구   우이동  221738  10  4분기
3     2019  우이신설선  4.19민주묘지  강북구   우이동  202508   9  3분기
4     2019  우이신설선  4.19민주묘지  강북구   우이동  159408   8  3분기
...    ...    ...       ...  ...   ...     ...  ..  ...
7624     0      0         0  중랑구  면목5동       0   0  0분기
7625     0      0         0  중랑구  면목7동       0   0  0분기
7626     0      0         0  중랑구   묵1동       0   0  0분기
7627     0      0         0  중랑구  신내2동       0   0  0분기
7628     0      0         0  중랑구  중화1동       0   0  0분기

[7629 rows x 8 columns]        사용월    호선명      지하철역  시군구   행정동  총승하차인원   월   분기
0     2020  우이신설선  4.19민주묘지  강북구   우이동  121940  12  4분기
1     2020  우이신설선  4.19민주묘지  강북구   우이동  148118  11  4분기
2     2020  우이신설선  4.19민주묘지  강북구   우이동  150294  10  4분기
3     2020  우이신설선  4.19민주묘지  강북구   우이동  126887   9  3분기
4     2020  우이신설선  4.19민주묘지  강북구   우이동  125015   8  3분기
...    ...    ...       ...  ...   ...     ...  ..  ...
7445     0      0         0  중랑구  면목5동       0   0  0분기
7446     0      0         0  중랑구  면목7동       0   0  0분기
7447     0      0         0  중랑구   묵1동       0   0  0분기
7448     0      0         0  중랑구  신내2동       0   0  0분기
7449     0      0         0  중랑구  중화1동       0   0  0분기

[7450 rows x 8 columns]        사용월    호선명      지하철역  시군구   행정동  총승하차인원   월   분기
0     2021  우이신설선  4.19민주묘지  강북구   우이동  149571  12  4분기
1     2021  우이신설선  4.19민주묘지  강북구   우이동  160435  11  4분기
2     2021  우이신설선  4.19민주묘지  강북구   우이동  155675  10  4분기
3     2021  우이신설선  4.19민주묘지  강북구   우이동  142949   9  3분기
4     2021  우이신설선  4.19민주묘지  강북구   우이동  136432   8  3분기
...    ...    ...       ...  ...   ...     ...  ..  ...
7550     0      0         0  중랑구  면목5동       0   0  0분기
7551     0      0         0  중랑구  면목7동       0   0  0분기
7552     0      0         0  중랑구   묵1동       0   0  0분기
7553     0      0         0  중랑구  신내2동       0   0  0분기
7554     0      0         0  중랑구  중화1동       0   0  0분기

[7555 rows x 8 columns]

In [ ]:
# 년분기 컬럼생성
# station_merge['년분기'] = station_merge19['연도'] + station_merge['분기'].str.replace('분기','')
# station_merge19

'사용월'과 '분기'로 년분기 컬럼 생성

In [98]:
station_merge19
station_merge20
station_merge21

def add_year_quarter(df):
    # '사용월'과 '분기' 컬럼을 합쳐서 '년분기' 컬럼을 생성
    df['년분기'] = df['사용월'].astype(str) + df['분기'].str.replace('분기','')
    return df

# 각 데이터프레임에 '년분기' 컬럼을 추가
station_merge19 = add_year_quarter(station_merge19)
station_merge20 = add_year_quarter(station_merge20)
station_merge21 = add_year_quarter(station_merge21)

In [99]:
print(station_merge19, station_merge20, station_merge21)

       사용월    호선명      지하철역  시군구   행정동  총승하차인원   월   분기    년분기
0     2019  우이신설선  4.19민주묘지  강북구   우이동  184362  12  4분기  20194
1     2019  우이신설선  4.19민주묘지  강북구   우이동  211195  11  4분기  20194
2     2019  우이신설선  4.19민주묘지  강북구   우이동  221738  10  4분기  20194
3     2019  우이신설선  4.19민주묘지  강북구   우이동  202508   9  3분기  20193
4     2019  우이신설선  4.19민주묘지  강북구   우이동  159408   8  3분기  20193
...    ...    ...       ...  ...   ...     ...  ..  ...    ...
7624     0      0         0  중랑구  면목5동       0   0  0분기     00
7625     0      0         0  중랑구  면목7동       0   0  0분기     00
7626     0      0         0  중랑구   묵1동       0   0  0분기     00
7627     0      0         0  중랑구  신내2동       0   0  0분기     00
7628     0      0         0  중랑구  중화1동       0   0  0분기     00

[7629 rows x 9 columns]        사용월    호선명      지하철역  시군구   행정동  총승하차인원   월   분기    년분기
0     2020  우이신설선  4.19민주묘지  강북구   우이동  121940  12  4분기  20204
1     2020  우이신설선  4.19민주묘지  강북구   우이동  148118  11  4분기  20204
2     2020  우이신설선  4.19민주묘지  강북구   우이동  150294  10  4분기  20204
3     2020  우이신설선  4.19민주묘지  강북구   우이동  126887   9  3분기  20203
4     2020  우이신설선  4.19민주묘지  강북구   우이동  125015   8  3분기  20203
...    ...    ...       ...  ...   ...     ...  ..  ...    ...
7445     0      0         0  중랑구  면목5동       0   0  0분기     00
7446     0      0         0  중랑구  면목7동       0   0  0분기     00
7447     0      0         0  중랑구   묵1동       0   0  0분기     00
7448     0      0         0  중랑구  신내2동       0   0  0분기     00
7449     0      0         0  중랑구  중화1동       0   0  0분기     00

[7450 rows x 9 columns]        사용월    호선명      지하철역  시군구   행정동  총승하차인원   월   분기    년분기
0     2021  우이신설선  4.19민주묘지  강북구   우이동  149571  12  4분기  20214
1     2021  우이신설선  4.19민주묘지  강북구   우이동  160435  11  4분기  20214
2     2021  우이신설선  4.19민주묘지  강북구   우이동  155675  10  4분기  20214
3     2021  우이신설선  4.19민주묘지  강북구   우이동  142949   9  3분기  20213
4     2021  우이신설선  4.19민주묘지  강북구   우이동  136432   8  3분기  20213
...    ...    ...       ...  ...   ...     ...  ..  ...    ...
7550     0      0         0  중랑구  면목5동       0   0  0분기     00
7551     0      0         0  중랑구  면목7동       0   0  0분기     00
7552     0      0         0  중랑구   묵1동       0   0  0분기     00
7553     0      0         0  중랑구  신내2동       0   0  0분기     00
7554     0      0         0  중랑구  중화1동       0   0  0분기     00

[7555 rows x 9 columns]

In [100]:
# 변수명 바꾸기 (길어서 줄이기 ㅎ..)
sw_19 = station_merge19
sw_20 = station_merge20
sw_21 = station_merge21

In [101]:
sw_19
sw_20
sw_21

       사용월    호선명      지하철역  시군구   행정동  총승하차인원   월   분기    년분기
0     2021  우이신설선  4.19민주묘지  강북구   우이동  149571  12  4분기  20214
1     2021  우이신설선  4.19민주묘지  강북구   우이동  160435  11  4분기  20214
2     2021  우이신설선  4.19민주묘지  강북구   우이동  155675  10  4분기  20214
3     2021  우이신설선  4.19민주묘지  강북구   우이동  142949   9  3분기  20213
4     2021  우이신설선  4.19민주묘지  강북구   우이동  136432   8  3분기  20213
...    ...    ...       ...  ...   ...     ...  ..  ...    ...
7550     0      0         0  중랑구  면목5동       0   0  0분기     00
7551     0      0         0  중랑구  면목7동       0   0  0분기     00
7552     0      0         0  중랑구   묵1동       0   0  0분기     00
7553     0      0         0  중랑구  신내2동       0   0  0분기     00
7554     0      0         0  중랑구  중화1동       0   0  0분기     00

[7555 rows x 9 columns]

In [102]:
sw_19 = sw_19.drop(columns=['월', '분기'])
sw_20 = sw_20.drop(columns=['월', '분기'])
sw_21 = sw_21.drop(columns=['월', '분기'])

sw_19 = sw_19.drop(columns='사용월')
sw_20 = sw_20.drop(columns='사용월')
sw_21 = sw_21.drop(columns='사용월')

In [103]:
print(sw_19, sw_20, sw_21)

        호선명      지하철역  시군구   행정동  총승하차인원    년분기
0     우이신설선  4.19민주묘지  강북구   우이동  184362  20194
1     우이신설선  4.19민주묘지  강북구   우이동  211195  20194
2     우이신설선  4.19민주묘지  강북구   우이동  221738  20194
3     우이신설선  4.19민주묘지  강북구   우이동  202508  20193
4     우이신설선  4.19민주묘지  강북구   우이동  159408  20193
...     ...       ...  ...   ...     ...    ...
7624      0         0  중랑구  면목5동       0     00
7625      0         0  중랑구  면목7동       0     00
7626      0         0  중랑구   묵1동       0     00
7627      0         0  중랑구  신내2동       0     00
7628      0         0  중랑구  중화1동       0     00

[7629 rows x 6 columns]         호선명      지하철역  시군구   행정동  총승하차인원    년분기
0     우이신설선  4.19민주묘지  강북구   우이동  121940  20204
1     우이신설선  4.19민주묘지  강북구   우이동  148118  20204
2     우이신설선  4.19민주묘지  강북구   우이동  150294  20204
3     우이신설선  4.19민주묘지  강북구   우이동  126887  20203
4     우이신설선  4.19민주묘지  강북구   우이동  125015  20203
...     ...       ...  ...   ...     ...    ...
7445      0         0  중랑구  면목5동       0     00
7446      0         0  중랑구  면목7동       0     00
7447      0         0  중랑구   묵1동       0     00
7448      0         0  중랑구  신내2동       0     00
7449      0         0  중랑구  중화1동       0     00

[7450 rows x 6 columns]         호선명      지하철역  시군구   행정동  총승하차인원    년분기
0     우이신설선  4.19민주묘지  강북구   우이동  149571  20214
1     우이신설선  4.19민주묘지  강북구   우이동  160435  20214
2     우이신설선  4.19민주묘지  강북구   우이동  155675  20214
3     우이신설선  4.19민주묘지  강북구   우이동  142949  20213
4     우이신설선  4.19민주묘지  강북구   우이동  136432  20213
...     ...       ...  ...   ...     ...    ...
7550      0         0  중랑구  면목5동       0     00
7551      0         0  중랑구  면목7동       0     00
7552      0         0  중랑구   묵1동       0     00
7553      0         0  중랑구  신내2동       0     00
7554      0         0  중랑구  중화1동       0     00

[7555 rows x 6 columns]

'지하철역' 컬럼을 문자열로 변환

In [104]:
# '지하철역' 컬럼을 문자열로 변환 
sw_19.loc[:, '지하철역'] = sw_19['지하철역'].astype(str)
sw_20.loc[:, '지하철역'] = sw_20['지하철역'].astype(str)
sw_21.loc[:, '지하철역'] = sw_21['지하철역'].astype(str)

# 결과 확인 
print(sw_19.head())
print(sw_20.head())
print(sw_21.head())

     호선명      지하철역  시군구  행정동  총승하차인원    년분기
0  우이신설선  4.19민주묘지  강북구  우이동  184362  20194
1  우이신설선  4.19민주묘지  강북구  우이동  211195  20194
2  우이신설선  4.19민주묘지  강북구  우이동  221738  20194
3  우이신설선  4.19민주묘지  강북구  우이동  202508  20193
4  우이신설선  4.19민주묘지  강북구  우이동  159408  20193
     호선명      지하철역  시군구  행정동  총승하차인원    년분기
0  우이신설선  4.19민주묘지  강북구  우이동  121940  20204
1  우이신설선  4.19민주묘지  강북구  우이동  148118  20204
2  우이신설선  4.19민주묘지  강북구  우이동  150294  20204
3  우이신설선  4.19민주묘지  강북구  우이동  126887  20203
4  우이신설선  4.19민주묘지  강북구  우이동  125015  20203
     호선명      지하철역  시군구  행정동  총승하차인원    년분기
0  우이신설선  4.19민주묘지  강북구  우이동  149571  20214
1  우이신설선  4.19민주묘지  강북구  우이동  160435  20214
2  우이신설선  4.19민주묘지  강북구  우이동  155675  20214
3  우이신설선  4.19민주묘지  강북구  우이동  142949  20213
4  우이신설선  4.19민주묘지  강북구  우이동  136432  20213

In [105]:
# '지하철역' 컬럼에서 고유값의 개수 확인 
print(sw_19['지하철역'].unique())
print(sw_20['지하철역'].unique())
print(sw_21['지하철역'].unique())

['4.19민주묘지' '가능' '가락시장' '가산디지털단지' '가양' '가오리' '가좌' '가천대' '가평' '간석' '갈매'
 '강남' '강남구청' '강동' '강동구청' '강매' '강변(동서울터미널)' '강일' '강촌' '개롱' '개봉' '개포동' '개화'
 '개화산' '거여' '건대입구' '검암' '경기광주' '경마공원' '경복궁(정부서울청사)' '경찰병원' '계양' '고덕'
 '고려대(종암)' '고속터미널' '고잔' '곡산' '곤지암' '공덕' '공릉(서울과학기술대)' '공항시장' '공항화물청사' '과천'
 '관악' '관악산(서울대)' '광나루(장신대)' '광명' '광명사거리' '광운대' '광화문(세종문화회관)' '광흥창(서강)'
 '교대(법원.검찰청)' '구로' '구로디지털단지' '구룡' '구리' '구반포' '구산' '구성' '구의(광진구청)' '구일'
 '구파발' '국수' '국회의사당' '군자(능동)' '군포' '굴봉산' '굴포천' '굽은다리(강동구민회관앞)' '금곡' '금릉'
 '금정' '금천구청' '금촌' '금호' '기흥' '길동' '길음' '김유정' '김포공항' '까치산' '까치울' '낙성대' '남구로'
 '남동인더스파크' '남부터미널(예술의전당)' '남성' '남영' '남춘천' '남태령' '남한산성입구(성남법원.검찰청)' '내방'
 '노들' '노량진' '노원' '녹번' '녹사평(용산구청)' '녹양' '녹천' '논현' '능곡' '단대오거리' '달월' '답십리'
 '당고개' '당산' '당정' '대곡' '대공원' '대림(구로구청)' '대모산입구' '대방' '대성리' '대야미' '대청' '대치'
 '대화' '대흥(서강대앞)' '덕계' '덕소' '덕정' '도곡' '도농' '도림천' '도봉' '도봉산' '도심' '도원' '도화'
 '독립문' '독바위' '독산' '돌곶이' '동대문' '동대문역사문화공원' '동대입구' '동두천' '동두천중앙' '동묘앞' '동암'
 '동인천' '동작(현충원)' '두정' '둔촌동' '둔촌오륜' '등촌' '디지털미디어시티' '뚝섬' '뚝섬유원지' '마곡'
 '마곡나루' '마두' '마들' '마석' '마장' '마천' '마포' '마포구청' '망우' '망원' '망월사' '망포' '매교'
 '매봉' '매탄권선' '먹골' '면목' '명동' '명일' '명학' '모란' '목동' '몽촌토성(평화의문)' '무악재' '문래'
 '문산' '문정' '미금' '미아(서울사이버대학)' '미아사거리' '반월' '반포' '발산' '방배' '방이' '방학' '방화'
 '배방' '백마' '백석' '백양리' '백운' '버티고개' '범계' '별내' '병점' '보라매' '보라매공원' '보라매병원'
 '보문' '보산' '보정' '복정' '봉명' '봉은사' '봉천' '봉화산(서울의료원)' '부개' '부발' '부천' '부천시청'
 '부천종합운동장' '부평' '부평구청' '북한산보국문' '북한산우이' '불광' '사가정' '사당' '사릉' '사평' '산본'
 '산성' '삼각지' '삼동' '삼산체육관' '삼성' '삼성(무역센터)' '삼성중앙' '삼송' '삼양' '삼양사거리' '삼전'
 '상갈' '상계' '상도' '상동' '상록수' '상봉(시외버스터미널)' '상수' '상왕십리' '상월곡(한국과학기술연구원)'
 '상일동' '상천' '새절(신사)' '샛강' '서강대' '서대문' '서동탄' '서빙고' '서울' '서울대벤처타운'
 '서울대입구(관악구청)' '서울숲' '서울역' '서울지방병무청' '서원' '서정리' '서초' '서현' '석계' '석수' '석촌'
 '석촌고분' '선릉' '선바위' '선유도' '선정릉' '성균관대' '성수' '성신여대입구(돈암)' '성환' '세류' '세마'
 '세종대왕릉' '소래포구' '소사' '소요산' '솔밭공원' '솔샘' '송내' '송도' '송정' '송탄' '송파' '송파나루'
 '수내' '수락산' '수리산' '수색' '수서' '수원' '수원시청' '수유(강북구청)' '수진' '숙대입구(갈월)'
 '숭실대입구(살피재)' '숭의' '시청' '신갈' '신금호' '신길' '신길온천' '신내' '신논현' '신답' '신당' '신대방'
 '신대방삼거리' '신도림' '신둔도예촌' '신림' '신목동' '신반포' '신방화' '신사' '신설동' '신용산' '신원' '신이문'
 '신정(은행정)' '신정네거리' '신중동' '신창(순천향대)' '신촌' '신포' '신풍' '신흥' '쌍문' '쌍용(나사렛대)'
 '아산' '아신' '아차산(어린이대공원후문)' '아현' '안국' '안산' '안암(고대병원앞)' '안양' '암사' '암사역사공원'
 '압구정' '압구정로데오' '애오개' '야당' '야탑' '약수' '양수' '양원' '양재(서초구청)' '양재시민의숲(매헌)'
 '양정' '양주' '양천구청' '양천향교' '양평' '어린이대공원(세종대)' '언주' '여의나루' '여의도' '여주' '역곡'
 '역삼' '역촌' '연수' '연신내' '염창' '영등포' '영등포구청' '영등포시장' '영종' '영통' '오금' '오류동' '오리'
 '오목교(목동운동장앞)' '오빈' '오산' '오산대' '오이도' '옥수' '온수(성공회대입구)' '온양온천'
 '올림픽공원(한국체대)' '왕십리(성동구청)' '외대앞' '용답' '용두(동대문구청)' '용마산' '용문' '용산' '우장산'
 '운길산' '운서' '운정' '원당' '원덕' '원인재' '원흥' '월계' '월곡(동덕여대)' '월곶' '월드컵경기장(성산)'
 '월롱' '을지로3가' '을지로4가' '을지로입구' '응봉' '응암' '의왕' '의정부' '이대' '이매' '이수' '이천'
 '이촌(국립중앙박물관)' '이태원' '인덕원' '인천' '인천공항1터미널' '인천공항2터미널' '인천논현' '인하대' '일산'
 '일원' '잠실(송파구청)' '잠실나루' '잠실새내' '잠원' '장승배기' '장암' '장지' '장한평' '정릉' '정발산'
 '정부과천청사' '정왕' '정자' '제기동' '제물포' '종각' '종로3가' '종로5가' '종합운동장' '주안' '주엽' '죽전'
 '중계' '중곡' '중동' '중랑' '중앙' '중앙보훈병원' '중화' '증미' '증산(명지대앞)' '지제' '지축' '지평'
 '지행' '직산' '진위' '창동' '창신' '천마산' '천안' '천왕' '천호(풍납토성)' '철산' '청계산입구' '청구'
 '청담' '청라국제도시' '청량리(서울시립대입구)' '청명' '청평' '초월' '초지' '총신대입구(이수)' '춘의' '춘천'
 '충무로' '충정로(경기대입구)' '탄현' '태릉입구' '태평' '퇴계원' '파주' '판교' '팔당' '평내호평' '평촌' '평택'
 '풍산' '하계' '학동' '학여울' '한강진' '한남' '한대앞' '한성대입구(삼선교)' '한성백제' '한양대' '한티' '합정'
 '행당' '행신' '혜화' '호구포' '홍대입구' '홍제' '화계' '화곡' '화랑대(서울여대입구)' '화서' '화전' '화정'
 '회기' '회룡' '회현(남대문시장)' '효창공원앞' '흑석(중앙대입구)' '0']
['4.19민주묘지' '가능' '가락시장' '가산디지털단지' '가양' '가오리' '가좌' '가천대' '가평' '간석' '갈매'
 '강남' '강남구청' '강동' '강동구청' '강매' '강변(동서울터미널)' '강일' '강촌' '개롱' '개봉' '개포동' '개화'
 '개화산' '거여' '건대입구' '검암' '경기광주' '경마공원' '경복궁(정부서울청사)' '경찰병원' '계양' '고덕'
 '고려대(종암)' '고색' '고속터미널' '고잔' '곡산' '곤지암' '공덕' '공릉(서울과학기술대)' '공항시장' '공항화물청사'
 '과천' '관악' '관악산(서울대)' '광나루(장신대)' '광명' '광명사거리' '광운대' '광화문(세종문화회관)'
 '광흥창(서강)' '교대(법원.검찰청)' '구로' '구로디지털단지' '구룡' '구리' '구반포' '구산' '구성'
 '구의(광진구청)' '구일' '구파발' '국수' '국회의사당' '군자(능동)' '군포' '굴봉산' '굴포천'
 '굽은다리(강동구민회관앞)' '금곡' '금릉' '금정' '금천구청' '금촌' '금호' '기흥' '길동' '길음' '김유정'
 '김포공항' '까치산' '까치울' '낙성대' '낙성대(강감찬)' '남구로' '남동인더스파크' '남부터미널(예술의전당)' '남성'
 '남영' '남춘천' '남태령' '남한산성입구(성남법원.검찰청)' '내방' '노들' '노량진' '노원' '녹번' '녹사평(용산구청)'
 '녹양' '녹천' '논현' '능곡' '단대오거리' '달월' '답십리' '당고개' '당산' '당정' '대곡' '대공원'
 '대림(구로구청)' '대모산입구' '대방' '대성리' '대야미' '대청' '대치' '대화' '대흥(서강대앞)' '덕계' '덕소'
 '덕정' '도곡' '도농' '도림천' '도봉' '도봉산' '도심' '도원' '도화' '독립문' '독바위' '독산' '돌곶이'
 '동대문' '동대문역사문화공원' '동대문역사문화공원(DDP)' '동대입구' '동두천' '동두천중앙' '동묘앞' '동암' '동인천'
 '동작(현충원)' '두정' '둔촌동' '둔촌오륜' '등촌' '디지털미디어시티' '뚝섬' '뚝섬유원지' '마곡' '마곡나루'
 '마곡나루(서울식물원)' '마두' '마들' '마석' '마장' '마천' '마포' '마포구청' '망우' '망원' '망월사' '망포'
 '매교' '매봉' '매탄권선' '먹골' '면목' '명동' '명일' '명학' '모란' '목동' '몽촌토성(평화의문)' '무악재'
 '문래' '문산' '문정' '미금' '미사' '미아(서울사이버대학)' '미아사거리' '반월' '반포' '발산' '방배' '방이'
 '방학' '방화' '배방' '백마' '백석' '백양리' '백운' '버티고개' '범계' '별내' '병점' '보라매' '보라매공원'
 '보라매병원' '보문' '보산' '보정' '복정' '봉명' '봉은사' '봉천' '봉화산(서울의료원)' '부개' '부발' '부천'
 '부천시청' '부천종합운동장' '부평' '부평구청' '북한산보국문' '북한산우이' '불광' '사가정' '사당' '사릉' '사리'
 '사평' '산본' '산성' '삼각지' '삼동' '삼산체육관' '삼성' '삼성(무역센터)' '삼성중앙' '삼송' '삼양'
 '삼양사거리' '삼전' '상갈' '상계' '상도' '상동' '상록수' '상봉(시외버스터미널)' '상수' '상왕십리'
 '상월곡(한국과학기술연구원)' '상일동' '상천' '새절(신사)' '샛강' '서강대' '서대문' '서동탄' '서빙고' '서울'
 '서울대벤처타운' '서울대입구(관악구청)' '서울숲' '서울역' '서울지방병무청' '서원' '서정리' '서초' '서현' '석계'
 '석수' '석촌' '석촌고분' '선릉' '선바위' '선유도' '선정릉' '성균관대' '성수' '성신여대입구(돈암)' '성환'
 '세류' '세마' '세종대왕릉' '소래포구' '소사' '소요산' '솔밭공원' '솔샘' '송내' '송도' '송정' '송탄' '송파'
 '송파나루' '수내' '수락산' '수리산' '수색' '수서' '수원' '수원시청' '수유(강북구청)' '수진' '숙대입구(갈월)'
 '숭실대입구(살피재)' '숭의' '시청' '신갈' '신금호' '신길' '신길온천' '신내' '신논현' '신답' '신당' '신대방'
 '신대방삼거리' '신도림' '신둔도예촌' '신림' '신목동' '신반포' '신방화' '신사' '신설동' '신용산' '신원' '신이문'
 '신정(은행정)' '신정네거리' '신중동' '신창(순천향대)' '신촌' '신포' '신풍' '신흥' '쌍문' '쌍용(나사렛대)'
 '아산' '아신' '아차산(어린이대공원후문)' '아현' '안국' '안산' '안암(고대병원앞)' '안양' '암사' '암사역사공원'
 '압구정' '압구정로데오' '애오개' '야당' '야목' '야탑' '약수' '양수' '양원' '양재(서초구청)'
 '양재시민의숲(매헌)' '양정' '양주' '양천구청' '양천향교' '양평' '어린이대공원(세종대)' '어천' '언주' '여의나루'
 '여의도' '여주' '역곡' '역삼' '역촌' '연수' '연신내' '염창' '영등포' '영등포구청' '영등포시장' '영종' '영통'
 '오금' '오류동' '오리' '오목교(목동운동장앞)' '오목천' '오빈' '오산' '오산대' '오이도' '옥수'
 '온수(성공회대입구)' '온양온천' '올림픽공원(한국체대)' '왕십리(성동구청)' '외대앞' '용답' '용두(동대문구청)'
 '용마산' '용마산(용마폭포공원)' '용문' '용산' '우장산' '운길산' '운서' '운정' '원당' '원덕' '원인재' '원흥'
 '월계' '월곡(동덕여대)' '월곶' '월드컵경기장(성산)' '월롱' '을지로3가' '을지로4가' '을지로입구' '응봉' '응암'
 '의왕' '의정부' '이대' '이매' '이수' '이천' '이촌(국립중앙박물관)' '이태원' '인덕원' '인천' '인천공항1터미널'
 '인천공항2터미널' '인천논현' '인하대' '일산' '일원' '임진강' '잠실(송파구청)' '잠실나루' '잠실새내' '잠원'
 '장승배기' '장암' '장지' '장한평' '정릉' '정발산' '정부과천청사' '정왕' '정자' '제기동' '제물포' '종각'
 '종로3가' '종로5가' '종합운동장' '주안' '주엽' '죽전' '중계' '중곡' '중동' '중랑' '중앙' '중앙보훈병원'
 '중화' '증미' '증산(명지대앞)' '지제' '지축' '지평' '지행' '직산' '진위' '창동' '창신' '천마산' '천안'
 '천왕' '천호(풍납토성)' '철산' '청계산입구' '청구' '청담' '청라국제도시' '청량리(서울시립대입구)' '청명' '청평'
 '초월' '초지' '총신대입구(이수)' '춘의' '춘천' '충무로' '충정로(경기대입구)' '탄현' '태릉입구' '태평' '퇴계원'
 '파주' '판교' '팔당' '평내호평' '평촌' '평택' '풍산' '하계' '하남풍산' '학동' '학여울' '한강진' '한남'
 '한대앞' '한성대입구(삼선교)' '한성백제' '한양대' '한티' '합정' '행당' '행신' '혜화' '호구포' '홍대입구'
 '홍제' '화계' '화곡' '화랑대(서울여대입구)' '화서' '화전' '화정' '회기' '회룡' '회현(남대문시장)' '효창공원앞'
 '흑석(중앙대입구)' '0']
['4.19민주묘지' '가능' '가락시장' '가산디지털단지' '가양' '가오리' '가좌' '가천대' '가평' '간석' '갈매'
 '강남' '강남구청' '강동' '강동구청' '강매' '강변(동서울터미널)' '강일' '강촌' '개롱' '개봉' '개포동' '개화'
 '개화산' '거여' '건대입구' '검암' '경기광주' '경마공원' '경복궁(정부서울청사)' '경찰병원' '계양' '고덕'
 '고려대(종암)' '고색' '고속터미널' '고잔' '곡산' '곤지암' '공덕' '공릉(서울과학기술대)' '공항시장' '공항화물청사'
 '과천' '관악' '관악산(서울대)' '광나루(장신대)' '광명' '광명사거리' '광운대' '광화문(세종문화회관)'
 '광흥창(서강)' '교대(법원.검찰청)' '구로' '구로디지털단지' '구룡' '구리' '구반포' '구산' '구성'
 '구의(광진구청)' '구일' '구파발' '국수' '국회의사당' '군자(능동)' '군포' '굴봉산' '굴포천'
 '굽은다리(강동구민회관앞)' '금곡' '금릉' '금정' '금천구청' '금촌' '금호' '기흥' '길동' '길음' '김유정'
 '김포공항' '까치산' '까치울' '낙성대' '낙성대(강감찬)' '남구로' '남동인더스파크' '남부터미널(예술의전당)' '남성'
 '남영' '남위례' '남춘천' '남태령' '남한산성입구(성남법원.검찰청)' '내방' '노들' '노량진' '노원' '녹번'
 '녹사평(용산구청)' '녹양' '녹천' '논현' '능곡' '단대오거리' '달월' '답십리' '당고개' '당산' '당정' '대곡'
 '대공원' '대림(구로구청)' '대모산입구' '대방' '대성리' '대야미' '대청' '대치' '대화' '대흥(서강대앞)' '덕계'
 '덕소' '덕정' '도곡' '도농' '도림천' '도봉' '도봉산' '도심' '도원' '도화' '독립문' '독바위' '독산'
 '돌곶이' '동대문' '동대문역사문화공원' '동대문역사문화공원(DDP)' '동대입구' '동두천' '동두천중앙' '동묘앞' '동암'
 '동인천' '동작(현충원)' '두정' '둔촌동' '둔촌오륜' '등촌' '디지털미디어시티' '뚝섬' '뚝섬유원지' '마곡'
 '마곡나루' '마곡나루(서울식물원)' '마두' '마들' '마석' '마장' '마천' '마포' '마포구청' '망우' '망원' '망월사'
 '망포' '매교' '매봉' '매탄권선' '먹골' '면목' '명동' '명일' '명학' '모란' '목동' '몽촌토성(평화의문)'
 '무악재' '문래' '문산' '문정' '미금' '미사' '미아(서울사이버대학)' '미아사거리' '반월' '반포' '발산' '방배'
 '방이' '방학' '방화' '배방' '백마' '백석' '백양리' '백운' '버티고개' '범계' '별내' '병점' '보라매'
 '보라매공원' '보라매병원' '보문' '보산' '보정' '복정' '봉명' '봉은사' '봉천' '봉화산(서울의료원)' '부개'
 '부발' '부천' '부천시청' '부천종합운동장' '부평' '부평구청' '북한산보국문' '북한산우이' '불광' '사가정' '사당'
 '사릉' '사리' '사평' '산본' '산성' '삼각지' '삼동' '삼산체육관' '삼성' '삼성(무역센터)' '삼성중앙' '삼송'
 '삼양' '삼양사거리' '삼전' '상갈' '상계' '상도' '상동' '상록수' '상봉(시외버스터미널)' '상수' '상왕십리'
 '상월곡(한국과학기술연구원)' '상일동' '상천' '새절(신사)' '샛강' '서강대' '서대문' '서동탄' '서빙고' '서울'
 '서울대벤처타운' '서울대입구(관악구청)' '서울숲' '서울역' '서울지방병무청' '서원' '서정리' '서초' '서현' '석계'
 '석수' '석촌' '석촌고분' '선릉' '선바위' '선유도' '선정릉' '성균관대' '성수' '성신여대입구(돈암)' '성환'
 '세류' '세마' '세종대왕릉' '소래포구' '소사' '소요산' '솔밭공원' '솔샘' '송내' '송도' '송정' '송탄' '송파'
 '송파나루' '수내' '수락산' '수리산' '수색' '수서' '수원' '수원시청' '수유(강북구청)' '수진' '숙대입구(갈월)'
 '숭실대입구(살피재)' '숭의' '시청' '신갈' '신금호' '신길' '신길온천' '신내' '신논현' '신답' '신당' '신대방'
 '신대방삼거리' '신도림' '신둔도예촌' '신림' '신목동' '신반포' '신방화' '신사' '신설동' '신용산' '신원' '신이문'
 '신정(은행정)' '신정네거리' '신중동' '신창(순천향대)' '신촌' '신포' '신풍' '신흥' '쌍문' '쌍용(나사렛대)'
 '아산' '아신' '아차산(어린이대공원후문)' '아현' '안국' '안산' '안암(고대병원앞)' '안양' '암사' '암사역사공원'
 '압구정' '압구정로데오' '애오개' '야당' '야목' '야탑' '약수' '양수' '양원' '양재(서초구청)'
 '양재시민의숲(매헌)' '양정' '양주' '양천구청' '양천향교' '양평' '어린이대공원(세종대)' '어천' '언주' '여의나루'
 '여의도' '여주' '역곡' '역삼' '역촌' '연수' '연신내' '염창' '영등포' '영등포구청' '영등포시장' '영종' '영통'
 '오금' '오류동' '오리' '오목교(목동운동장앞)' '오목천' '오빈' '오산' '오산대' '오이도' '옥수'
 '온수(성공회대입구)' '온양온천' '올림픽공원(한국체대)' '왕십리(성동구청)' '외대앞' '용답' '용두(동대문구청)'
 '용마산' '용마산(용마폭포공원)' '용문' '용산' '우장산' '운길산' '운서' '운정' '원당' '원덕' '원인재' '원흥'
 '월계' '월곡(동덕여대)' '월곶' '월드컵경기장(성산)' '월롱' '을지로3가' '을지로4가' '을지로입구' '응봉' '응암'
 '의왕' '의정부' '이대' '이매' '이수' '이천' '이촌(국립중앙박물관)' '이태원' '인덕원' '인천' '인천공항1터미널'
 '인천공항2터미널' '인천논현' '인하대' '일산' '일원' '임진강' '잠실(송파구청)' '잠실나루' '잠실새내' '잠원'
 '장승배기' '장암' '장지' '장한평' '정릉' '정발산' '정부과천청사' '정왕' '정자' '제기동' '제물포' '종각'
 '종로3가' '종로5가' '종합운동장' '주안' '주엽' '죽전' '중계' '중곡' '중동' '중랑' '중앙' '중앙보훈병원'
 '중화' '증미' '증산(명지대앞)' '지제' '지축' '지평' '지행' '직산' '진위' '창동' '창신' '천마산' '천안'
 '천왕' '천호(풍납토성)' '철산' '청계산입구' '청구' '청담' '청라국제도시' '청량리(서울시립대입구)' '청명' '청평'
 '초월' '초지' '총신대입구(이수)' '춘의' '춘천' '충무로' '충정로(경기대입구)' '탄현' '탕정' '태릉입구' '태평'
 '퇴계원' '파주' '판교' '팔당' '평내호평' '평촌' '평택' '평택지제' '풍산' '하계' '하남검단산'
 '하남시청(덕풍?신장)' '하남풍산' '학동' '학여울' '한강진' '한남' '한대앞' '한성대입구(삼선교)' '한성백제'
 '한양대' '한티' '합정' '행당' '행신' '혜화' '호구포' '홍대입구' '홍제' '화계' '화곡' '화랑대(서울여대입구)'
 '화서' '화전' '화정' '회기' '회룡' '회현(남대문시장)' '효창공원앞' '흑석(중앙대입구)' '0']

In [106]:
# 행정동 갯수 확인 
print(sw_19['행정동'].nunique())
print(sw_20['행정동'].nunique())
print(sw_21['행정동'].nunique())

426
426
426

In [107]:
print(sw_19, sw_20, sw_21)

        호선명      지하철역  시군구   행정동  총승하차인원    년분기
0     우이신설선  4.19민주묘지  강북구   우이동  184362  20194
1     우이신설선  4.19민주묘지  강북구   우이동  211195  20194
2     우이신설선  4.19민주묘지  강북구   우이동  221738  20194
3     우이신설선  4.19민주묘지  강북구   우이동  202508  20193
4     우이신설선  4.19민주묘지  강북구   우이동  159408  20193
...     ...       ...  ...   ...     ...    ...
7624      0         0  중랑구  면목5동       0     00
7625      0         0  중랑구  면목7동       0     00
7626      0         0  중랑구   묵1동       0     00
7627      0         0  중랑구  신내2동       0     00
7628      0         0  중랑구  중화1동       0     00

[7629 rows x 6 columns]         호선명      지하철역  시군구   행정동  총승하차인원    년분기
0     우이신설선  4.19민주묘지  강북구   우이동  121940  20204
1     우이신설선  4.19민주묘지  강북구   우이동  148118  20204
2     우이신설선  4.19민주묘지  강북구   우이동  150294  20204
3     우이신설선  4.19민주묘지  강북구   우이동  126887  20203
4     우이신설선  4.19민주묘지  강북구   우이동  125015  20203
...     ...       ...  ...   ...     ...    ...
7445      0         0  중랑구  면목5동       0     00
7446      0         0  중랑구  면목7동       0     00
7447      0         0  중랑구   묵1동       0     00
7448      0         0  중랑구  신내2동       0     00
7449      0         0  중랑구  중화1동       0     00

[7450 rows x 6 columns]         호선명      지하철역  시군구   행정동  총승하차인원    년분기
0     우이신설선  4.19민주묘지  강북구   우이동  149571  20214
1     우이신설선  4.19민주묘지  강북구   우이동  160435  20214
2     우이신설선  4.19민주묘지  강북구   우이동  155675  20214
3     우이신설선  4.19민주묘지  강북구   우이동  142949  20213
4     우이신설선  4.19민주묘지  강북구   우이동  136432  20213
...     ...       ...  ...   ...     ...    ...
7550      0         0  중랑구  면목5동       0     00
7551      0         0  중랑구  면목7동       0     00
7552      0         0  중랑구   묵1동       0     00
7553      0         0  중랑구  신내2동       0     00
7554      0         0  중랑구  중화1동       0     00

[7555 rows x 6 columns]

지하철역이 없는 데이터 필터링해서 갯수 확인

In [108]:
# '지하철역'이 0인 데이터만 필터링 
sw_19_zero = sw_19[sw_19['지하철역'] == 0]
sw_20_zero = sw_20[sw_20['지하철역'] == 0]
sw_21_zero = sw_21[sw_21['지하철역'] == 0]

# 결과확인 
print("19년도 데이터 - '지하철역이' 0인 행 개수:", len(sw_19_zero))
print("20년도 데이터 - '지하철역이' 0인 행 개수:", len(sw_20_zero))
print("21년도 데이터 - '지하철역이' 0인 행 개수:", len(sw_21_zero))

19년도 데이터 - '지하철역이' 0인 행 개수: 0
20년도 데이터 - '지하철역이' 0인 행 개수: 0
21년도 데이터 - '지하철역이' 0인 행 개수: 0

2019년 데이터 '지하철역'으로 데이터 있는것과 없는 것으로 구분

In [ ]:
# '지하철역' 값이 0인 데이터
sw_19_station_zero = sw_19[sw_19['지하철역'] == 0]

# '지하철역' 값이 0이 아닌 데이터
sw_19_with_station = sw_19[sw_19['지하철역'] != 0]

# 결과확인 (출력할 때 데이터가 너무 많으면 `head()`로 일부만 출력)
print("19년도 데이터 - '지하철역'이 0인 데이터 (상위 5개):")
print(sw_19_station_zero.head())  # '지하철역'이 0인 데이터 상위 5개 행

print("\n19년도 데이터 - '지하철역'이 0이 아닌 데이터 (상위 5개):")
print(sw_19_with_station.head())  # '지하철역'이 0이 아닌 데이터 상위 5개 행

# 데이터 갯수 출력
print("\n19년도 데이터 - '지하철역'이 있는 데이터 갯수:", len(sw_19_with_station))  # '지하철역'이 0이 아닌 데이터 갯수
print("19년도 데이터 - '지하철역'이 없는 데이터 갯수:", len(sw_19_station_zero))  # '지하철역'이 0인 데이터 갯수

19년도 데이터 - '지하철역'이 0인 데이터 (상위 5개):
Empty DataFrame
Columns: [호선명, 지하철역, 시군구, 행정동, 총승하차인원, 년분기]
Index: []

19년도 데이터 - '지하철역'이 0이 아닌 데이터 (상위 5개):
     호선명      지하철역  시군구  행정동  총승하차인원    년분기
0  우이신설선  4.19민주묘지  강북구  우이동  184362  20194
1  우이신설선  4.19민주묘지  강북구  우이동  211195  20194
2  우이신설선  4.19민주묘지  강북구  우이동  221738  20194
3  우이신설선  4.19민주묘지  강북구  우이동  202508  20193
4  우이신설선  4.19민주묘지  강북구  우이동  159408  20193

19년도 데이터 - '지하철역'이 있는 데이터 갯수: 7629
19년도 데이터 - '지하철역'이 없는 데이터 갯수: 0

(2019년) 호선명, 지하철역, 시군구, 행정동, 년분기에 총승하차인원으로 groupby 해서 같은 데이터끼리 그룹화 후 승하차인원수 합산

In [135]:
# '총승하차인원'을 기준으로 groupby 후 합산
group19_sum = sw_19_with_station.groupby(
    ['호선명', '지하철역', '시군구', '행정동', '년분기']
)['총승하차인원'].sum().reset_index()

# '총승하차인원'이 0인 데이터만 제외
group19_non_zero = sw_19_with_station[sw_19_with_station['총승하차인원'] != 0]

# 병합 예시 (groupby_sum 결과 병합)
merged = pd.merge(
    sw_19_with_station, 
    group19_sum[['호선명', '지하철역', '시군구', '행정동', '년분기', '총승하차인원']], 
    on=['호선명', '지하철역', '시군구', '행정동', '년분기'], 
    how='left', 
    suffixes=('', '_합산')
)

# 결과 확인
print(merged.head())  # 병합된 결과 출력

     호선명      지하철역  시군구  행정동  총승하차인원    년분기      총승하차인원_평균  총승하차인원_합산
0  우이신설선  4.19민주묘지  강북구  우이동  184362  20194  205765.000000     617295
1  우이신설선  4.19민주묘지  강북구  우이동  211195  20194  205765.000000     617295
2  우이신설선  4.19민주묘지  강북구  우이동  221738  20194  205765.000000     617295
3  우이신설선  4.19민주묘지  강북구  우이동  202508  20193  175996.333333     527989
4  우이신설선  4.19민주묘지  강북구  우이동  159408  20193  175996.333333     527989

 행정동 ,지하철, 년분기별로 승하차인원 합산 groupby

In [156]:
# '행정동', '지하철역', '년분기'별로 '총승하차인원' 합산
grouped_data19 = merged.groupby(
    ['행정동', '지하철역', '년분기']
)['총승하차인원'].sum().reset_index()

# 결과 확인
print(grouped_data19)

       행정동       지하철역    년분기   총승하차인원
0        0         가능  20191  1210310
1        0         가능  20192  1346897
2        0         가능  20193  2152637
3        0         가능  20194  1296336
4        0         가좌  20191   891758
...    ...        ...    ...      ...
2392  휘경2동          0     00        0
2393   흑석동  흑석(중앙대입구)  20191  1729636
2394   흑석동  흑석(중앙대입구)  20192  2014339
2395   흑석동  흑석(중앙대입구)  20193  1722586
2396   흑석동  흑석(중앙대입구)  20194  1996528

[2397 rows x 4 columns]

합산 뒤, 총승하차인원 평균값 계산

In [160]:
# '총승하차인원'이 0이 아닌 데이터로 필터링 (NaN 처리 후 평균 계산)
group19_non_zero = grouped_data19[grouped_data19['총승하차인원'] != 0]

# '총승하차인원' 의 평균 계산
group19_mean = grouped_data19.groupby(
    ['지하철역', '행정동', '년분기']
).agg(
    총승하차인원_평균=('총승하차인원', 'mean')  # 총승하차인원 평균 계산
).reset_index()

# 결과 확인
print(group19_mean)

           지하철역   행정동    년분기  총승하차인원_평균
0             0  가리봉동     00        0.0
1             0  가양2동     00        0.0
2             0  가양3동     00        0.0
3             0   가회동     00        0.0
4             0  갈현1동     00        0.0
...         ...   ...    ...        ...
2392      효창공원앞   용문동  20194  1342737.0
2393  흑석(중앙대입구)   흑석동  20191  1729636.0
2394  흑석(중앙대입구)   흑석동  20192  2014339.0
2395  흑석(중앙대입구)   흑석동  20193  1722586.0
2396  흑석(중앙대입구)   흑석동  20194  1996528.0

[2397 rows x 4 columns]

결과 확인 후, 총승하차인원 평균값이 float이라 정수형 변환(보기편해서)

In [ ]:
# '총승하차인원_평균'을 정수형으로 변환
group19_mean['총승하차인원_평균'] = group19_mean['총승하차인원_평균'].astype(int)

# 결과 확인
print(group19_mean)
# group19_mean.to_csv('group19_mean.csv', index=False)

           지하철역   행정동    년분기  총승하차인원_평균
0             0  가리봉동     00          0
1             0  가양2동     00          0
2             0  가양3동     00          0
3             0   가회동     00          0
4             0  갈현1동     00          0
...         ...   ...    ...        ...
2392      효창공원앞   용문동  20194    1342737
2393  흑석(중앙대입구)   흑석동  20191    1729636
2394  흑석(중앙대입구)   흑석동  20192    2014339
2395  흑석(중앙대입구)   흑석동  20193    1722586
2396  흑석(중앙대입구)   흑석동  20194    1996528

[2397 rows x 4 columns]

행정동이 있는 데이터와 없는 데이터로 분할

In [ ]:
# '행정동' 값이 있는 데이터 (NaN이 아닌 데이터)
with_admin_dong = group19_mean[group19_mean['행정동'].notna()]

# '행정동' 값이 없는 데이터 (NaN인 데이터)
without_admin_dong = group19_mean[group19_mean['행정동'].isna()]

# 결과 확인
print("행정동이 있는 데이터:")
print(with_admin_dong)  # 상위 5개 확인

print("\n행정동이 없는 데이터:")
print(without_admin_dong)  # 상위 5개 확인

행정동이 있는 데이터:
           지하철역   행정동    년분기  총승하차인원_평균
0             0  가리봉동     00          0
1             0  가양2동     00          0
2             0  가양3동     00          0
3             0   가회동     00          0
4             0  갈현1동     00          0
...         ...   ...    ...        ...
2392      효창공원앞   용문동  20194    1342737
2393  흑석(중앙대입구)   흑석동  20191    1729636
2394  흑석(중앙대입구)   흑석동  20192    2014339
2395  흑석(중앙대입구)   흑석동  20193    1722586
2396  흑석(중앙대입구)   흑석동  20194    1996528

[2397 rows x 4 columns]

행정동이 없는 데이터:
Empty DataFrame
Columns: [지하철역, 행정동, 년분기, 총승하차인원_평균]
Index: []

행정동 열의 결측값 확인

In [164]:
# '행정동' 열의 결측값 개수 확인
missing_admin_dong = group19_mean['행정동'].isna().sum()

# 결과 출력
print(f"'행정동' 값이 없는 데이터 개수: {missing_admin_dong}")

'행정동' 값이 없는 데이터 개수: 0

In [175]:
group19_mean

           지하철역   행정동    년분기  총승하차인원_평균
0             0  가리봉동     00          0
1             0  가양2동     00          0
2             0  가양3동     00          0
3             0   가회동     00          0
4             0  갈현1동     00          0
...         ...   ...    ...        ...
2392      효창공원앞   용문동  20194    1342737
2393  흑석(중앙대입구)   흑석동  20191    1729636
2394  흑석(중앙대입구)   흑석동  20192    2014339
2395  흑석(중앙대입구)   흑석동  20193    1722586
2396  흑석(중앙대입구)   흑석동  20194    1996528

[2397 rows x 4 columns]

데이터 없는 데이터프레임 컬럼 맞추기

In [ ]:
# print(sw_19_station_zero.columns)
# print(sw_19_with_station.columns)

Index(['호선명', '지하철역', '유임승차인원', '무임승차인원', '유임하차인원', '무임하차인원', '시군구', '행정동',
       '총승하차인원', '년분기'],
      dtype='object')
Index(['호선명', '지하철역', '유임승차인원', '무임승차인원', '유임하차인원', '무임하차인원', '시군구', '행정동',
       '총승하차인원', '년분기', '총승하차인원_평균'],
      dtype='object')

2020년 데이터 '지하철역'으로 데이터 있는것과 없는 것으로 구분

In [167]:
sw_20

        호선명      지하철역  시군구   행정동  총승하차인원    년분기
0     우이신설선  4.19민주묘지  강북구   우이동  121940  20204
1     우이신설선  4.19민주묘지  강북구   우이동  148118  20204
2     우이신설선  4.19민주묘지  강북구   우이동  150294  20204
3     우이신설선  4.19민주묘지  강북구   우이동  126887  20203
4     우이신설선  4.19민주묘지  강북구   우이동  125015  20203
...     ...       ...  ...   ...     ...    ...
7445      0         0  중랑구  면목5동       0     00
7446      0         0  중랑구  면목7동       0     00
7447      0         0  중랑구   묵1동       0     00
7448      0         0  중랑구  신내2동       0     00
7449      0         0  중랑구  중화1동       0     00

[7450 rows x 6 columns]

In [168]:
# '지하철역' 값이 0인 데이터
sw_20_station_zero = sw_20[sw_20['지하철역'] == 0]

# '지하철역' 값이 0이 아닌 데이터
sw_20_with_station = sw_20[sw_20['지하철역'] != 0]

# 결과확인 (출력할 때 데이터가 너무 많으면 `head()`로 일부만 출력)
print("20년도 데이터 - '지하철역'이 0인 데이터 (상위 5개):")
print(sw_20_station_zero.head())  # '지하철역'이 0인 데이터 상위 5개 행

print("\n20년도 데이터 - '지하철역'이 0이 아닌 데이터 (상위 5개):")
print(sw_20_with_station.head())  # '지하철역'이 0이 아닌 데이터 상위 5개 행

# 데이터 갯수 출력
print("\n20년도 데이터 - '지하철역'이 있는 데이터 갯수:", len(sw_20_with_station))  # '지하철역'이 0이 아닌 데이터 갯수
print("20년도 데이터 - '지하철역'이 없는 데이터 갯수:", len(sw_20_station_zero))  # '지하철역'이 0인 데이터 갯수

20년도 데이터 - '지하철역'이 0인 데이터 (상위 5개):
Empty DataFrame
Columns: [호선명, 지하철역, 시군구, 행정동, 총승하차인원, 년분기]
Index: []

20년도 데이터 - '지하철역'이 0이 아닌 데이터 (상위 5개):
     호선명      지하철역  시군구  행정동  총승하차인원    년분기
0  우이신설선  4.19민주묘지  강북구  우이동  121940  20204
1  우이신설선  4.19민주묘지  강북구  우이동  148118  20204
2  우이신설선  4.19민주묘지  강북구  우이동  150294  20204
3  우이신설선  4.19민주묘지  강북구  우이동  126887  20203
4  우이신설선  4.19민주묘지  강북구  우이동  125015  20203

20년도 데이터 - '지하철역'이 있는 데이터 갯수: 7450
20년도 데이터 - '지하철역'이 없는 데이터 갯수: 0

(2020년) 호선명, 지하철역, 시군구, 행정동, 년분기에 총승하차인원으로 groupby 해서 같은 데이터끼리 그룹화 후 승하차인원수 합산

In [169]:
# '총승하차인원'을 기준으로 groupby 후 합산
group20_sum = sw_20_with_station.groupby(
    ['호선명', '지하철역', '시군구', '행정동', '년분기']
)['총승하차인원'].sum().reset_index()

# '총승하차인원'이 0인 데이터만 제외
group20_non_zero = sw_20_with_station[sw_20_with_station['총승하차인원'] != 0]

# 병합 예시 (groupby_sum 결과 병합)
merged = pd.merge(
    sw_20_with_station, 
    group20_sum[['호선명', '지하철역', '시군구', '행정동', '년분기', '총승하차인원']], 
    on=['호선명', '지하철역', '시군구', '행정동', '년분기'], 
    how='left', 
    suffixes=('', '_합산')
)

# 결과 확인
print(merged.head())  # 병합된 결과 출력

     호선명      지하철역  시군구  행정동  총승하차인원    년분기  총승하차인원_합산
0  우이신설선  4.19민주묘지  강북구  우이동  121940  20204     420352
1  우이신설선  4.19민주묘지  강북구  우이동  148118  20204     420352
2  우이신설선  4.19민주묘지  강북구  우이동  150294  20204     420352
3  우이신설선  4.19민주묘지  강북구  우이동  126887  20203     403616
4  우이신설선  4.19민주묘지  강북구  우이동  125015  20203     403616

 행정동 ,지하철, 년분기별로 승하차인원 합산 groupby

In [170]:
# '행정동', '지하철역', '년분기'별로 '총승하차인원' 합산
grouped_data20 = merged.groupby(
    ['행정동', '지하철역', '년분기']
)['총승하차인원'].sum().reset_index()

# 결과 확인
print(grouped_data20)

       행정동       지하철역    년분기   총승하차인원
0        0         가능  20201   983141
1        0         가능  20202   967255
2        0         가능  20203   959089
3        0         가능  20204   954525
4        0         가좌  20201   742518
...    ...        ...    ...      ...
2411  휘경2동          0     00        0
2412   흑석동  흑석(중앙대입구)  20201  1241657
2413   흑석동  흑석(중앙대입구)  20202  1133733
2414   흑석동  흑석(중앙대입구)  20203  1165204
2415   흑석동  흑석(중앙대입구)  20204  1146435

[2416 rows x 4 columns]

합산 뒤, 총승하차인원 평균값 계산

In [171]:
# '총승하차인원'이 0이 아닌 데이터로 필터링 (NaN 처리 후 평균 계산)
group20_non_zero = grouped_data20[grouped_data20['총승하차인원'] != 0]

# '총승하차인원' 의 평균 계산
group20_mean = grouped_data20.groupby(
    ['지하철역', '행정동', '년분기']
).agg(
    총승하차인원_평균=('총승하차인원', 'mean')  # 총승하차인원 평균 계산
).reset_index()

# 결과 확인
print(group20_mean)

           지하철역   행정동    년분기  총승하차인원_평균
0             0  가리봉동     00        0.0
1             0  가양2동     00        0.0
2             0  가양3동     00        0.0
3             0   가회동     00        0.0
4             0  갈현1동     00        0.0
...         ...   ...    ...        ...
2411      효창공원앞   용문동  20204   968103.0
2412  흑석(중앙대입구)   흑석동  20201  1241657.0
2413  흑석(중앙대입구)   흑석동  20202  1133733.0
2414  흑석(중앙대입구)   흑석동  20203  1165204.0
2415  흑석(중앙대입구)   흑석동  20204  1146435.0

[2416 rows x 4 columns]

결과 확인 후, 총승하차인원 평균값이 float이라 정수형 변환

In [172]:
# '총승하차인원_평균'을 정수형으로 변환
group20_mean['총승하차인원_평균'] = group20_mean['총승하차인원_평균'].astype(int)

# 결과 확인
print(group20_mean)
# group20_mean.to_csv('group20_mean.csv', index=False)

           지하철역   행정동    년분기  총승하차인원_평균
0             0  가리봉동     00          0
1             0  가양2동     00          0
2             0  가양3동     00          0
3             0   가회동     00          0
4             0  갈현1동     00          0
...         ...   ...    ...        ...
2411      효창공원앞   용문동  20204     968103
2412  흑석(중앙대입구)   흑석동  20201    1241657
2413  흑석(중앙대입구)   흑석동  20202    1133733
2414  흑석(중앙대입구)   흑석동  20203    1165204
2415  흑석(중앙대입구)   흑석동  20204    1146435

[2416 rows x 4 columns]

행정동이 있는 데이터와 없는 데이터로 분할

In [173]:
# '행정동' 값이 있는 데이터 (NaN이 아닌 데이터)
with_admin_dong = group20_mean[group20_mean['행정동'].notna()]

# '행정동' 값이 없는 데이터 (NaN인 데이터)
without_admin_dong = group20_mean[group20_mean['행정동'].isna()]

# 결과 확인
print("행정동이 있는 데이터:")
print(with_admin_dong)  # 상위 5개 확인

print("\n행정동이 없는 데이터:")
print(without_admin_dong)  # 상위 5개 확인

행정동이 있는 데이터:
           지하철역   행정동    년분기  총승하차인원_평균
0             0  가리봉동     00          0
1             0  가양2동     00          0
2             0  가양3동     00          0
3             0   가회동     00          0
4             0  갈현1동     00          0
...         ...   ...    ...        ...
2411      효창공원앞   용문동  20204     968103
2412  흑석(중앙대입구)   흑석동  20201    1241657
2413  흑석(중앙대입구)   흑석동  20202    1133733
2414  흑석(중앙대입구)   흑석동  20203    1165204
2415  흑석(중앙대입구)   흑석동  20204    1146435

[2416 rows x 4 columns]

행정동이 없는 데이터:
Empty DataFrame
Columns: [지하철역, 행정동, 년분기, 총승하차인원_평균]
Index: []

행정동 열의 결측값 확인

In [174]:
# '행정동' 열의 결측값 개수 확인
missing_admin_dong = group20_mean['행정동'].isna().sum()

# 결과 출력
print(f"'행정동' 값이 없는 데이터 개수: {missing_admin_dong}")

'행정동' 값이 없는 데이터 개수: 0

In [177]:
group20_mean

           지하철역   행정동    년분기  총승하차인원_평균
0             0  가리봉동     00          0
1             0  가양2동     00          0
2             0  가양3동     00          0
3             0   가회동     00          0
4             0  갈현1동     00          0
...         ...   ...    ...        ...
2411      효창공원앞   용문동  20204     968103
2412  흑석(중앙대입구)   흑석동  20201    1241657
2413  흑석(중앙대입구)   흑석동  20202    1133733
2414  흑석(중앙대입구)   흑석동  20203    1165204
2415  흑석(중앙대입구)   흑석동  20204    1146435

[2416 rows x 4 columns]

2021년 데이터 '지하철역'으로 데이터 있는것과 없는 것으로 구분

In [178]:
sw_21

        호선명      지하철역  시군구   행정동  총승하차인원    년분기
0     우이신설선  4.19민주묘지  강북구   우이동  149571  20214
1     우이신설선  4.19민주묘지  강북구   우이동  160435  20214
2     우이신설선  4.19민주묘지  강북구   우이동  155675  20214
3     우이신설선  4.19민주묘지  강북구   우이동  142949  20213
4     우이신설선  4.19민주묘지  강북구   우이동  136432  20213
...     ...       ...  ...   ...     ...    ...
7550      0         0  중랑구  면목5동       0     00
7551      0         0  중랑구  면목7동       0     00
7552      0         0  중랑구   묵1동       0     00
7553      0         0  중랑구  신내2동       0     00
7554      0         0  중랑구  중화1동       0     00

[7555 rows x 6 columns]

In [179]:
# '지하철역' 값이 0인 데이터
sw_21_station_zero = sw_21[sw_21['지하철역'] == 0]

# '지하철역' 값이 0이 아닌 데이터
sw_21_with_station = sw_21[sw_21['지하철역'] != 0]

# 결과확인 (출력할 때 데이터가 너무 많으면 `head()`로 일부만 출력)
print("21년도 데이터 - '지하철역'이 0인 데이터 (상위 5개):")
print(sw_21_station_zero.head())  # '지하철역'이 0인 데이터 상위 5개 행

print("\n21년도 데이터 - '지하철역'이 0이 아닌 데이터 (상위 5개):")
print(sw_21_with_station.head())  # '지하철역'이 0이 아닌 데이터 상위 5개 행

# 데이터 갯수 출력
print("\n21년도 데이터 - '지하철역'이 있는 데이터 갯수:", len(sw_21_with_station))  # '지하철역'이 0이 아닌 데이터 갯수
print("21년도 데이터 - '지하철역'이 없는 데이터 갯수:", len(sw_21_station_zero))  # '지하철역'이 0인 데이터 갯수

21년도 데이터 - '지하철역'이 0인 데이터 (상위 5개):
Empty DataFrame
Columns: [호선명, 지하철역, 시군구, 행정동, 총승하차인원, 년분기]
Index: []

21년도 데이터 - '지하철역'이 0이 아닌 데이터 (상위 5개):
     호선명      지하철역  시군구  행정동  총승하차인원    년분기
0  우이신설선  4.19민주묘지  강북구  우이동  149571  20214
1  우이신설선  4.19민주묘지  강북구  우이동  160435  20214
2  우이신설선  4.19민주묘지  강북구  우이동  155675  20214
3  우이신설선  4.19민주묘지  강북구  우이동  142949  20213
4  우이신설선  4.19민주묘지  강북구  우이동  136432  20213

21년도 데이터 - '지하철역'이 있는 데이터 갯수: 7555
21년도 데이터 - '지하철역'이 없는 데이터 갯수: 0