In [2]:
import numpy as np 
import pandas as pd

In [3]:
sw_19 = pd.read_csv('file/station_merge19.csv')
sw_20 = pd.read_csv('file/station_merge20.csv')
sw_21 = pd.read_csv('file/station_merge21.csv')

In [4]:
sw_19
sw_20
sw_21

,사용월,호선명_x,지하철역,작업일자,호선명_y,구,동,구_동,총승하차인원,월,분기,년분기
0,2021,우이신설선,4.19민주묘지,20220103,우이신설선,강북구,우이동,강북구_우이동,149571,12,4분기,20214
1,2021,우이신설선,4.19민주묘지,20211203,우이신설선,강북구,우이동,강북구_우이동,160435,11,4분기,20214
2,2021,우이신설선,4.19민주묘지,20211103,우이신설선,강북구,우이동,강북구_우이동,155675,10,4분기,20214
3,2021,우이신설선,4.19민주묘지,20211003,우이신설선,강북구,우이동,강북구_우이동,142949,9,3분기,20213
4,2021,우이신설선,4.19민주묘지,20210903,우이신설선,강북구,우이동,강북구_우이동,136432,8,3분기,20213
...,...,...,...,...,...,...,...,...,...,...,...,...
10066,0,0,0,0,0,중랑구,면목5동,중랑구_면목5동,0,0,0분기,0
10067,0,0,0,0,0,중랑구,면목7동,중랑구_면목7동,0,0,0분기,0
10068,0,0,0,0,0,중랑구,묵1동,중랑구_묵1동,0,0,0분기,0
10069,0,0,0,0,0,중랑구,신내2동,중랑구_신내2동,0,0,0분기,0
10070,0,0,0,0,0,중랑구,중화1동,중랑구_중화1동,0,0,0분기,0

In [55]:
sw_19 = sw_19.drop(columns=['월','분기'])
sw_20 = sw_20.drop(columns=['월','분기'])
sw_21 = sw_21.drop(columns=['월','분기'])

sw_19 = sw_19.drop(columns=['사용월','구_동','작업일자'])
sw_20 = sw_20.drop(columns=['사용월','구_동','작업일자'])
sw_21 = sw_21.drop(columns=['사용월','구_동','작업일자'])

sw_19 = sw_19.drop(columns=['호선명_y','호선명_x'])
sw_20 = sw_20.drop(columns=['호선명_y','호선명_x'])
sw_21 = sw_21.drop(columns=['호선명_y','호선명_x'])

sw_19 = sw_19.drop(columns=['연도'])

sw_19
sw_20 
sw_21

           지하철역    구     동  총승하차인원    년분기
0      4.19민주묘지  강북구   우이동  149571  20214
1      4.19민주묘지  강북구   우이동  160435  20214
2      4.19민주묘지  강북구   우이동  155675  20214
3      4.19민주묘지  강북구   우이동  142949  20213
4      4.19민주묘지  강북구   우이동  136432  20213
...         ...  ...   ...     ...    ...
10066         0  중랑구  면목5동       0      0
10067         0  중랑구  면목7동       0      0
10068         0  중랑구   묵1동       0      0
10069         0  중랑구  신내2동       0      0
10070         0  중랑구  중화1동       0      0

[10071 rows x 5 columns]

In [61]:
# '지하철역' 컬럼을 문자열로 변환
sw_19.loc[:, '지하철역'] = sw_19['지하철역'].astype(str)
sw_20.loc[:, '지하철역'] = sw_20['지하철역'].astype(str)
sw_21.loc[:, '지하철역'] = sw_21['지하철역'].astype(str)

# 결과 확인
print(sw_19.head())
print(sw_20.head())
print(sw_21.head())

       지하철역    구    동  총승하차인원    년분기
0  4.19민주묘지  강북구  우이동  184362  20194
1  4.19민주묘지  강북구  우이동  211195  20194
2  4.19민주묘지  강북구  우이동  221738  20194
3  4.19민주묘지  강북구  우이동  202508  20193
4  4.19민주묘지  강북구  우이동  159408  20193
       지하철역    구    동  총승하차인원    년분기
0  4.19민주묘지  강북구  우이동  121940  20204
1  4.19민주묘지  강북구  우이동  148118  20204
2  4.19민주묘지  강북구  우이동  150294  20204
3  4.19민주묘지  강북구  우이동  126887  20203
4  4.19민주묘지  강북구  우이동  125015  20203
       지하철역    구    동  총승하차인원    년분기
0  4.19민주묘지  강북구  우이동  149571  20214
1  4.19민주묘지  강북구  우이동  160435  20214
2  4.19민주묘지  강북구  우이동  155675  20214
3  4.19민주묘지  강북구  우이동  142949  20213
4  4.19민주묘지  강북구  우이동  136432  20213

In [62]:
# '지하철역' 컬럼에서 고유값의 개수 확인
print(sw_19['지하철역'].nunique())
print(sw_20['지하철역'].nunique())
print(sw_21['지하철역'].nunique())

521
533
538

In [57]:
# 수정된 DataFrame을 CSV로 저장
sw_19.to_csv('sw19.csv', index=False)
sw_20.to_csv('sw20.csv', index=False)
sw_21.to_csv('sw21.csv', index=False)