In [8]:
import numpy as np 
import pandas as pd

In [9]:
sw19 = pd.read_csv('sw19.csv')
sw20 = pd.read_csv('sw20.csv')
sw21 = pd.read_csv('sw21.csv')
dong = pd.read_csv('file/merged_final_all.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'file/merged_final_all.csv'

In [ ]:
sw19
sw20
sw21

           지하철역    구    동  총승하차인원    년분기
0      4.19민주묘지  강북구  우이동  149571  20214
1      4.19민주묘지  강북구  우이동  160435  20214
2      4.19민주묘지  강북구  우이동  155675  20214
3      4.19민주묘지  강북구  우이동  142949  20213
4      4.19민주묘지  강북구  우이동  136432  20213
...         ...  ...  ...     ...    ...
9870  흑석(중앙대입구)  동작구  흑석동  411629  20212
9871  흑석(중앙대입구)  동작구  흑석동  413572  20212
9872  흑석(중앙대입구)  동작구  흑석동  426497  20211
9873  흑석(중앙대입구)  동작구  흑석동  336883  20211
9874  흑석(중앙대입구)  동작구  흑석동  339637  20211

[9875 rows x 5 columns]

In [ ]:
# sw19= sw19.reset_index(drop=True)
# sw20= sw20.reset_index(drop=True)
# sw21= sw21.reset_index(drop=True)

# sw19
# sw20
# sw21

# sw19x = sw19.set_index("지하철역")
# sw19x

             구    동  총승하차인원    년분기
지하철역
4.19민주묘지   강북구  우이동  184362  20194
4.19민주묘지   강북구  우이동  211195  20194
4.19민주묘지   강북구  우이동  221738  20194
4.19민주묘지   강북구  우이동  202508  20193
4.19민주묘지   강북구  우이동  159408  20193
...        ...  ...     ...    ...
흑석(중앙대입구)  동작구  흑석동  715039  20192
흑석(중앙대입구)  동작구  흑석동  695586  20192
흑석(중앙대입구)  동작구  흑석동  700486  20191
흑석(중앙대입구)  동작구  흑석동  475403  20191
흑석(중앙대입구)  동작구  흑석동  553747  20191

[10203 rows x 4 columns]

In [ ]:
# sw19x.reset_index(drop=True)

         구    동  총승하차인원    년분기
0      강북구  우이동  184362  20194
1      강북구  우이동  211195  20194
2      강북구  우이동  221738  20194
3      강북구  우이동  202508  20193
4      강북구  우이동  159408  20193
...    ...  ...     ...    ...
10198  동작구  흑석동  715039  20192
10199  동작구  흑석동  695586  20192
10200  동작구  흑석동  700486  20191
10201  동작구  흑석동  475403  20191
10202  동작구  흑석동  553747  20191

[10203 rows x 4 columns]

In [6]:
merged = pd.concat([sw19, sw20, sw21], axis=0, ignore_index=True)
merged

            지하철역    구    동  총승하차인원    년분기
0       4.19민주묘지  강북구  우이동  184362  20194
1       4.19민주묘지  강북구  우이동  211195  20194
2       4.19민주묘지  강북구  우이동  221738  20194
3       4.19민주묘지  강북구  우이동  202508  20193
4       4.19민주묘지  강북구  우이동  159408  20193
...          ...  ...  ...     ...    ...
29886  흑석(중앙대입구)  동작구  흑석동  411629  20212
29887  흑석(중앙대입구)  동작구  흑석동  413572  20212
29888  흑석(중앙대입구)  동작구  흑석동  426497  20211
29889  흑석(중앙대입구)  동작구  흑석동  336883  20211
29890  흑석(중앙대입구)  동작구  흑석동  339637  20211

[29891 rows x 5 columns]

In [7]:
merged = merged.rename(columns={'구': '시군구', '동': '행정동', '총승하차인원':'총_승객수'}, inplace=False)

NameError: name 'merged' is not defined

In [4]:
merged = merged.dropna(subset=['행정동'])
merged

NameError: name 'merged' is not defined

In [9]:
# 오류발생

merged 동별로 지하철역명, 갯수 확인

In [10]:
# merged 데이터프레임의 컬럼 이름을 확인
print(merged.columns)

# '지하철역' 컬럼이 있는지 확인 후, 없으면 컬럼 이름을 변경
if '지하철역' not in merged.columns:
    # 예를 들어, '지하철역'이 '지하철역 이름'으로 되어 있다면, 이름을 수정
    merged.rename(columns={'지하철역 이름': '지하철역'}, inplace=True)

# '동'별로 지하철역을 그룹화하여 나열
grouped_by_dong = merged.groupby('행정동')['지하철역'].apply(list).reset_index()

# 0번 인덱스 행 삭제
grouped_by_dong = grouped_by_dong.drop(index=0)

# '지하철역' 컬럼에서 중복값을 제거하고 고유한 값만 남기기
grouped_by_dong['지하철역'] = grouped_by_dong['지하철역'].apply(lambda x: ', '.join(sorted(set(x))) if isinstance(x, list) else x)

# 결과 확인
print(grouped_by_dong.head())

# 수정된 DataFrame을 CSV로 저장
grouped_by_dong.to_csv('dong_sw.csv', index=False)
print('CSV 저장 성공')

# '지하철역' 컬럼에서 고유값의 개수를 확인
print(grouped_by_dong['지하철역'].nunique())

Index(['지하철역', '시군구', '행정동', '총_승객수', '년분기'], dtype='object')
    행정동            지하철역
1  가락1동        가락시장, 송파
2  가락2동        개롱, 경찰병원
3  가락본동              오금
4   가산동     가산디지털단지, 독산
5  가양1동  마곡, 마곡나루, 양천향교
CSV 저장 성공
225

dong 에 지하철역 추가해서 확인 (22, 23, 24)

In [24]:
# merged 데이터에서 지하철역과 행정동 병합

sw_dong = pd.merge(dong, merged[['지하철역','행정동']],on=['행정동'], how='left')
sw_dong

         행정동   시군구      총_승객수    년분기  지하철역
0       가락1동   송파구  1687061.0  20221  가락시장
1       가락1동   송파구  1687061.0  20221  가락시장
2       가락1동   송파구  1687061.0  20221  가락시장
3       가락1동   송파구  1687061.0  20221  가락시장
4       가락1동   송파구  1687061.0  20221  가락시장
...      ...   ...        ...    ...   ...
251435  화곡본동   강서구        0.0  20243   NaN
251436   황학동    중구        0.0  20243   NaN
251437   회기동  동대문구        0.0  20243   NaN
251438   후암동   용산구        0.0  20243   NaN
251439  휘경2동  동대문구        0.0  20243   NaN

[251440 rows x 5 columns]

In [26]:
sw_dong['지하철역'] = sw_dong['지하철역'].fillna(0)
sw_dong

         행정동   시군구      총_승객수    년분기  지하철역
0       가락1동   송파구  1687061.0  20221  가락시장
1       가락1동   송파구  1687061.0  20221  가락시장
2       가락1동   송파구  1687061.0  20221  가락시장
3       가락1동   송파구  1687061.0  20221  가락시장
4       가락1동   송파구  1687061.0  20221  가락시장
...      ...   ...        ...    ...   ...
251435  화곡본동   강서구        0.0  20243     0
251436   황학동    중구        0.0  20243     0
251437   회기동  동대문구        0.0  20243     0
251438   후암동   용산구        0.0  20243     0
251439  휘경2동  동대문구        0.0  20243     0

[251440 rows x 5 columns]

동별로 지하철역 확인

In [39]:
# 지하철역 0인 데이터 제외

filter_sw_dong = sw_dong[sw_dong['지하철역'] !=0]
filter_sw_dong

# hang_sw = filter_sw_dong[['행정동', '지하철역', '년분기']]
# hang_sw

# '행정동', '지하철역', '년분기' 컬럼만 선택하고 중복 제거
unique_data = sw_dong[['행정동', '지하철역', '년분기', '총_승객수']].drop_duplicates()

# 결과 확인
unique_data.head()

      행정동     지하철역    년분기      총_승객수
0    가락1동     가락시장  20221  1687061.0
48   가락1동       송파  20221  1687061.0
180  가락2동       개롱  20221   939791.0
192  가락2동     경찰병원  20221   939791.0
252   가산동  가산디지털단지  20221  3436767.0

In [ ]:
# 확인차 파일저장
# unique_data.to_csv('unique_data.csv', index=False, encoding='utf-8')

In [ ]:
# 데이터가 있는 DataFrame 'sw_dong'을 예시로 가정

# '지하철역', '호선명', '시군구', '행정동', '년분기' 기준으로 그룹화하여 총_승객수 합산
sw_dong_grouped = sw_dong.groupby(['지하철역', '호선명', '시군구', '행정동', '년분기'], as_index=False)['총_승객수'].sum()

# 중복된 데이터가 있는 경우 제거
sw_dong_unique = sw_dong_grouped.drop_duplicates()

# 결과 확인
print(sw_dong_unique)