In [1]:
import pandas as pd

In [2]:
data_01 = pd.read_csv('서울시_상권분석서비스(점포-행정동)_2021년.csv', encoding='EUC-KR')
data_02 = pd.read_csv(r'D:\Work\team_project\project2\oos\data\거주인구\Resident_Population_Dong424.csv')

In [3]:
data_01.info(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141137 entries, 0 to 141136
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   기준_년분기_코드    141137 non-null  int64
 1   행정동_코드       141137 non-null  int64
 2   행정동_코드_명     141137 non-null  object
 3   서비스_업종_코드    141137 non-null  object
 4   서비스_업종_코드_명  141137 non-null  object
 5   점포_수         141137 non-null  int64
 6   유사_업종_점포_수   141137 non-null  int64
 7   개업_율         141137 non-null  int64
 8   개업_점포_수      141137 non-null  int64
 9   폐업_률         141137 non-null  int64
 10  폐업_점포_수      141137 non-null  int64
 11  프랜차이즈_점포_수   141137 non-null  int64
dtypes: int64(9), object(3)
memory usage: 12.9+ MB

In [4]:
set_a = set(data_01['행정동_코드_명'])
set_b = set(data_02['동별'])
common_values = set_a & set_b  # A와 B에 모두 있는 값
only_in_a = set_a - set_b  # A에만 있는 값
only_in_b = set_b - set_a  # B에만 있는 값

In [5]:
# 결과 출력
print("A와 B에 모두 있는 값:")
print(common_values)

print("\nA에만 있는 값:")
print(only_in_a)

print("\nB에만 있는 값:")
print(only_in_b)

A와 B에 모두 있는 값:
{'위례동', '망원2동', '송파2동', '신월3동', '상봉1동', '사당1동', '공항동', '신길5동', '우장산동', '공덕동', '숭인1동', '서원동', '정릉1동', '남가좌2동', '황학동', '세곡동', '청운효자동', '휘경1동', '효창동', '남영동', '구로5동', '서교동', '가락1동', '개포4동', '등촌2동', '보문동', '문정1동', '방이1동', '둔촌1동', '삼각산동', '방화1동', '연남동', '종로5·6가동', '성내2동', '창1동', '청량리동', '목1동', '상도1동', '전농2동', '고덕1동', '신사1동', '창신3동', '화곡2동', '수유2동', '대치4동', '대흥동', '월계3동', '방학1동', '원효로2동', '신당5동', '가양3동', '오금동', '여의동', '마천2동', '반포3동', '양평2동', '돈암1동', '신림동', '성수2가1동', '금호2·3가동', '등촌1동', '화곡4동', '정릉3동', '성수1가2동', '장위3동', '회현동', '조원동', '발산1동', '성내3동', '구산동', '대치2동', '무악동', '옥수동', '이촌2동', '한남동', '신월7동', '내곡동', '난향동', '사당3동', '서초2동', '응암1동', '신대방1동', '종로1·2·3·4가동', '역삼2동', '대림1동', '양재2동', '상도4동', '쌍문2동', '대조동', '자양3동', '마천1동', '쌍문1동', '가락2동', '월계1동', '우이동', '노량진2동', '개봉1동', '창신2동', '상일동', '신정3동', '대림2동', '목4동', '남현동', '신수동', '중앙동', '장충동', '구의2동', '흑석동', '일원2동', '대림3동', '충현동', '필동', '천연동', '소공동', '수궁동', '삼성2동', '삼성1동', '삼성동', '명일2동', '신원동', '잠실4동', '연희동', '성내1동', '월계2동', '가양2동', '일원1동', '신길7동', '목5동', '상계9동', '서초4동', '남가좌1동', '용강동', '응암3동', '목3동', '신월1동', '약수동', '사직동', '낙성대동', '잠실3동', '오류1동', '신사2동', '성수2가3동', '창2동', '녹번동', '쌍문3동', '하계2동', '다산동', '정릉4동', '이촌1동', '독산1동', '면목5동', '삼전동', '전농1동', '상봉2동', '풍납2동', '월곡2동', '방학3동', '안암동', '자양1동', '석촌동', '암사1동', '이태원2동', '회기동', '노량진1동', '화곡8동', '은천동', '목2동', '마장동', '화곡3동', '인헌동', '서강동', '구로4동', '장위2동', '독산2동', '문래동', '상계8동', '문정2동', '정릉2동', '원효로1동', '창4동', '화양동', '대학동', '둔촌2동', '행운동', '하계1동', '금호1가동', '성수1가1동', '당산2동', '반포본동', '개봉3동', '개봉2동', '송중동', '가양1동', '이문1동', '길음1동', '번1동', '구로1동', '잠원동', '후암동', '망우3동', '진관동', '휘경2동', '오류2동', '상계2동', '길음2동', '등촌3동', '북가좌2동', '합정동', '거여2동', '신월5동', '난곡동', '신월2동', '이문2동', '청림동', '독산4동', '잠실본동', '석관동', '잠실7동', '신길6동', '사당5동', '중계1동', '불광1동', '가락본동', '상암동', '역촌동', '방배본동', '혜화동', '반포4동', '돈암2동', '사근동', '동화동', '용답동', '방화3동', '이태원1동', '장안2동', '창신1동', '잠실2동', '월곡1동', '인수동', '수유1동', '신정6동', '상계1동', '번2동', '거여1동', '묵1동', '답십리2동', '북가좌1동', '고덕2동', '장위1동', '왕십리도선동', '성산2동', '화곡1동', '상계10동', '서빙고동', '송천동', '구로2동', '용신동', '암사2동', '도화동', '반포1동', '도봉1동', '송정동', '삼청동', '장지동', '상계3·4동', '가회동', '응암2동', '신월6동', '신대방2동', '청담동', '상도3동', '중화2동', '잠실6동', '성산1동', '청구동', '보광동', '행당2동', '군자동', '반포2동', '염리동', '중곡4동', '방배2동', '면목4동', '명일1동', '홍제1동', '암사3동', '도곡2동', '증산동', '구의1동', '신도림동', '보라매동', '홍은1동', '중림동', '상계5동', '창3동', '영등포본동', '대치1동', '번3동', '신정1동', '청파동', '중계2·3동', '중곡3동', '을지로동', '홍제2동', '성북동', '광희동', '사당4동', '길동', '홍제3동', '시흥1동', '면목본동', '중계본동', '방배1동', '중계4동', '양평1동', '사당2동', '창5동', '고척1동', '방배4동', '성현동', '면목7동', '시흥2동', '시흥4동', '신정2동', '용문동', '상계6·7동', '서림동', '가리봉동', '신사동', '일원본동', '천호3동', '쌍문4동', '삼양동', '공릉2동', '중곡1동', '수유3동', '신길3동', '수색동', '신길4동', '구의3동', '금호4가동', '논현2동', '풍납1동', '행당1동', '방학2동', '신당동', '신정7동', '신길1동', '홍은2동', '고척2동', '이화동', '갈현2동', '신내2동', '송파1동', '교남동', '서초1동', '시흥3동', '제기동', '묵2동', '방화2동', '답십리1동', '망우본동', '평창동', '자양4동', '서초3동', '화곡6동', '용산2가동', '불광2동', '미아동', '신내1동', '명동', '삼선동', '수서동', '역삼1동', '천호1동', '개포2동', '망원1동', '방이2동', '미성동', '중화1동', '화곡본동', '압구정동', '왕십리2동', '독산3동', '논현1동', '염창동', '면목2동', '갈현1동', '청룡동', '도봉2동', '강일동', '영등포동', '장안1동', '오륜동', '개포1동', '당산1동', '부암동', '신월4동', '도곡1동', '신촌동', '숭인2동', '천호2동', '종암동', '한강로동', '시흥5동', '응봉동', '가산동', '구로3동', '면목3·8동', '방배3동', '신정4동', '광장동', '대방동', '상도2동', '북아현동', '아현동', '중곡2동', '공릉1동', '동선동', '자양2동', '도림동', '능동', '양재1동'}

A에만 있는 값:
{'항동'}

B에만 있는 값:
{'관악구 신사동'}

In [6]:
data_01.loc[data_01['행정동_코드'] == 11620685, '행정동_코드_명'] = '관악구 신사동'

In [7]:
data_01[data_01['행정동_코드_명'] == '관악구 신사동'][:1]

,기준_년분기_코드,행정동_코드,행정동_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
27437,20211,11620685,관악구 신사동,CS100001,한식음식점,115,127,5,6,6,7,12

In [8]:
dong_check = data_01[data_01['행정동_코드_명'] == '신사동']

In [9]:
dong_check.head(1)

,기준_년분기_코드,행정동_코드,행정동_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
29684,20211,11680510,신사동,CS100001,한식음식점,276,314,2,6,2,5,38

In [10]:
set_a = set(data_01['행정동_코드_명'])
set_b = set(data_02['동별'])
common_values = set_a & set_b  # A와 B에 모두 있는 값
only_in_a = set_a - set_b  # A에만 있는 값
only_in_b = set_b - set_a  # B에만 있는 값

# 결과 출력
print("A와 B에 모두 있는 값:")
print(common_values)

print("\nA에만 있는 값:")
print(only_in_a)

print("\nB에만 있는 값:")
print(only_in_b)

A와 B에 모두 있는 값:
{'위례동', '망원2동', '송파2동', '신월3동', '상봉1동', '사당1동', '공항동', '신길5동', '우장산동', '공덕동', '숭인1동', '서원동', '정릉1동', '남가좌2동', '황학동', '세곡동', '청운효자동', '휘경1동', '효창동', '남영동', '구로5동', '서교동', '가락1동', '개포4동', '등촌2동', '보문동', '문정1동', '방이1동', '둔촌1동', '삼각산동', '방화1동', '연남동', '종로5·6가동', '성내2동', '창1동', '청량리동', '목1동', '상도1동', '전농2동', '고덕1동', '신사1동', '창신3동', '화곡2동', '수유2동', '대치4동', '대흥동', '월계3동', '방학1동', '원효로2동', '신당5동', '가양3동', '오금동', '여의동', '마천2동', '반포3동', '양평2동', '돈암1동', '신림동', '성수2가1동', '금호2·3가동', '등촌1동', '화곡4동', '정릉3동', '성수1가2동', '장위3동', '회현동', '조원동', '발산1동', '성내3동', '구산동', '대치2동', '무악동', '옥수동', '이촌2동', '한남동', '신월7동', '내곡동', '난향동', '사당3동', '서초2동', '응암1동', '신대방1동', '종로1·2·3·4가동', '역삼2동', '대림1동', '양재2동', '상도4동', '쌍문2동', '대조동', '자양3동', '마천1동', '쌍문1동', '가락2동', '월계1동', '우이동', '노량진2동', '개봉1동', '창신2동', '상일동', '신정3동', '대림2동', '목4동', '남현동', '신수동', '중앙동', '장충동', '구의2동', '흑석동', '일원2동', '대림3동', '충현동', '필동', '천연동', '소공동', '수궁동', '삼성2동', '삼성1동', '삼성동', '명일2동', '신원동', '잠실4동', '연희동', '성내1동', '월계2동', '가양2동', '일원1동', '신길7동', '목5동', '상계9동', '서초4동', '남가좌1동', '용강동', '응암3동', '목3동', '신월1동', '약수동', '사직동', '낙성대동', '잠실3동', '오류1동', '신사2동', '성수2가3동', '창2동', '녹번동', '쌍문3동', '하계2동', '다산동', '정릉4동', '이촌1동', '독산1동', '면목5동', '삼전동', '전농1동', '상봉2동', '풍납2동', '월곡2동', '방학3동', '안암동', '자양1동', '석촌동', '암사1동', '이태원2동', '회기동', '노량진1동', '화곡8동', '은천동', '목2동', '마장동', '화곡3동', '인헌동', '서강동', '구로4동', '장위2동', '독산2동', '문래동', '상계8동', '문정2동', '정릉2동', '원효로1동', '창4동', '화양동', '대학동', '둔촌2동', '행운동', '하계1동', '금호1가동', '성수1가1동', '당산2동', '반포본동', '개봉3동', '개봉2동', '송중동', '가양1동', '이문1동', '길음1동', '번1동', '구로1동', '잠원동', '후암동', '망우3동', '진관동', '휘경2동', '오류2동', '상계2동', '길음2동', '등촌3동', '북가좌2동', '합정동', '거여2동', '신월5동', '난곡동', '신월2동', '이문2동', '청림동', '독산4동', '잠실본동', '석관동', '잠실7동', '신길6동', '사당5동', '중계1동', '불광1동', '가락본동', '상암동', '역촌동', '방배본동', '혜화동', '반포4동', '돈암2동', '사근동', '동화동', '용답동', '방화3동', '이태원1동', '장안2동', '창신1동', '잠실2동', '월곡1동', '인수동', '수유1동', '신정6동', '상계1동', '번2동', '거여1동', '묵1동', '답십리2동', '북가좌1동', '고덕2동', '장위1동', '왕십리도선동', '성산2동', '화곡1동', '상계10동', '서빙고동', '송천동', '구로2동', '용신동', '암사2동', '도화동', '반포1동', '도봉1동', '송정동', '삼청동', '장지동', '상계3·4동', '가회동', '응암2동', '신월6동', '신대방2동', '청담동', '상도3동', '중화2동', '잠실6동', '성산1동', '청구동', '보광동', '행당2동', '군자동', '반포2동', '염리동', '중곡4동', '방배2동', '면목4동', '명일1동', '홍제1동', '암사3동', '도곡2동', '증산동', '구의1동', '신도림동', '보라매동', '홍은1동', '중림동', '상계5동', '창3동', '영등포본동', '대치1동', '번3동', '신정1동', '청파동', '중계2·3동', '중곡3동', '을지로동', '홍제2동', '성북동', '광희동', '사당4동', '길동', '홍제3동', '시흥1동', '면목본동', '중계본동', '방배1동', '중계4동', '양평1동', '사당2동', '창5동', '고척1동', '방배4동', '성현동', '면목7동', '시흥2동', '시흥4동', '신정2동', '용문동', '상계6·7동', '서림동', '가리봉동', '신사동', '일원본동', '천호3동', '쌍문4동', '삼양동', '공릉2동', '중곡1동', '수유3동', '신길3동', '수색동', '관악구 신사동', '구의3동', '신길4동', '금호4가동', '논현2동', '풍납1동', '행당1동', '방학2동', '신당동', '신정7동', '신길1동', '홍은2동', '고척2동', '이화동', '갈현2동', '신내2동', '송파1동', '교남동', '서초1동', '시흥3동', '제기동', '묵2동', '방화2동', '답십리1동', '망우본동', '평창동', '자양4동', '서초3동', '화곡6동', '용산2가동', '불광2동', '미아동', '신내1동', '명동', '삼선동', '수서동', '역삼1동', '천호1동', '개포2동', '망원1동', '방이2동', '미성동', '중화1동', '화곡본동', '압구정동', '왕십리2동', '독산3동', '논현1동', '염창동', '면목2동', '갈현1동', '청룡동', '도봉2동', '강일동', '영등포동', '장안1동', '오륜동', '개포1동', '당산1동', '부암동', '신월4동', '도곡1동', '신촌동', '숭인2동', '천호2동', '종암동', '한강로동', '시흥5동', '응봉동', '가산동', '구로3동', '면목3·8동', '방배3동', '신정4동', '광장동', '대방동', '상도2동', '북아현동', '아현동', '중곡2동', '공릉1동', '동선동', '자양2동', '도림동', '능동', '양재1동'}

A에만 있는 값:
{'항동'}

B에만 있는 값:
set()

In [11]:
data_01.loc[data_01['행정동_코드_명'] == '항동', '행정동_코드_명'] = '오류2동'

In [12]:
set_a = set(data_01['행정동_코드_명'])
set_b = set(data_02['동별'])
common_values = set_a & set_b  # A와 B에 모두 있는 값
only_in_a = set_a - set_b  # A에만 있는 값
only_in_b = set_b - set_a  # B에만 있는 값

# 결과 출력
print("A와 B에 모두 있는 값:")
print(common_values)

print("\nA에만 있는 값:")
print(only_in_a)

print("\nB에만 있는 값:")
print(only_in_b)

A와 B에 모두 있는 값:
{'위례동', '망원2동', '송파2동', '신월3동', '상봉1동', '사당1동', '공항동', '신길5동', '우장산동', '공덕동', '숭인1동', '서원동', '정릉1동', '남가좌2동', '황학동', '세곡동', '청운효자동', '휘경1동', '효창동', '남영동', '구로5동', '서교동', '가락1동', '개포4동', '등촌2동', '보문동', '문정1동', '방이1동', '둔촌1동', '삼각산동', '방화1동', '연남동', '종로5·6가동', '성내2동', '창1동', '청량리동', '목1동', '상도1동', '전농2동', '고덕1동', '신사1동', '창신3동', '화곡2동', '수유2동', '대치4동', '대흥동', '월계3동', '방학1동', '원효로2동', '신당5동', '가양3동', '오금동', '여의동', '마천2동', '반포3동', '양평2동', '돈암1동', '신림동', '성수2가1동', '금호2·3가동', '등촌1동', '화곡4동', '정릉3동', '성수1가2동', '장위3동', '회현동', '조원동', '발산1동', '성내3동', '구산동', '대치2동', '무악동', '옥수동', '이촌2동', '한남동', '신월7동', '내곡동', '난향동', '사당3동', '서초2동', '응암1동', '신대방1동', '종로1·2·3·4가동', '역삼2동', '대림1동', '양재2동', '상도4동', '쌍문2동', '대조동', '자양3동', '마천1동', '쌍문1동', '가락2동', '월계1동', '우이동', '노량진2동', '개봉1동', '창신2동', '상일동', '신정3동', '대림2동', '목4동', '남현동', '신수동', '중앙동', '장충동', '구의2동', '흑석동', '일원2동', '대림3동', '충현동', '필동', '천연동', '소공동', '수궁동', '삼성2동', '삼성1동', '삼성동', '명일2동', '신원동', '잠실4동', '연희동', '성내1동', '월계2동', '가양2동', '일원1동', '신길7동', '목5동', '상계9동', '서초4동', '남가좌1동', '용강동', '응암3동', '목3동', '신월1동', '약수동', '사직동', '낙성대동', '잠실3동', '오류1동', '신사2동', '성수2가3동', '창2동', '녹번동', '쌍문3동', '하계2동', '다산동', '정릉4동', '이촌1동', '독산1동', '면목5동', '삼전동', '전농1동', '상봉2동', '풍납2동', '월곡2동', '방학3동', '안암동', '자양1동', '석촌동', '암사1동', '이태원2동', '회기동', '노량진1동', '화곡8동', '은천동', '목2동', '마장동', '화곡3동', '인헌동', '서강동', '구로4동', '장위2동', '독산2동', '문래동', '상계8동', '문정2동', '정릉2동', '원효로1동', '창4동', '화양동', '대학동', '둔촌2동', '행운동', '하계1동', '금호1가동', '성수1가1동', '당산2동', '반포본동', '개봉3동', '개봉2동', '송중동', '가양1동', '이문1동', '길음1동', '번1동', '구로1동', '잠원동', '후암동', '망우3동', '진관동', '휘경2동', '오류2동', '상계2동', '길음2동', '등촌3동', '북가좌2동', '합정동', '거여2동', '신월5동', '난곡동', '신월2동', '이문2동', '청림동', '독산4동', '잠실본동', '석관동', '잠실7동', '신길6동', '사당5동', '중계1동', '불광1동', '가락본동', '상암동', '역촌동', '방배본동', '혜화동', '반포4동', '돈암2동', '사근동', '동화동', '용답동', '방화3동', '이태원1동', '장안2동', '창신1동', '잠실2동', '월곡1동', '인수동', '수유1동', '신정6동', '상계1동', '번2동', '거여1동', '묵1동', '답십리2동', '북가좌1동', '고덕2동', '장위1동', '왕십리도선동', '성산2동', '화곡1동', '상계10동', '서빙고동', '송천동', '구로2동', '용신동', '암사2동', '도화동', '반포1동', '도봉1동', '송정동', '삼청동', '장지동', '상계3·4동', '가회동', '응암2동', '신월6동', '신대방2동', '청담동', '상도3동', '중화2동', '잠실6동', '성산1동', '청구동', '보광동', '행당2동', '군자동', '반포2동', '염리동', '중곡4동', '방배2동', '면목4동', '명일1동', '홍제1동', '암사3동', '도곡2동', '증산동', '구의1동', '신도림동', '보라매동', '홍은1동', '중림동', '상계5동', '창3동', '영등포본동', '대치1동', '번3동', '신정1동', '청파동', '중계2·3동', '중곡3동', '을지로동', '홍제2동', '성북동', '광희동', '사당4동', '길동', '홍제3동', '시흥1동', '면목본동', '중계본동', '방배1동', '중계4동', '양평1동', '사당2동', '창5동', '고척1동', '방배4동', '성현동', '면목7동', '시흥2동', '시흥4동', '신정2동', '용문동', '상계6·7동', '서림동', '가리봉동', '신사동', '일원본동', '천호3동', '쌍문4동', '삼양동', '공릉2동', '중곡1동', '수유3동', '신길3동', '수색동', '관악구 신사동', '구의3동', '신길4동', '금호4가동', '논현2동', '풍납1동', '행당1동', '방학2동', '신당동', '신정7동', '신길1동', '홍은2동', '고척2동', '이화동', '갈현2동', '신내2동', '송파1동', '교남동', '서초1동', '시흥3동', '제기동', '묵2동', '방화2동', '답십리1동', '망우본동', '평창동', '자양4동', '서초3동', '화곡6동', '용산2가동', '불광2동', '미아동', '신내1동', '명동', '삼선동', '수서동', '역삼1동', '천호1동', '개포2동', '망원1동', '방이2동', '미성동', '중화1동', '화곡본동', '압구정동', '왕십리2동', '독산3동', '논현1동', '염창동', '면목2동', '갈현1동', '청룡동', '도봉2동', '강일동', '영등포동', '장안1동', '오륜동', '개포1동', '당산1동', '부암동', '신월4동', '도곡1동', '신촌동', '숭인2동', '천호2동', '종암동', '한강로동', '시흥5동', '응봉동', '가산동', '구로3동', '면목3·8동', '방배3동', '신정4동', '광장동', '대방동', '상도2동', '북아현동', '아현동', '중곡2동', '공릉1동', '동선동', '자양2동', '도림동', '능동', '양재1동'}

A에만 있는 값:
set()

B에만 있는 값:
set()

In [13]:
data_01.columns

Index(['기준_년분기_코드', '행정동_코드', '행정동_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '점포_수',
       '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')

서비스 명 통일작업

In [14]:
data_01['서비스_업종_코드_명'].unique()

array(['한식음식점', '중식음식점', '일식음식점', '양식음식점', '제과점', '패스트푸드점', '치킨전문점',
       '분식전문점', '호프-간이주점', '커피-음료', '일반교습학원', '외국어학원', '예술학원', '스포츠 강습',
       '일반의원', '치과의원', '한의원', '동물병원', '변호사사무소', '기타법무서비스', '세무사사무소',
       '당구장', '골프연습장', 'PC방', '전자게임장', '자동차수리', '자동차미용', '미용실', '네일숍',
       '피부관리실', '세탁소', '가전제품수리', '부동산중개업', '여관', '게스트하우스', '고시원', '노래방',
       '녹음실', '사진관', '통번역서비스', '건축물청소', '여행사', '비디오/서적임대', '의류임대', '슈퍼마켓',
       '편의점', '컴퓨터및주변장치판매', '핸드폰', '주류도매', '미곡판매', '육류판매', '수산물판매', '청과상',
       '반찬가게', '일반의류', '유아의류', '신발', '가방', '안경', '시계및귀금속', '의약품', '의료기기',
       '서적', '문구', '화장품', '미용재료', '운동/경기용품', '완구', '섬유제품', '화초', '애완동물',
       '가구', '가전제품', '철물점', '인테리어', '조명용품', '자동차부품', '모터사이클및부품',
       '재생용품 판매점', '예술품', '전자상거래업', '컴퓨터학원', '변리사사무소', '법무사사무소', '회계사사무소',
       '볼링장', '기타오락장', '복권방', '통신기기수리', '스포츠클럽', '독서실', '가정용품임대', '한복점',
       '자전거 및 기타운송장비', '악기', '주유소', 'DVD방', '모터사이클수리', '중고차판매', '중고가구'],
      dtype=object)