In [1]:
import pandas as pd

In [2]:
data_01 = pd.read_csv('서울시_상권분석서비스(점포-행정동)_2020년.csv', encoding='EUC-KR')
data_02 = pd.read_csv(r'D:\Work\team_project\project2\oos\data\거주인구\Resident_Population_Dong424.csv')

In [3]:
data_01.info(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140538 entries, 0 to 140537
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   기준_년분기_코드    140538 non-null  int64
 1   행정동_코드       140538 non-null  int64
 2   행정동_코드_명     140538 non-null  object
 3   서비스_업종_코드    140538 non-null  object
 4   서비스_업종_코드_명  140538 non-null  object
 5   점포_수         140538 non-null  int64
 6   유사_업종_점포_수   140538 non-null  int64
 7   개업_율         140538 non-null  int64
 8   개업_점포_수      140538 non-null  int64
 9   폐업_률         140538 non-null  int64
 10  폐업_점포_수      140538 non-null  int64
 11  프랜차이즈_점포_수   140538 non-null  int64
dtypes: int64(9), object(3)
memory usage: 12.9+ MB

In [4]:
set_a = set(data_01['행정동_코드_명'])
set_b = set(data_02['동별'])
common_values = set_a & set_b  # A와 B에 모두 있는 값
only_in_a = set_a - set_b  # A에만 있는 값
only_in_b = set_b - set_a  # B에만 있는 값

In [5]:
# 결과 출력
print("A와 B에 모두 있는 값:")
print(common_values)

print("\nA에만 있는 값:")
print(only_in_a)

print("\nB에만 있는 값:")
print(only_in_b)

A와 B에 모두 있는 값:
{'신길1동', '상계5동', '등촌2동', '면목3·8동', '강일동', '독산2동', '중화1동', '중림동', '서원동', '신길3동', '응암1동', '송중동', '신내1동', '화곡8동', '명동', '우장산동', '사당3동', '면목본동', '불광1동', '목5동', '돈암1동', '성내3동', '중곡4동', '천호2동', '창4동', '신도림동', '역삼2동', '평창동', '무악동', '대치1동', '가양2동', '다산동', '보라매동', '종로1·2·3·4가동', '난곡동', '난향동', '오금동', '논현1동', '청룡동', '서림동', '길동', '금호1가동', '제기동', '이촌1동', '노량진2동', '옥수동', '화곡6동', '공덕동', '성내1동', '행당1동', '일원1동', '망우3동', '창3동', '양평2동', '상도2동', '아현동', '응암2동', '삼각산동', '수궁동', '구산동', '발산1동', '잠실4동', '종암동', '반포3동', '마천2동', '가회동', '영등포동', '혜화동', '등촌1동', '흑석동', '광장동', '상도3동', '화곡본동', '월계3동', '답십리1동', '남현동', '홍제3동', '필동', '북가좌2동', '서강동', '월계1동', '방배2동', '보광동', '면목4동', '삼전동', '오륜동', '진관동', '도곡2동', '길음1동', '면목5동', '창5동', '역삼1동', '영등포본동', '창신1동', '효창동', '고덕2동', '이문1동', '일원본동', '장위2동', '성수2가3동', '녹번동', '마장동', '개포1동', '정릉4동', '방배1동', '개봉3동', '성산1동', '중곡1동', '황학동', '쌍문4동', '시흥4동', '홍제1동', '사당2동', '미성동', '송천동', '행당2동', '구의3동', '방이1동', '신정4동', '전농1동', '쌍문3동', '성현동', '부암동', '휘경2동', '상계3·4동', '잠실본동', '방학2동', '상계6·7동', '신월4동', '합정동', '상암동', '대흥동', '신월1동', '양재2동', '능동', '위례동', '망우본동', '하계1동', '가락2동', '염리동', '묵2동', '사근동', '은천동', '자양3동', '잠실6동', '방배3동', '가양1동', '우이동', '공릉2동', '청구동', '방배본동', '응봉동', '용문동', '오류2동', '수유2동', '장지동', '시흥5동', '내곡동', '송정동', '월계2동', '상계2동', '송파1동', '묵1동', '서초1동', '신당동', '청담동', '방학1동', '거여1동', '가리봉동', '창신2동', '청운효자동', '신림동', '동선동', '도곡1동', '명일1동', '장안1동', '성수2가1동', '북가좌1동', '개포2동', '남영동', '천연동', '화곡1동', '상도4동', '서빙고동', '세곡동', '신길4동', '불광2동', '성내2동', '회현동', '상일동', '휘경1동', '응암3동', '노량진1동', '반포4동', '청림동', '대림2동', '잠실7동', '정릉3동', '공릉1동', '용답동', '서초2동', '보문동', '동화동', '신정1동', '월곡2동', '금호4가동', '신길5동', '안암동', '대림1동', '상계1동', '신월6동', '삼성1동', '신길6동', '돈암2동', '중계2·3동', '방화1동', '용신동', '북아현동', '이촌2동', '방배4동', '암사1동', '중계4동', '대조동', '시흥3동', '하계2동', '방화2동', '회기동', '암사2동', '낙성대동', '독산1동', '개포4동', '성북동', '신원동', '청파동', '시흥1동', '도봉2동', '광희동', '이태원1동', '중곡3동', '자양1동', '약수동', '구로2동', '천호3동', '대치4동', '거여2동', '화곡4동', '사직동', '군자동', '방이2동', '이화동', '잠실3동', '쌍문2동', '독산4동', '남가좌2동', '오류1동', '대치2동', '금호2·3가동', '번2동', '당산1동', '인수동', '당산2동', '서초4동', '신정7동', '정릉2동', '신수동', '종로5·6가동', '용강동', '신월5동', '상봉1동', '압구정동', '청량리동', '수색동', '목2동', '석관동', '연희동', '천호1동', '수유1동', '여의동', '일원2동', '명일2동', '원효로2동', '둔촌1동', '미아동', '구의1동', '면목7동', '교남동', '신사동', '문래동', '문정1동', '정릉1동', '목3동', '남가좌1동', '역촌동', '숭인2동', '구로3동', '고척1동', '신길7동', '신대방2동', '신월7동', '갈현1동', '서초3동', '자양4동', '창2동', '을지로동', '방학3동', '길음2동', '중앙동', '이태원2동', '전농2동', '반포2동', '논현2동', '소공동', '상봉2동', '후암동', '연남동', '삼양동', '잠원동', '행운동', '번3동', '원효로1동', '사당4동', '등촌3동', '삼청동', '문정2동', '홍은1동', '중곡2동', '석촌동', '대방동', '구로5동', '왕십리도선동', '독산3동', '둔촌2동', '구의2동', '중계본동', '도림동', '한남동', '도화동', '송파2동', '염창동', '쌍문1동', '수유3동', '대림3동', '답십리2동', '잠실2동', '공항동', '마천1동', '고척2동', '성수1가2동', '신촌동', '개봉2동', '풍납1동', '장위3동', '상도1동', '신사1동', '신정3동', '화곡3동', '신당5동', '신정2동', '목4동', '대학동', '사당1동', '가산동', '고덕1동', '장충동', '가락본동', '양재1동', '용산2가동', '화곡2동', '양평1동', '증산동', '상계9동', '홍은2동', '암사3동', '수서동', '중계1동', '도봉1동', '신월3동', '번1동', '서교동', '충현동', '신월2동', '홍제2동', '목1동', '중화2동', '반포1동', '상계8동', '왕십리2동', '화양동', '성산2동', '방화3동', '반포본동', '신사2동', '신대방1동', '조원동', '창1동', '숭인1동', '면목2동', '구로4동', '신내2동', '창신3동', '장안2동', '한강로동', '가락1동', '삼성2동', '풍납2동', '이문2동', '사당5동', '신정6동', '상계10동', '망원1동', '장위1동', '가양3동', '망원2동', '갈현2동', '삼선동', '성수1가1동', '월곡1동', '시흥2동', '개봉1동', '구로1동', '삼성동', '인헌동', '자양2동'}

A에만 있는 값:
{'항동'}

B에만 있는 값:
{'관악구 신사동'}

In [6]:
data_01.loc[data_01['행정동_코드'] == 11620685, '행정동_코드_명'] = '관악구 신사동'

In [7]:
data_01[data_01['행정동_코드_명'] == '관악구 신사동'][:1]

,기준_년분기_코드,행정동_코드,행정동_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
27302,20201,11620685,관악구 신사동,CS100001,한식음식점,106,116,9,10,7,8,10

In [8]:
dong_check = data_01[data_01['행정동_코드_명'] == '신사동']

In [9]:
dong_check.head(1)

,기준_년분기_코드,행정동_코드,행정동_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
29539,20201,11680510,신사동,CS100001,한식음식점,270,308,3,9,3,10,38

In [10]:
set_a = set(data_01['행정동_코드_명'])
set_b = set(data_02['동별'])
common_values = set_a & set_b  # A와 B에 모두 있는 값
only_in_a = set_a - set_b  # A에만 있는 값
only_in_b = set_b - set_a  # B에만 있는 값

# 결과 출력
print("A와 B에 모두 있는 값:")
print(common_values)

print("\nA에만 있는 값:")
print(only_in_a)

print("\nB에만 있는 값:")
print(only_in_b)

A와 B에 모두 있는 값:
{'신길1동', '상계5동', '등촌2동', '면목3·8동', '강일동', '독산2동', '중화1동', '중림동', '서원동', '신길3동', '응암1동', '송중동', '신내1동', '화곡8동', '명동', '우장산동', '사당3동', '면목본동', '불광1동', '목5동', '돈암1동', '성내3동', '중곡4동', '천호2동', '창4동', '신도림동', '역삼2동', '평창동', '무악동', '대치1동', '가양2동', '다산동', '보라매동', '종로1·2·3·4가동', '난곡동', '난향동', '오금동', '논현1동', '청룡동', '서림동', '길동', '금호1가동', '제기동', '이촌1동', '노량진2동', '옥수동', '화곡6동', '공덕동', '성내1동', '행당1동', '일원1동', '망우3동', '창3동', '양평2동', '상도2동', '아현동', '응암2동', '삼각산동', '수궁동', '구산동', '발산1동', '잠실4동', '종암동', '반포3동', '마천2동', '가회동', '영등포동', '혜화동', '등촌1동', '흑석동', '광장동', '상도3동', '화곡본동', '월계3동', '답십리1동', '남현동', '홍제3동', '필동', '북가좌2동', '서강동', '월계1동', '방배2동', '보광동', '면목4동', '삼전동', '오륜동', '진관동', '도곡2동', '길음1동', '면목5동', '창5동', '역삼1동', '영등포본동', '창신1동', '효창동', '고덕2동', '이문1동', '일원본동', '장위2동', '성수2가3동', '녹번동', '마장동', '개포1동', '정릉4동', '방배1동', '개봉3동', '성산1동', '중곡1동', '황학동', '쌍문4동', '시흥4동', '홍제1동', '사당2동', '미성동', '송천동', '행당2동', '구의3동', '방이1동', '신정4동', '전농1동', '쌍문3동', '성현동', '부암동', '휘경2동', '상계3·4동', '잠실본동', '방학2동', '상계6·7동', '신월4동', '합정동', '상암동', '대흥동', '신월1동', '양재2동', '능동', '위례동', '망우본동', '하계1동', '가락2동', '염리동', '묵2동', '사근동', '은천동', '자양3동', '잠실6동', '방배3동', '가양1동', '우이동', '공릉2동', '청구동', '방배본동', '응봉동', '용문동', '오류2동', '수유2동', '장지동', '시흥5동', '내곡동', '송정동', '월계2동', '상계2동', '송파1동', '묵1동', '서초1동', '신당동', '청담동', '방학1동', '거여1동', '가리봉동', '창신2동', '청운효자동', '신림동', '동선동', '도곡1동', '명일1동', '장안1동', '성수2가1동', '북가좌1동', '개포2동', '남영동', '천연동', '화곡1동', '상도4동', '서빙고동', '세곡동', '신길4동', '불광2동', '성내2동', '회현동', '상일동', '휘경1동', '응암3동', '노량진1동', '반포4동', '청림동', '대림2동', '관악구 신사동', '잠실7동', '정릉3동', '공릉1동', '용답동', '서초2동', '보문동', '동화동', '신정1동', '월곡2동', '금호4가동', '신길5동', '안암동', '대림1동', '상계1동', '신월6동', '삼성1동', '신길6동', '돈암2동', '중계2·3동', '방화1동', '용신동', '북아현동', '이촌2동', '방배4동', '암사1동', '중계4동', '대조동', '시흥3동', '하계2동', '방화2동', '회기동', '암사2동', '낙성대동', '독산1동', '개포4동', '성북동', '신원동', '청파동', '시흥1동', '도봉2동', '광희동', '이태원1동', '중곡3동', '자양1동', '약수동', '구로2동', '천호3동', '대치4동', '거여2동', '화곡4동', '사직동', '군자동', '방이2동', '이화동', '잠실3동', '쌍문2동', '독산4동', '남가좌2동', '오류1동', '대치2동', '금호2·3가동', '번2동', '당산1동', '인수동', '당산2동', '서초4동', '신정7동', '정릉2동', '신수동', '종로5·6가동', '용강동', '신월5동', '상봉1동', '압구정동', '청량리동', '수색동', '목2동', '석관동', '연희동', '천호1동', '수유1동', '여의동', '일원2동', '명일2동', '원효로2동', '둔촌1동', '미아동', '구의1동', '면목7동', '교남동', '신사동', '문래동', '문정1동', '정릉1동', '목3동', '남가좌1동', '역촌동', '숭인2동', '구로3동', '고척1동', '신길7동', '신대방2동', '신월7동', '갈현1동', '서초3동', '자양4동', '창2동', '을지로동', '방학3동', '길음2동', '중앙동', '이태원2동', '전농2동', '반포2동', '논현2동', '소공동', '상봉2동', '후암동', '연남동', '삼양동', '잠원동', '행운동', '번3동', '원효로1동', '사당4동', '등촌3동', '삼청동', '문정2동', '홍은1동', '중곡2동', '석촌동', '대방동', '구로5동', '왕십리도선동', '독산3동', '둔촌2동', '구의2동', '중계본동', '도림동', '한남동', '도화동', '송파2동', '염창동', '쌍문1동', '수유3동', '대림3동', '답십리2동', '잠실2동', '공항동', '마천1동', '고척2동', '성수1가2동', '신촌동', '개봉2동', '풍납1동', '장위3동', '상도1동', '신사1동', '신정3동', '화곡3동', '신당5동', '신정2동', '목4동', '대학동', '사당1동', '가산동', '고덕1동', '장충동', '가락본동', '양재1동', '용산2가동', '화곡2동', '양평1동', '증산동', '상계9동', '홍은2동', '암사3동', '수서동', '중계1동', '도봉1동', '신월3동', '번1동', '서교동', '충현동', '신월2동', '홍제2동', '목1동', '중화2동', '반포1동', '상계8동', '왕십리2동', '화양동', '성산2동', '방화3동', '반포본동', '신사2동', '신대방1동', '조원동', '창1동', '숭인1동', '면목2동', '구로4동', '신내2동', '창신3동', '장안2동', '한강로동', '가락1동', '삼성2동', '풍납2동', '이문2동', '사당5동', '신정6동', '상계10동', '망원1동', '장위1동', '가양3동', '망원2동', '갈현2동', '삼선동', '성수1가1동', '월곡1동', '시흥2동', '개봉1동', '구로1동', '삼성동', '인헌동', '자양2동'}

A에만 있는 값:
{'항동'}

B에만 있는 값:
set()

In [11]:
data_01.loc[data_01['행정동_코드_명'] == '항동', '행정동_코드_명'] = '오류2동'

In [12]:
set_a = set(data_01['행정동_코드_명'])
set_b = set(data_02['동별'])
common_values = set_a & set_b  # A와 B에 모두 있는 값
only_in_a = set_a - set_b  # A에만 있는 값
only_in_b = set_b - set_a  # B에만 있는 값

# 결과 출력
print("A와 B에 모두 있는 값:")
print(common_values)

print("\nA에만 있는 값:")
print(only_in_a)

print("\nB에만 있는 값:")
print(only_in_b)

A와 B에 모두 있는 값:
{'신길1동', '상계5동', '등촌2동', '면목3·8동', '강일동', '독산2동', '중화1동', '중림동', '서원동', '신길3동', '응암1동', '송중동', '신내1동', '화곡8동', '명동', '우장산동', '사당3동', '면목본동', '불광1동', '목5동', '돈암1동', '성내3동', '중곡4동', '천호2동', '창4동', '신도림동', '역삼2동', '평창동', '무악동', '대치1동', '가양2동', '다산동', '보라매동', '종로1·2·3·4가동', '난곡동', '난향동', '오금동', '논현1동', '청룡동', '서림동', '길동', '금호1가동', '제기동', '이촌1동', '노량진2동', '옥수동', '화곡6동', '공덕동', '성내1동', '행당1동', '일원1동', '망우3동', '창3동', '양평2동', '상도2동', '아현동', '응암2동', '삼각산동', '수궁동', '구산동', '발산1동', '잠실4동', '종암동', '반포3동', '마천2동', '가회동', '영등포동', '혜화동', '등촌1동', '흑석동', '광장동', '상도3동', '화곡본동', '월계3동', '답십리1동', '남현동', '홍제3동', '필동', '북가좌2동', '서강동', '월계1동', '방배2동', '보광동', '면목4동', '삼전동', '오륜동', '진관동', '도곡2동', '길음1동', '면목5동', '창5동', '역삼1동', '영등포본동', '창신1동', '효창동', '고덕2동', '이문1동', '일원본동', '장위2동', '성수2가3동', '녹번동', '마장동', '개포1동', '정릉4동', '방배1동', '개봉3동', '성산1동', '중곡1동', '황학동', '쌍문4동', '시흥4동', '홍제1동', '사당2동', '미성동', '송천동', '행당2동', '구의3동', '방이1동', '신정4동', '전농1동', '쌍문3동', '성현동', '부암동', '휘경2동', '상계3·4동', '잠실본동', '방학2동', '상계6·7동', '신월4동', '합정동', '상암동', '대흥동', '신월1동', '양재2동', '능동', '위례동', '망우본동', '하계1동', '가락2동', '염리동', '묵2동', '사근동', '은천동', '자양3동', '잠실6동', '방배3동', '가양1동', '우이동', '공릉2동', '청구동', '방배본동', '응봉동', '용문동', '오류2동', '수유2동', '장지동', '시흥5동', '내곡동', '송정동', '월계2동', '상계2동', '송파1동', '묵1동', '서초1동', '신당동', '청담동', '방학1동', '거여1동', '가리봉동', '창신2동', '청운효자동', '신림동', '동선동', '도곡1동', '명일1동', '장안1동', '성수2가1동', '북가좌1동', '개포2동', '남영동', '천연동', '화곡1동', '상도4동', '서빙고동', '세곡동', '신길4동', '불광2동', '성내2동', '회현동', '상일동', '휘경1동', '응암3동', '노량진1동', '반포4동', '청림동', '대림2동', '관악구 신사동', '잠실7동', '정릉3동', '공릉1동', '용답동', '서초2동', '보문동', '동화동', '신정1동', '월곡2동', '금호4가동', '신길5동', '안암동', '대림1동', '상계1동', '신월6동', '삼성1동', '신길6동', '돈암2동', '중계2·3동', '방화1동', '용신동', '북아현동', '이촌2동', '방배4동', '암사1동', '중계4동', '대조동', '시흥3동', '하계2동', '방화2동', '회기동', '암사2동', '낙성대동', '독산1동', '개포4동', '성북동', '신원동', '청파동', '시흥1동', '도봉2동', '광희동', '이태원1동', '중곡3동', '자양1동', '약수동', '구로2동', '천호3동', '대치4동', '거여2동', '화곡4동', '사직동', '군자동', '방이2동', '이화동', '잠실3동', '쌍문2동', '독산4동', '남가좌2동', '오류1동', '대치2동', '금호2·3가동', '번2동', '당산1동', '인수동', '당산2동', '서초4동', '신정7동', '정릉2동', '신수동', '종로5·6가동', '용강동', '신월5동', '상봉1동', '압구정동', '청량리동', '수색동', '목2동', '석관동', '연희동', '천호1동', '수유1동', '여의동', '일원2동', '명일2동', '원효로2동', '둔촌1동', '미아동', '구의1동', '면목7동', '교남동', '신사동', '문래동', '문정1동', '정릉1동', '목3동', '남가좌1동', '역촌동', '숭인2동', '구로3동', '고척1동', '신길7동', '신대방2동', '신월7동', '갈현1동', '서초3동', '자양4동', '창2동', '을지로동', '방학3동', '길음2동', '중앙동', '이태원2동', '전농2동', '반포2동', '논현2동', '소공동', '상봉2동', '후암동', '연남동', '삼양동', '잠원동', '행운동', '번3동', '원효로1동', '사당4동', '등촌3동', '삼청동', '문정2동', '홍은1동', '중곡2동', '석촌동', '대방동', '구로5동', '왕십리도선동', '독산3동', '둔촌2동', '구의2동', '중계본동', '도림동', '한남동', '도화동', '송파2동', '염창동', '쌍문1동', '수유3동', '대림3동', '답십리2동', '잠실2동', '공항동', '마천1동', '고척2동', '성수1가2동', '신촌동', '개봉2동', '풍납1동', '장위3동', '상도1동', '신사1동', '신정3동', '화곡3동', '신당5동', '신정2동', '목4동', '대학동', '사당1동', '가산동', '고덕1동', '장충동', '가락본동', '양재1동', '용산2가동', '화곡2동', '양평1동', '증산동', '상계9동', '홍은2동', '암사3동', '수서동', '중계1동', '도봉1동', '신월3동', '번1동', '서교동', '충현동', '신월2동', '홍제2동', '목1동', '중화2동', '반포1동', '상계8동', '왕십리2동', '화양동', '성산2동', '방화3동', '반포본동', '신사2동', '신대방1동', '조원동', '창1동', '숭인1동', '면목2동', '구로4동', '신내2동', '창신3동', '장안2동', '한강로동', '가락1동', '삼성2동', '풍납2동', '이문2동', '사당5동', '신정6동', '상계10동', '망원1동', '장위1동', '가양3동', '망원2동', '갈현2동', '삼선동', '성수1가1동', '월곡1동', '시흥2동', '개봉1동', '구로1동', '삼성동', '인헌동', '자양2동'}

A에만 있는 값:
set()

B에만 있는 값:
set()

In [13]:
data_01.columns

Index(['기준_년분기_코드', '행정동_코드', '행정동_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '점포_수',
       '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')

서비스 명 통일작업

In [14]:
data_01['서비스_업종_코드_명'].unique()

array(['한식음식점', '중식음식점', '일식음식점', '양식음식점', '제과점', '패스트푸드점', '치킨전문점',
       '분식전문점', '호프-간이주점', '커피-음료', '일반교습학원', '외국어학원', '예술학원', '스포츠 강습',
       '일반의원', '치과의원', '한의원', '변호사사무소', '기타법무서비스', '세무사사무소', '당구장',
       '골프연습장', 'PC방', '전자게임장', '자동차수리', '자동차미용', '미용실', '네일숍', '피부관리실',
       '세탁소', '가전제품수리', '부동산중개업', '여관', '게스트하우스', '고시원', '노래방', '녹음실',
       '사진관', '통번역서비스', '건축물청소', '여행사', '비디오/서적임대', '의류임대', '슈퍼마켓', '편의점',
       '컴퓨터및주변장치판매', '핸드폰', '주류도매', '미곡판매', '육류판매', '수산물판매', '청과상',
       '반찬가게', '일반의류', '유아의류', '신발', '가방', '안경', '시계및귀금속', '의약품', '의료기기',
       '서적', '문구', '화장품', '미용재료', '운동/경기용품', '완구', '섬유제품', '화초', '애완동물',
       '가구', '가전제품', '철물점', '인테리어', '조명용품', '자동차부품', '모터사이클및부품',
       '재생용품 판매점', '예술품', '전자상거래업', '컴퓨터학원', '동물병원', '변리사사무소', '법무사사무소',
       '회계사사무소', '볼링장', '기타오락장', '복권방', '통신기기수리', '스포츠클럽', '독서실',
       '가정용품임대', '한복점', '악기', '주유소', 'DVD방', '모터사이클수리', '중고차판매',
       '자전거 및 기타운송장비', '중고가구'], dtype=object)