In [31]:
import pandas as pd

In [32]:
dong = pd.read_csv(r'D:\Work\project\project2\oos\data\거주인구\Resident_Population_Dong424.csv')

data = pd.read_csv('sales_2023,2024.csv')

In [33]:
data.info()
print('년분기 갯수 : ', data['기준_년분기_코드'].nunique())
print('업종명 갯수 : ', data['서비스_업종_코드_명'].nunique())
print('행정동 갯수 : ', data['행정동_코드_명'].nunique())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101139 entries, 0 to 101138
Data columns (total 53 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   기준_년분기_코드        101139 non-null  int64
 1   행정동_코드           101139 non-null  int64
 2   행정동_코드_명         101139 non-null  object
 3   서비스_업종_코드        101139 non-null  object
 4   서비스_업종_코드_명      101139 non-null  object
 5   당월_매출_금액         101139 non-null  int64
 6   당월_매출_건수         101139 non-null  int64
 7   주중_매출_금액         101139 non-null  int64
 8   주말_매출_금액         101139 non-null  int64
 9   월요일_매출_금액        101139 non-null  int64
 10  화요일_매출_금액        101139 non-null  int64
 11  수요일_매출_금액        101139 non-null  int64
 12  목요일_매출_금액        101139 non-null  int64
 13  금요일_매출_금액        101139 non-null  int64
 14  토요일_매출_금액        101139 non-null  int64
 15  일요일_매출_금액        101139 non-null  int64
 16  시간대_00~06_매출_금액  101139 non-null  int64
 17  시간대_06~11_매출_금액  101139 non-null  int64
 18  시간대_11~14_매출_금액  101139 non-null  int64
 19  시간대_14~17_매출_금액  101139 non-null  int64
 20  시간대_17~21_매출_금액  101139 non-null  int64
 21  시간대_21~24_매출_금액  101139 non-null  int64
 22  남성_매출_금액         101139 non-null  int64
 23  여성_매출_금액         101139 non-null  int64
 24  연령대_10_매출_금액     101139 non-null  int64
 25  연령대_20_매출_금액     101139 non-null  int64
 26  연령대_30_매출_금액     101139 non-null  int64
 27  연령대_40_매출_금액     101139 non-null  int64
 28  연령대_50_매출_금액     101139 non-null  int64
 29  연령대_60_이상_매출_금액  101139 non-null  int64
 30  주중_매출_건수         101139 non-null  int64
 31  주말_매출_건수         101139 non-null  int64
 32  월요일_매출_건수        101139 non-null  int64
 33  화요일_매출_건수        101139 non-null  int64
 34  수요일_매출_건수        101139 non-null  int64
 35  목요일_매출_건수        101139 non-null  int64
 36  금요일_매출_건수        101139 non-null  int64
 37  토요일_매출_건수        101139 non-null  int64
 38  일요일_매출_건수        101139 non-null  int64
 39  시간대_건수~06_매출_건수  101139 non-null  int64
 40  시간대_건수~11_매출_건수  101139 non-null  int64
 41  시간대_건수~14_매출_건수  101139 non-null  int64
 42  시간대_건수~17_매출_건수  101139 non-null  int64
 43  시간대_건수~21_매출_건수  101139 non-null  int64
 44  시간대_건수~24_매출_건수  101139 non-null  int64
 45  남성_매출_건수         101139 non-null  int64
 46  여성_매출_건수         101139 non-null  int64
 47  연령대_10_매출_건수     101139 non-null  int64
 48  연령대_20_매출_건수     101139 non-null  int64
 49  연령대_30_매출_건수     101139 non-null  int64
 50  연령대_40_매출_건수     101139 non-null  int64
 51  연령대_50_매출_건수     101139 non-null  int64
 52  연령대_60_이상_매출_건수  101139 non-null  int64
dtypes: int64(50), object(3)
memory usage: 40.9+ MB
년분기 갯수 :  6
업종명 갯수 :  63
행정동 갯수 :  423

In [34]:
col = ['기준_년분기_코드', '행정동_코드', '행정동_코드_명', '서비스_업종_코드_명',
       '당월_매출_금액', '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액',
       '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액',
       '일요일_매출_금액', '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
       '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액',
       '여성_매출_금액', '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액',
       '연령대_40_매출_금액', '연령대_50_매출_금액', '연령대_60_이상_매출_금액']

data = data[col]

In [35]:
col_name = ['년분기', '행정동_코드', '행정동', '업종명', '월매출',
       '주중매출', '주말매출', '월요일', '화요일', '수요일','목요일', '금요일', '토요일', '일요일',
       '0006','0611', '1114', '1417', '1721', '2124',
       '남성', '여성',
       'Age_10', 'Age_20', 'Age_30', 'Age_40','Age_50', 'Age_60_to_end']

data.columns = col_name

In [36]:
set_a = set(data['행정동'])
set_b = set(dong['동별'])
common_values = set_a & set_b  # A와 B에 모두 있는 값
only_in_a = set_a - set_b  # A에만 있는 값
only_in_b = set_b - set_a  # B에만 있는 값

# 결과 출력
print("A와 B에 모두 있는 값:")
print(common_values)

print("\nA에만 있는 값:")
print(only_in_a)

print("\nB에만 있는 값:")
print(only_in_b)

A와 B에 모두 있는 값:
{'정릉1동', '금호4가동', '신정1동', '신월4동', '동선동', '방학1동', '역삼1동', '석관동', '수색동', '월곡1동', '신길4동', '화곡2동', '삼성2동', '성수1가2동', '보광동', '잠실3동', '보문동', '방학2동', '암사1동', '등촌2동', '신수동', '방배1동', '독산2동', '방배4동', '북가좌2동', '마천1동', '영등포동', '대치4동', '방학3동', '화양동', '안암동', '홍제1동', '원효로2동', '압구정동', '광장동', '전농1동', '중화1동', '휘경1동', '길음1동', '신길3동', '은천동', '부암동', '녹번동', '성수2가3동', '휘경2동', '대림3동', '신대방2동', '화곡3동', '개봉2동', '수유3동', '상암동', '연희동', '천호1동', '소공동', '개포4동', '용답동', '천호2동', '동화동', '증산동', '거여2동', '논현2동', '도곡1동', '가양1동', '홍제3동', '방배2동', '대학동', '남현동', '홍은2동', '구로4동', '도화동', '인헌동', '도곡2동', '진관동', '대림2동', '제기동', '이태원1동', '수유1동', '길음2동', '신길6동', '충현동', '노량진2동', '쌍문3동', '시흥2동', '망원1동', '갈현1동', '이문1동', '구의2동', '화곡8동', '양평1동', '신사1동', '신월5동', '잠실본동', '망원2동', '자양2동', '서초2동', '등촌3동', '인수동', '면목본동', '망우본동', '필동', '삼양동', '상계10동', '조원동', '낙성대동', '마장동', '이화동', '구로5동', '청담동', '사근동', '쌍문2동', '성수1가1동', '풍납2동', '월곡2동', '화곡본동', '발산1동', '수궁동', '장위2동', '창2동', '사당4동', '가회동', '아현동', '연남동', '가산동', '고덕2동', '면목7동', '신원동', '수유2동', '서교동', '상봉1동', '삼성1동', '이태원2동', '가양2동', '명동', '개봉1동', '신길5동', '응암3동', '삼각산동', '구로3동', '노량진1동', '개포2동', '방화3동', '목4동', '중화2동', '청룡동', '월계1동', '다산동', '명일2동', '거여1동', '성산2동', '청파동', '남영동', '창4동', '문정2동', '신정6동', '신월1동', '서강동', '대조동', '서원동', '오류2동', '구로1동', '서초1동', '자양4동', '북아현동', '우장산동', '위례동', '방배본동', '신길7동', '답십리1동', '황학동', '면목2동', '번1동', '반포2동', '세곡동', '망우3동', '장위1동', '회기동', '대림1동', '목3동', '서초4동', '천호3동', '하계2동', '합정동', '우이동', '상도4동', '성내2동', '서빙고동', '용문동', '장안2동', '교남동', '창3동', '구의1동', '반포본동', '이문2동', '신대방1동', '전농2동', '송정동', '중곡4동', '신월7동', '오금동', '한남동', '광희동', '시흥4동', '금호1가동', '개봉3동', '시흥1동', '상계1동', '창5동', '화곡6동', '성수2가1동', '문정1동', '회현동', '청림동', '도봉2동', '창신1동', '갈현2동', '능동', '천연동', '이촌2동', '응암2동', '창신3동', '옥수동', '답십리2동', '월계2동', '창1동', '미아동', '구산동', '양평2동', '일원1동', '성내1동', '상계2동', '종암동', '송파2동', '반포4동', '시흥5동', '불광2동', '중곡1동', '중계1동', '신정2동', '개포1동', '방배3동', '신월3동', '쌍문4동', '길동', '가락1동', '고척2동', '후암동', '약수동', '암사3동', '하계1동', '당산1동', '왕십리2동', '사직동', '가락2동', '신사동', '신당동', '신촌동', '여의동', '가락본동', '중곡3동', '상계9동', '면목5동', '미성동', '목2동', '불광1동', '사당5동', '서림동', '홍제2동', '신사2동', '독산3동', '구로2동', '방이2동', '남가좌1동', '가리봉동', '고척1동', '고덕1동', '시흥3동', '오류1동', '북가좌1동', '자양3동', '사당1동', '오륜동', '무악동', '삼선동', '삼전동', '번2동', '화곡1동', '상도1동', '명일1동', '보라매동', '송파1동', '자양1동', '쌍문1동', '성산1동', '상봉2동', '염창동', '응봉동', '당산2동', '창신2동', '수서동', '남가좌2동', '잠원동', '돈암2동', '장안1동', '구의3동', '장위3동', '목5동', '잠실2동', '상도2동', '신월6동', '영등포본동', '도림동', '중곡2동', '신월2동', '등촌1동', '목1동', '서초3동', '문래동', '홍은1동', '역촌동', '장충동', '화곡4동', '양재1동', '군자동', '공릉2동', '양재2동', '혜화동', '사당2동', '풍납1동', '중계본동', '응암1동', '왕십리도선동', '난곡동', '정릉3동', '원효로1동', '용산2가동', '암사2동', '일원2동', '숭인2동', '도봉1동', '용신동', '잠실6동', '신내1동', '성현동', '묵1동', '한강로동', '묵2동', '독산1동', '흑석동', '행당2동', '공덕동', '을지로동', '청구동', '상계5동', '삼청동', '난향동', '성내3동', '석촌동', '일원본동', '신정4동', '반포3동', '잠실7동', '숭인1동', '독산4동', '역삼2동', '신정3동', '청량리동', '대흥동', '청운효자동', '상일동', '강일동', '상계8동', '행당1동', '내곡동', '평창동', '돈암1동', '둔촌2동', '이촌1동', '신정7동', '대방동', '반포1동', '월계3동', '중앙동', '면목4동', '장지동', '효창동', '송중동', '방화1동', '상도3동', '신길1동', '공릉1동', '행운동', '논현1동', '용강동', '가양3동', '대치1동', '성북동', '신림동', '번3동', '신당5동', '신내2동', '마천2동', '사당3동', '중계4동', '정릉2동', '방화2동', '정릉4동', '방이1동', '신도림동', '삼성동', '공항동', '대치2동', '중림동', '송천동', '염리동', '잠실4동'}

A에만 있는 값:
{'항동', '면목3?8동', '종로5?6가동', '중계2?3동', '상계6?7동', '금호2?3가동', '상계3?4동', '종로1?2?3?4가동'}

B에만 있는 값:
{'중계2·3동', '종로1·2·3·4가동', '면목3·8동', '종로5·6가동', '상계6·7동', '관악구 신사동', '상계3·4동', '금호2·3가동', '둔촌1동'}

In [37]:
data['행정동'] = data['행정동'].str.replace('?', '·', regex=False)

In [38]:
data.loc[data['행정동_코드'] == 11620685, '행정동'] = '관악구 신사동'
data.loc[data['행정동'] == '항동', '행정동'] = '오류2동'

In [39]:
set_a = set(data['행정동'])
set_b = set(dong['동별'])
common_values = set_a & set_b  # A와 B에 모두 있는 값
only_in_a = set_a - set_b  # A에만 있는 값
only_in_b = set_b - set_a  # B에만 있는 값

# 결과 출력
print("A와 B에 모두 있는 값:")
print(common_values)

print("\nA에만 있는 값:")
print(only_in_a)

print("\nB에만 있는 값:")
print(only_in_b)

A와 B에 모두 있는 값:
{'정릉1동', '금호4가동', '신정1동', '신월4동', '동선동', '방학1동', '역삼1동', '석관동', '수색동', '월곡1동', '신길4동', '화곡2동', '삼성2동', '성수1가2동', '보광동', '잠실3동', '보문동', '방학2동', '암사1동', '등촌2동', '신수동', '방배1동', '독산2동', '방배4동', '북가좌2동', '마천1동', '영등포동', '대치4동', '방학3동', '화양동', '안암동', '홍제1동', '원효로2동', '압구정동', '광장동', '전농1동', '중화1동', '휘경1동', '길음1동', '신길3동', '은천동', '부암동', '녹번동', '종로5·6가동', '성수2가3동', '휘경2동', '대림3동', '신대방2동', '화곡3동', '개봉2동', '수유3동', '상암동', '연희동', '천호1동', '소공동', '개포4동', '용답동', '천호2동', '동화동', '증산동', '거여2동', '논현2동', '도곡1동', '가양1동', '홍제3동', '방배2동', '대학동', '남현동', '홍은2동', '구로4동', '도화동', '인헌동', '도곡2동', '진관동', '대림2동', '제기동', '이태원1동', '면목3·8동', '수유1동', '길음2동', '신길6동', '충현동', '노량진2동', '쌍문3동', '시흥2동', '망원1동', '갈현1동', '이문1동', '구의2동', '화곡8동', '양평1동', '신사1동', '신월5동', '잠실본동', '망원2동', '자양2동', '서초2동', '등촌3동', '인수동', '면목본동', '망우본동', '필동', '삼양동', '상계10동', '조원동', '낙성대동', '마장동', '이화동', '구로5동', '청담동', '사근동', '쌍문2동', '성수1가1동', '풍납2동', '월곡2동', '화곡본동', '발산1동', '수궁동', '장위2동', '창2동', '사당4동', '가회동', '아현동', '연남동', '가산동', '고덕2동', '면목7동', '신원동', '수유2동', '서교동', '상봉1동', '삼성1동', '이태원2동', '가양2동', '명동', '개봉1동', '신길5동', '응암3동', '삼각산동', '구로3동', '노량진1동', '개포2동', '방화3동', '목4동', '중화2동', '청룡동', '월계1동', '다산동', '명일2동', '거여1동', '성산2동', '청파동', '남영동', '창4동', '문정2동', '신정6동', '신월1동', '서강동', '대조동', '서원동', '상계3·4동', '오류2동', '구로1동', '서초1동', '자양4동', '북아현동', '우장산동', '위례동', '방배본동', '신길7동', '답십리1동', '황학동', '면목2동', '번1동', '반포2동', '세곡동', '망우3동', '장위1동', '회기동', '대림1동', '목3동', '서초4동', '천호3동', '하계2동', '합정동', '우이동', '상도4동', '성내2동', '서빙고동', '용문동', '장안2동', '교남동', '창3동', '구의1동', '반포본동', '이문2동', '신대방1동', '전농2동', '송정동', '중곡4동', '신월7동', '종로1·2·3·4가동', '오금동', '한남동', '광희동', '시흥4동', '금호1가동', '개봉3동', '시흥1동', '상계1동', '창5동', '화곡6동', '성수2가1동', '문정1동', '회현동', '청림동', '도봉2동', '창신1동', '갈현2동', '능동', '천연동', '이촌2동', '응암2동', '창신3동', '옥수동', '답십리2동', '월계2동', '창1동', '미아동', '구산동', '양평2동', '일원1동', '성내1동', '금호2·3가동', '상계2동', '종암동', '송파2동', '반포4동', '시흥5동', '불광2동', '중곡1동', '중계1동', '신정2동', '개포1동', '방배3동', '신월3동', '쌍문4동', '길동', '가락1동', '고척2동', '후암동', '약수동', '암사3동', '하계1동', '당산1동', '왕십리2동', '사직동', '가락2동', '신사동', '신당동', '신촌동', '여의동', '가락본동', '중곡3동', '상계9동', '면목5동', '미성동', '목2동', '불광1동', '사당5동', '서림동', '홍제2동', '신사2동', '상계6·7동', '독산3동', '구로2동', '방이2동', '남가좌1동', '가리봉동', '고척1동', '고덕1동', '시흥3동', '오류1동', '북가좌1동', '자양3동', '사당1동', '오륜동', '무악동', '삼선동', '관악구 신사동', '삼전동', '번2동', '화곡1동', '상도1동', '명일1동', '보라매동', '송파1동', '자양1동', '쌍문1동', '성산1동', '상봉2동', '염창동', '응봉동', '당산2동', '창신2동', '수서동', '남가좌2동', '잠원동', '돈암2동', '장안1동', '구의3동', '장위3동', '목5동', '잠실2동', '상도2동', '신월6동', '영등포본동', '도림동', '중곡2동', '신월2동', '등촌1동', '목1동', '서초3동', '문래동', '홍은1동', '역촌동', '장충동', '화곡4동', '양재1동', '군자동', '공릉2동', '양재2동', '혜화동', '사당2동', '풍납1동', '중계2·3동', '중계본동', '응암1동', '왕십리도선동', '난곡동', '정릉3동', '원효로1동', '용산2가동', '암사2동', '일원2동', '숭인2동', '도봉1동', '용신동', '잠실6동', '신내1동', '성현동', '묵1동', '한강로동', '묵2동', '독산1동', '흑석동', '행당2동', '공덕동', '을지로동', '청구동', '상계5동', '삼청동', '난향동', '성내3동', '석촌동', '일원본동', '신정4동', '반포3동', '잠실7동', '숭인1동', '독산4동', '역삼2동', '신정3동', '청량리동', '대흥동', '청운효자동', '상일동', '강일동', '상계8동', '행당1동', '내곡동', '평창동', '돈암1동', '둔촌2동', '이촌1동', '신정7동', '대방동', '반포1동', '월계3동', '중앙동', '면목4동', '장지동', '효창동', '송중동', '방화1동', '상도3동', '신길1동', '공릉1동', '행운동', '논현1동', '용강동', '가양3동', '대치1동', '성북동', '신림동', '번3동', '신당5동', '신내2동', '마천2동', '사당3동', '중계4동', '정릉2동', '방화2동', '정릉4동', '방이1동', '신도림동', '삼성동', '공항동', '대치2동', '중림동', '송천동', '염리동', '잠실4동'}

A에만 있는 값:
set()

B에만 있는 값:
{'둔촌1동'}

In [40]:
dong_check = data[data['행정동'].str.contains('^둔촌', na=False)]
dong_check['행정동'].unique()

array(['둔촌2동'], dtype=object)