In [54]:
import pandas as pd
import numpy as np
import my_def

<h1>데이터확인 및 가공</h1>
업종명 분류 -> 9개의 중분류로 구분

In [55]:
df = pd.read_csv('Merged_Sales_data_v2.6(selected_store).csv')

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335256 entries, 0 to 335255
Data columns (total 13 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   년분기        335256 non-null  int64
 1   행정동        335256 non-null  object
 2   업종명        335256 non-null  object
 3   월매출(점포)    335256 non-null  int64
 4   인구수        335256 non-null  int64
 5   지역생활인구     335256 non-null  int64
 6   장기외국인      335256 non-null  int64
 7   단기외국인      335256 non-null  int64
 8   주차장면적(면)   335256 non-null  int64
 9   주차장개수(개소)  335256 non-null  int64
 10  학교수        335256 non-null  int64
 11  학생수        335256 non-null  int64
 12  버스정류장수     335256 non-null  int64
dtypes: int64(11), object(2)
memory usage: 33.3+ MB

In [57]:
categories = {
    "식음료": [
        "커피-음료", "패스트푸드점", "분식전문점", "한식음식점",
        "양식음식점", "일식음식점", "호프-간이주점", "제과점", "중식음식점"
    ],
    "의료_건강": [
        "의약품", "치과의원", "일반의원", "한의원", "피부관리실", "의료기기"
    ],
    "소매_편의": [
        "미곡판매", "편의점", "슈퍼마켓", "반찬가게", "육류판매",
        "수산물판매", "문구", "청과상"
    ],
    "미용_패션": [
        "미용실", "화장품", "네일숍", "신발", "일반의류"
    ],
    "교육_학원": [
        "스포츠 강습", "예술학원", "외국어학원"
    ],
    "취미_레저": [
        "스포츠클럽", "골프연습장", "완구", "당구장", "노래방",
        "운동/경기용품", "자전거 및 기타운송장비", "서적"
    ],
    "생활서비스": [
        "세탁소", "철물점", "안경", "인테리어", "자동차미용", "자동차수리",
        "가전제품수리", "조명용품", "섬유제품", "전자상거래업"
    ],
    "가구_전자기기": [
        "가구", "가전제품", "핸드폰", "시계및귀금속", "컴퓨터및주변장치판매", "가방"
    ],
    "부동산_숙박": [
        "부동산중개업", "고시원"
    ]
}

In [58]:
def categorize_merged_data(merged_data):
    for category, biz_list in categories.items():
        if merged_data in biz_list:
            return category
    return "기타"

In [59]:
df['업종별카테고리'] = df['업종명'].apply(categorize_merged_data)
df.head(1)

,년분기,행정동,업종명,월매출(점포),인구수,지역생활인구,장기외국인,단기외국인,주차장면적(면),주차장개수(개소),학교수,학생수,버스정류장수,업종별카테고리
0,20191,가락1동,미곡판매,2796909658,20186,523724,13892,1772,20942,83,3,1586,14,소매_편의

In [60]:
grouped_df = df.groupby(['년분기', '행정동', '업종별카테고리']).agg({
    '월매출(점포)': 'sum',
    # '주중매출': 'sum',
    # '주말매출': 'sum',
    # '점포수': 'sum',
    '인구수' : 'mean',
    '지역생활인구': 'mean',
    '장기외국인': 'mean',
    '단기외국인': 'mean',
    '주차장면적(면)': 'mean',
    '주차장개수(개소)': 'mean',
    '학교수': 'mean',
    '학생수': 'mean',
    '버스정류장수': 'mean'	
}).reset_index()

grouped_df

,년분기,행정동,업종별카테고리,월매출(점포),인구수,지역생활인구,장기외국인,단기외국인,주차장면적(면),주차장개수(개소),학교수,학생수,버스정류장수
0,20191,가락1동,생활서비스,3975118,20186.00,523724.00,13892.00,1772.00,20942.00,83.00,3.00,1586.00,14.00
1,20191,가락1동,소매_편의,6565196464,20186.00,523724.00,13892.00,1772.00,20942.00,83.00,3.00,1586.00,14.00
2,20191,가락1동,식음료,404795979,20186.00,523724.00,13892.00,1772.00,20942.00,83.00,3.00,1586.00,14.00
3,20191,가락1동,의료_건강,170057995,20186.00,523724.00,13892.00,1772.00,20942.00,83.00,3.00,1586.00,14.00
4,20191,가락2동,가구_전자기기,10626421,34155.00,722081.00,8185.00,1925.00,14340.00,1058.00,2.00,1867.00,26.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72365,20242,흑석동,생활서비스,52455262,32491.00,848734.00,77201.00,6202.00,16937.00,298.00,0.00,0.00,59.00
72366,20242,흑석동,소매_편의,460400862,32491.00,848734.00,77201.00,6202.00,16937.00,298.00,0.00,0.00,59.00
72367,20242,흑석동,식음료,331108691,32491.00,848734.00,77201.00,6202.00,16937.00,298.00,0.00,0.00,59.00
72368,20242,흑석동,의료_건강,963794015,32491.00,848734.00,77201.00,6202.00,16937.00,298.00,0.00,0.00,59.00
72369,20242,흑석동,취미_레저,24619516,32491.00,848734.00,77201.00,6202.00,16937.00,298.00,0.00,0.00,59.00

In [61]:
#df = df.drop(["행정동_코드", "주중매출", "주말매출"], axis= 1)

In [62]:
grouped_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72370 entries, 0 to 72369
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   년분기        72370 non-null  int64
 1   행정동        72370 non-null  object
 2   업종별카테고리    72370 non-null  object
 3   월매출(점포)    72370 non-null  int64
 4   인구수        72370 non-null  float64
 5   지역생활인구     72370 non-null  float64
 6   장기외국인      72370 non-null  float64
 7   단기외국인      72370 non-null  float64
 8   주차장면적(면)   72370 non-null  float64
 9   주차장개수(개소)  72370 non-null  float64
 10  학교수        72370 non-null  float64
 11  학생수        72370 non-null  float64
 12  버스정류장수     72370 non-null  float64
dtypes: float64(9), int64(2), object(2)
memory usage: 7.2+ MB

In [63]:
grouped_df = my_def.reduce_memory_usage(grouped_df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72370 entries, 0 to 72369
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   년분기        72370 non-null  int16
 1   행정동        72370 non-null  object
 2   업종별카테고리    72370 non-null  object
 3   월매출(점포)    72370 non-null  int64
 4   인구수        72370 non-null  float16
 5   지역생활인구     72370 non-null  float32
 6   장기외국인      72370 non-null  float32
 7   단기외국인      72370 non-null  float32
 8   주차장면적(면)   72370 non-null  float32
 9   주차장개수(개소)  72370 non-null  float16
 10  학교수        72370 non-null  float16
 11  학생수        72370 non-null  float16
 12  버스정류장수     72370 non-null  float16
dtypes: float16(5), float32(4), int16(1), int64(1), object(2)
memory usage: 3.6+ MB
None

In [64]:
df[df["업종별카테고리"] == "기타"]

Empty DataFrame
Columns: [년분기, 행정동, 업종명, 월매출(점포), 인구수, 지역생활인구, 장기외국인, 단기외국인, 주차장면적(면), 주차장개수(개소), 학교수, 학생수, 버스정류장수, 업종별카테고리]
Index: []

<h1>업종별카테고리 선형회귀 모델</h1>
Polynomial Features & Standard Scaler 사용 안함<br>
9개 카테고리를 개별로해서 데이터프레임 형태로 저장

In [65]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [66]:
df = grouped_df

In [67]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pandas as pd


# 업종명 고유값 추출
unique_categories = df["업종별카테고리"].unique()

# 결과를 저장할 딕셔너리 생성
results = {}

# 각 업종별로 데이터를 나누어 모델 학습 및 예측 수행
for category in unique_categories:
    # 업종별 데이터 필터링
    df_category = df[df['업종별카테고리'] == category]
    
    # 원핫인코딩 수행
    df_category = pd.get_dummies(df_category, columns=['행정동'], drop_first=True)
    
    # 피처와 타겟 설정
    features = ['년분기', '인구수', '지역생활인구', '장기외국인', '단기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '학생수', '버스정류장수'] + [col for col in df_category.columns if col.startswith('행정동_')]
    target = '월매출(점포)'
    
    # 피처와 타겟 데이터 분리
    X = df_category[features]
    y = df_category[target]
    
    # 학습 데이터와 테스트 데이터 분리
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # 선형 회귀 모델 학습
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    # 성능 평가 호출
    evaluation_result = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)
    
    # 결과 저장
    if evaluation_result is not None:
        results[category] = evaluation_result

# 결과를 데이터프레임으로 변환
results_df = pd.DataFrame.from_dict(results, orient='index')
results_df = results_df.apply(pd.to_numeric)

# test_mae_ratio의 최고, 최저, 평균 추가
test_mae_ratio_max = results_df['test_mae_ratio'].max()
test_mae_ratio_min = results_df['test_mae_ratio'].min()
test_mae_ratio_mean = results_df['test_mae_ratio'].mean()

# 모든 행에 공통으로 최고, 최저, 평균 추가
test_mae_summary = {
    'test_mae_ratio_max': test_mae_ratio_max,
    'test_mae_ratio_min': test_mae_ratio_min,
    'test_mae_ratio_mean': test_mae_ratio_mean
}

for key, value in test_mae_summary.items():
    results_df[key] = value

# 결과를 소수점 2자리로 포맷팅하여 출력
pd.options.display.float_format = '{:.2f}'.format
results_df.iloc[:,4:].sort_values(by="test_mae_ratio")

,train_r2,test_r2,train_mae,test_mae,train_mae_ratio,test_mae_ratio,test_mae_ratio_max,test_mae_ratio_min,test_mae_ratio_mean
의료_건강,0.89,0.86,65831478.81,68563335.25,12.99,14.24,51.73,14.24,28.85
식음료,0.90,0.87,37618281.55,38377084.10,15.49,16.07,51.73,14.24,28.85
생활서비스,0.87,0.84,30718277.08,32138815.32,20.50,22.05,51.73,14.24,28.85
소매_편의,0.58,0.39,87847351.74,102653909.79,19.57,22.24,51.73,14.24,28.85
미용_패션,0.88,0.88,21884108.01,21239793.50,24.74,24.92,51.73,14.24,28.85
교육_학원,0.81,0.79,11538555.11,12073224.24,29.47,30.91,51.73,14.24,28.85
취미_레저,0.89,0.87,40492318.26,39659249.49,32.39,36.40,51.73,14.24,28.85
가구_전자기기,0.85,0.81,39063167.87,42332003.36,36.75,41.12,51.73,14.24,28.85
부동산_숙박,0.89,0.89,4973988.37,6274025.45,44.76,51.73,51.73,14.24,28.85

In [68]:
result = my_def.linear_category_model(df)
result

AttributeError: module 'my_def' has no attribute 'linear_category_model'

<h1>선형회귀 - Standard Scaler 적용</h1>

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import pandas as pd


# 업종명 고유값 추출
unique_categories = df["업종별카테고리"].unique()

# 결과를 저장할 딕셔너리 생성
results = {}

# 각 업종별로 데이터를 나누어 모델 학습 및 예측 수행
for category in unique_categories:
    # 업종별 데이터 필터링
    df_category = df[df['업종별카테고리'] == category]
    
    # 원핫인코딩 수행
    df_category = pd.get_dummies(df_category, columns=['행정동'], drop_first=True)
    
    # 피처와 타겟 설정
    features = ['년분기', '인구수', '지역생활인구', '장기외국인', '단기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '학생수', '버스정류장수'] + [col for col in df_category.columns if col.startswith('행정동_')]
    target = '월매출(점포)'
    
    # 피처와 타겟 데이터 분리
    X = df_category[features]
    y = df_category[target]
    
    # Standard Scaler 적용
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    # 학습 데이터와 테스트 데이터 분리
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
    
    # 선형 회귀 모델 학습
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    # 성능 평가 호출
    evaluation_result = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)
    
    # 결과 저장
    if evaluation_result is not None:
        results[category] = evaluation_result

# 결과를 데이터프레임으로 변환
results_df = pd.DataFrame.from_dict(results, orient='index')
results_df = results_df.apply(pd.to_numeric)

# test_mae_ratio의 최고, 최저, 평균 추가
test_mae_ratio_max = results_df['test_mae_ratio'].max()
test_mae_ratio_min = results_df['test_mae_ratio'].min()
test_mae_ratio_mean = results_df['test_mae_ratio'].mean()

# 모든 행에 공통으로 최고, 최저, 평균 추가
test_mae_summary = {
    'test_mae_ratio_max': test_mae_ratio_max,
    'test_mae_ratio_min': test_mae_ratio_min,
    'test_mae_ratio_mean': test_mae_ratio_mean
}

for key, value in test_mae_summary.items():
    results_df[key] = value

# 결과를 소수점 2자리로 포맷팅하여 출력
pd.options.display.float_format = '{:.2f}'.format

# test_mae_ratio로 정렬
results_df_sorted = results_df.sort_values(by="test_mae_ratio")

# 결과 출력
results_df.iloc[:,4:].sort_values(by="test_mae_ratio")

,train_r2,test_r2,train_mae,test_mae,train_mae_ratio,test_mae_ratio,test_mae_ratio_max,test_mae_ratio_min,test_mae_ratio_mean
의료_건강,0.90,0.87,61375116.79,63967202.57,12.11,13.28,88727.29,13.28,9878.82
식음료,0.90,0.88,35274752.10,36030482.92,14.52,15.08,88727.29,13.28,9878.82
소매_편의,0.91,0.92,67513819.08,72971707.10,15.04,15.81,88727.29,13.28,9878.82
생활서비스,0.88,0.85,28391240.56,29677954.83,18.95,20.36,88727.29,13.28,9878.82
미용_패션,0.89,0.89,18533845.43,17652177.47,20.95,20.71,88727.29,13.28,9878.82
교육_학원,0.83,0.81,10582407.30,11134260.19,27.03,28.51,88727.29,13.28,9878.82
취미_레저,0.90,0.87,33765855.44,32879439.94,27.01,30.18,88727.29,13.28,9878.82
가구_전자기기,0.86,0.75,35170373.75,39279334.03,33.09,38.16,88727.29,13.28,9878.82
부동산_숙박,0.91,-9608290.00,3786829.41,10762206872.16,34.08,88727.29,88727.29,13.28,9878.82

<h1>선형회귀 - Min-Max Scaler 적용</h1>

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
import pandas as pd


# 업종명 고유값 추출
unique_categories = df["업종별카테고리"].unique()

# 결과를 저장할 딕셔너리 생성
results = {}

# 각 업종별로 데이터를 나누어 모델 학습 및 예측 수행
for category in unique_categories:
    # 업종별 데이터 필터링
    df_category = df[df['업종별카테고리'] == category]
    
    # 원핫인코딩 수행
    df_category = pd.get_dummies(df_category, columns=['행정동'], drop_first=True)
    
    # 피처와 타겟 설정
    features = ['년분기', '인구수', '지역생활인구', '장기외국인', '단기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '학생수', '버스정류장수'] + [col for col in df_category.columns if col.startswith('행정동_')]
    target = '월매출(점포)'
    
    # 피처와 타겟 데이터 분리
    X = df_category[features]
    y = df_category[target]
    
    # Min-Max Scaler 적용
    scaler = MinMaxScaler()
    X_scaled = scaler.fit_transform(X)
    
    # 학습 데이터와 테스트 데이터 분리
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
    
    # 선형 회귀 모델 학습
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    # 성능 평가 호출
    evaluation_result = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)
    
    # 결과 저장
    if evaluation_result is not None:
        results[category] = evaluation_result

# 결과를 데이터프레임으로 변환
results_df = pd.DataFrame.from_dict(results, orient='index')
results_df = results_df.apply(pd.to_numeric)

# test_mae_ratio의 최고, 최저, 평균 추가
test_mae_ratio_max = results_df['test_mae_ratio'].max()
test_mae_ratio_min = results_df['test_mae_ratio'].min()
test_mae_ratio_mean = results_df['test_mae_ratio'].mean()

# 모든 행에 공통으로 최고, 최저, 평균 추가
test_mae_summary = {
    'test_mae_ratio_max': test_mae_ratio_max,
    'test_mae_ratio_min': test_mae_ratio_min,
    'test_mae_ratio_mean': test_mae_ratio_mean
}

for key, value in test_mae_summary.items():
    results_df[key] = value

# 결과를 소수점 2자리로 포맷팅하여 출력
pd.options.display.float_format = '{:.2f}'.format

# test_mae_ratio로 정렬
results_df_sorted = results_df.sort_values(by="test_mae_ratio")

# 결과 출력
results_df.iloc[:,4:].sort_values(by="test_mae_ratio")

,train_r2,test_r2,train_mae,test_mae,train_mae_ratio,test_mae_ratio,test_mae_ratio_max,test_mae_ratio_min,test_mae_ratio_mean
의료_건강,0.90,0.87,61374957.12,63966989.75,12.11,13.28,43.39,13.28,24.92
식음료,0.90,0.88,35274679.94,36030324.71,14.52,15.08,43.39,13.28,24.92
소매_편의,0.91,0.92,67514795.80,72972417.48,15.04,15.81,43.39,13.28,24.92
생활서비스,0.88,0.85,28391337.52,29678050.21,18.95,20.36,43.39,13.28,24.92
미용_패션,0.89,0.89,18533839.25,17652188.30,20.95,20.71,43.39,13.28,24.92
교육_학원,0.83,0.81,10582428.47,11134286.46,27.03,28.51,43.39,13.28,24.92
취미_레저,0.90,0.87,33765913.15,32879592.57,27.01,30.18,43.39,13.28,24.92
가구_전자기기,0.86,0.82,35170481.21,38053044.14,33.09,36.97,43.39,13.28,24.92
부동산_숙박,0.91,0.89,3786581.53,5262682.51,34.07,43.39,43.39,13.28,24.92

<h1>업종별카테고리 랜덤포레스트 모델</h1>
Polynomial Features & Standard Scaler 사용 안함<br>
9개 카테고리를 개별로해서 데이터프레임 형태로 저장

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import pandas as pd

# 업종명 고유값 추출
unique_categories = df["업종별카테고리"].unique()

# 결과를 저장할 딕셔너리 생성
results = {}

# 각 업종별로 데이터를 나누어 모델 학습 및 예측 수행
for category in unique_categories:
    # 업종별 데이터 필터링
    df_category = df[df['업종별카테고리'] == category]
    
    # 원핫인코딩 수행
    df_category = pd.get_dummies(df_category, columns=['행정동'], drop_first=True)
    
    # 피처와 타겟 설정
    features = ['년분기', '인구수', '지역생활인구', '장기외국인', '단기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '학생수', '버스정류장수'] + [col for col in df_category.columns if col.startswith('행정동_')]
    target = '월매출(점포)'
    
    # 피처와 타겟 데이터 분리
    X = df_category[features]
    y = df_category[target]
    
    # 학습 데이터와 테스트 데이터 분리
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # 랜덤 포레스트 회귀 모델 학습
    model = RandomForestRegressor(random_state=42)
    model.fit(X_train, y_train)
    
    # 성능 평가 호출
    evaluation_result = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)
    
    # 결과 저장
    if evaluation_result is not None:
        results[category] = evaluation_result

# 결과를 데이터프레임으로 변환
results_df = pd.DataFrame.from_dict(results, orient='index')
results_df = results_df.apply(pd.to_numeric)

# test_mae_ratio의 최고, 최저, 평균 추가
test_mae_ratio_max = results_df['test_mae_ratio'].max()
test_mae_ratio_min = results_df['test_mae_ratio'].min()
test_mae_ratio_mean = results_df['test_mae_ratio'].mean()

# 모든 행에 공통으로 최고, 최저, 평균 추가
test_mae_summary = {
    'test_mae_ratio_max': test_mae_ratio_max,
    'test_mae_ratio_min': test_mae_ratio_min,
    'test_mae_ratio_mean': test_mae_ratio_mean
}

for key, value in test_mae_summary.items():
    results_df[key] = value

# 결과를 소수점 2자리로 포맷팅하여 출력
pd.options.display.float_format = '{:.2f}'.format
results_df.iloc[:,4:].sort_values(by="test_mae_ratio")

,train_r2,test_r2,train_mae,test_mae,train_mae_ratio,test_mae_ratio,test_mae_ratio_max,test_mae_ratio_min,test_mae_ratio_mean
식음료,0.99,0.95,8885904.84,23148990.74,3.66,9.69,30.01,9.69,18.53
의료_건강,0.99,0.92,18769319.01,49234555.08,3.70,10.22,30.01,9.69,18.53
소매_편의,0.99,0.93,19039644.86,52735225.80,4.24,11.43,30.01,9.69,18.53
미용_패션,0.99,0.95,5117091.34,12818820.90,5.78,15.04,30.01,9.69,18.53
교육_학원,0.99,0.91,2739382.65,7125945.34,7.00,18.24,30.01,9.69,18.53
생활서비스,0.99,0.86,9250704.47,26613611.91,6.17,18.26,30.01,9.69,18.53
취미_레저,0.98,0.92,11064078.22,26072810.81,8.85,23.93,30.01,9.69,18.53
가구_전자기기,0.99,0.87,11154921.06,30784492.36,10.50,29.91,30.01,9.69,18.53
부동산_숙박,0.99,0.93,1283412.56,3640508.32,11.55,30.01,30.01,9.69,18.53

<h1>랜덤포레스트 모델 - Standard scaler</h1>

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
import pandas as pd

# 업종명 고유값 추출
unique_categories = df["업종별카테고리"].unique()

# 결과를 저장할 딕셔너리 생성
results = {}

# 각 업종별로 데이터를 나누어 모델 학습 및 예측 수행
for category in unique_categories:
    # 업종별 데이터 필터링
    df_category = df[df['업종별카테고리'] == category]
    
    # 원핫인코딩 수행
    df_category = pd.get_dummies(df_category, columns=['행정동'], drop_first=True)
    
    # 피처와 타겟 설정
    features = ['년분기', '인구수', '지역생활인구', '장기외국인', '단기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '학생수', '버스정류장수'] + [col for col in df_category.columns if col.startswith('행정동_')]
    target = '월매출(점포)'
    
    # 피처와 타겟 데이터 분리
    X = df_category[features]
    y = df_category[target]
    
    # Standard Scaler 적용
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    # 학습 데이터와 테스트 데이터 분리
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
    
    # 랜덤 포레스트 회귀 모델 학습
    model = RandomForestRegressor(random_state=42)
    model.fit(X_train, y_train)
    
    # 성능 평가 호출
    evaluation_result = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)
    
    # 결과 저장
    if evaluation_result is not None:
        results[category] = evaluation_result

# 결과를 데이터프레임으로 변환
results_df = pd.DataFrame.from_dict(results, orient='index')
results_df = results_df.apply(pd.to_numeric)

# test_mae_ratio의 최고, 최저, 평균 추가
test_mae_ratio_max = results_df['test_mae_ratio'].max()
test_mae_ratio_min = results_df['test_mae_ratio'].min()
test_mae_ratio_mean = results_df['test_mae_ratio'].mean()

# 모든 행에 공통으로 최고, 최저, 평균 추가
test_mae_summary = {
    'test_mae_ratio_max': test_mae_ratio_max,
    'test_mae_ratio_min': test_mae_ratio_min,
    'test_mae_ratio_mean': test_mae_ratio_mean
}

for key, value in test_mae_summary.items():
    results_df[key] = value

# 결과를 소수점 2자리로 포맷팅하여 출력
pd.options.display.float_format = '{:.2f}'.format
results_df_sorted = results_df.sort_values(by="test_mae_ratio")

# 결과 출력
results_df.iloc[:,4:].sort_values(by="test_mae_ratio")

,train_r2,test_r2,train_mae,test_mae,train_mae_ratio,test_mae_ratio,test_mae_ratio_max,test_mae_ratio_min,test_mae_ratio_mean
식음료,0.99,0.95,8885513.90,23164099.70,3.66,9.70,30.00,9.70,18.53
의료_건강,0.99,0.92,18777082.80,49220800.85,3.71,10.22,30.00,9.70,18.53
소매_편의,0.99,0.93,19031018.06,52803462.02,4.24,11.44,30.00,9.70,18.53
미용_패션,0.99,0.95,5121125.34,12806716.61,5.79,15.02,30.00,9.70,18.53
교육_학원,0.99,0.91,2743014.28,7127660.88,7.01,18.25,30.00,9.70,18.53
생활서비스,0.99,0.86,9242864.07,26657370.21,6.17,18.29,30.00,9.70,18.53
취미_레저,0.98,0.92,11050807.38,26035739.99,8.84,23.90,30.00,9.70,18.53
가구_전자기기,0.99,0.87,11149433.72,30813966.75,10.49,29.93,30.00,9.70,18.53
부동산_숙박,0.99,0.93,1284903.30,3639133.54,11.56,30.00,30.00,9.70,18.53

<h1>랜덤포레스트 모델 - Min-Max scaler</h1>

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

# 업종명 고유값 추출
unique_categories = df["업종별카테고리"].unique()

# 결과를 저장할 딕셔너리 생성
results = {}

# 각 업종별로 데이터를 나누어 모델 학습 및 예측 수행
for category in unique_categories:
    # 업종별 데이터 필터링
    df_category = df[df['업종별카테고리'] == category]
    
    # 원핫인코딩 수행
    df_category = pd.get_dummies(df_category, columns=['행정동'], drop_first=True)
    
    # 피처와 타겟 설정
    features = ['년분기', '인구수', '지역생활인구', '장기외국인', '단기외국인', '주차장면적(면)', '주차장개수(개소)', '학교수', '학생수', '버스정류장수'] + [col for col in df_category.columns if col.startswith('행정동_')]
    target = '월매출(점포)'
    
    # 피처와 타겟 데이터 분리
    X = df_category[features]
    y = df_category[target]
    
    # Min-Max Scaler 적용
    scaler = MinMaxScaler()
    X_scaled = scaler.fit_transform(X)
    
    # 학습 데이터와 테스트 데이터 분리
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
    
    # 랜덤 포레스트 회귀 모델 학습
    model = RandomForestRegressor(random_state=42)
    model.fit(X_train, y_train)
    
    # 성능 평가 호출
    evaluation_result = my_def.evaluate_model(model, X_train, X_test, y_train, y_test)
    
    # 결과 저장
    if evaluation_result is not None:
        results[category] = evaluation_result

# 결과를 데이터프레임으로 변환
results_df = pd.DataFrame.from_dict(results, orient='index')
results_df = results_df.apply(pd.to_numeric)

# test_mae_ratio의 최고, 최저, 평균 추가
test_mae_ratio_max = results_df['test_mae_ratio'].max()
test_mae_ratio_min = results_df['test_mae_ratio'].min()
test_mae_ratio_mean = results_df['test_mae_ratio'].mean()

# 모든 행에 공통으로 최고, 최저, 평균 추가
test_mae_summary = {
    'test_mae_ratio_max': test_mae_ratio_max,
    'test_mae_ratio_min': test_mae_ratio_min,
    'test_mae_ratio_mean': test_mae_ratio_mean
}

for key, value in test_mae_summary.items():
    results_df[key] = value

# 결과를 소수점 2자리로 포맷팅하여 출력
pd.options.display.float_format = '{:.2f}'.format
results_df_sorted = results_df.sort_values(by="test_mae_ratio")

# 결과 출력
results_df.iloc[:,4:].sort_values(by="test_mae_ratio")

<h1>그래디언트 부스팅<h2>