In [9]:
import numpy as np 
import pandas as pd

In [10]:
sw19 = pd.read_csv('files/subway_2019.csv', encoding='euc-kr')
sw20 = pd.read_csv('files/subway_2020.csv', encoding='euc-kr')
sw21 = pd.read_csv('files/subway_2021.csv', encoding='euc-kr')
dong_st = pd.read_csv('files/dong_station.csv', encoding='euc-kr')

In [17]:
sw19
sw20
sw21
# dong_st

         사용월  호선명          지하철역  유임승차인원  무임승차인원  유임하차인원  무임하차인원      작업일자
0     202112  1호선  청량리(서울시립대입구)  310669  220908  311345  221568  20220103
1     202112  1호선          종로5가  359249  220044  362984  210306  20220103
2     202112  1호선          종로3가  407934  249355  375067  234742  20220103
3     202112  1호선            종각  755897  116282  740655  108719  20220103
4     202112  1호선           제기동  217819  226280  208609  241771  20220103
...      ...  ...           ...     ...     ...     ...     ...       ...
7282  202101  중앙선            양정   11604    4423    9672    3948  20210203
7283  202101  중앙선            덕소   91503   30070   91806   30576  20210203
7284  202101  중앙선            용문   18880   18177   19008   18107  20210203
7285  202101  중앙선            양평   38720   16674   37894   16687  20210203
7286  202101  중앙선            양수   24279   11584   24136   11769  20210203

[7287 rows x 8 columns]

In [12]:
dong_st.columns = ['지하철역', '호선명', '구', '동', '구_동']
dong_st

           지하철역  호선명    구     동       구_동
0           NaN  NaN  강남구  개포1동  강남구_개포1동
1         대모산입구  분당선  강남구  개포2동  강남구_개포2동
2            구룡  분당선  강남구  개포2동  강남구_개포2동
3           개포동  분당선  강남구  개포2동  강남구_개포2동
4            대청  3호선  강남구  개포3동  강남구_개포3동
..          ...  ...  ...   ...       ...
593  봉화산(서울의료원)  6호선  중랑구  신내1동  중랑구_신내1동
594         NaN  NaN  중랑구  신내2동  중랑구_신내2동
595         NaN  NaN  중랑구  중화1동  중랑구_중화1동
596          중화  7호선  중랑구  중화2동  중랑구_중화2동
597          중랑  중앙선  중랑구  중화2동  중랑구_중화2동

[598 rows x 5 columns]

In [108]:
# '지하철역'으로 데이터 병합
station_merge19 = pd.merge(sw19, dong_st, how='outer', on='지하철역')
station_merge20 = pd.merge(sw20, dong_st, how='outer', on='지하철역')
station_merge21 = pd.merge(sw21, dong_st, how='outer', on='지하철역')
station_merge19.dtypes

# 병합하면서 변환된 float 열을 int로 변환
# 병합된 데이터프레임 리스트
station_merges = [station_merge19, station_merge20, station_merge21]

for df in station_merges:
    for col in df.select_dtypes(include='float').columns:
        df[col] = df[col].fillna(0).astype(int)

station_merge19
station_merge20
station_merge21

# NaN 값 0으로 채우기 
station_merge19.fillna(0, inplace=True)
station_merge20.fillna(0, inplace=True)
station_merge21.fillna(0, inplace=True)

station_merge19
station_merge20
station_merge21

# 데이터프레임 리스트
station_data_list = [station_merge19, station_merge20, station_merge21]

# '지하철역'이 0이 아닌 데이터만 필터링
station_data_list = [df[df['지하철역'] != 0] for df in station_data_list]

# 결과 확인 (필요한 경우)
station_data19, station_data20, station_data21 = station_data_list
station_data_list

# 지하철역이 없는 데이터 제외 
# station_data19 = station_merge19[station_merge19['지하철역'] != 0]
# station_data20 = station_merge20[station_merge20['지하철역'] != 0]
# station_data21 = station_merge21[station_merge21['지하철역'] != 0]

station_data19
station_data20
station_data21

# # '지하철역'으로 병합한 csv파일 (확인차)
station_merge_all = pd.concat([station_data19 , station_data20 , station_data21])
station_merge_all.to_csv('station_merged_ex.csv', index=False, encoding='utf-8')
station_merge_all

# 동이 없는 데이터 제외 
station_merge_all = station_data19[station_data19['동'].notna()]
station_merge_all

# 필요없는 컬럼 삭제 
station_merge_all.drop('작업일자', axis=1, inplace=True)
station_merge_all

,사용월,호선명_x,지하철역,유임승차인원,무임승차인원,유임하차인원,무임하차인원,호선명_y,구,동,구_동
0,201912,우이신설선,4.19민주묘지,61832,32442,59882,30206,우이신설선,강북구,우이동,강북구_우이동
1,201911,우이신설선,4.19민주묘지,74480,32496,74086,30133,우이신설선,강북구,우이동,강북구_우이동
2,201910,우이신설선,4.19민주묘지,77817,35133,76453,32335,우이신설선,강북구,우이동,강북구_우이동
3,201909,우이신설선,4.19민주묘지,71959,31068,70973,28508,우이신설선,강북구,우이동,강북구_우이동
4,201908,우이신설선,4.19민주묘지,50245,32013,47766,29384,우이신설선,강북구,우이동,강북구_우이동
...,...,...,...,...,...,...,...,...,...,...,...
10198,201905,9호선,흑석(중앙대입구),295597,60729,296602,62111,9호선,동작구,흑석동,동작구_흑석동
10199,201904,9호선,흑석(중앙대입구),285478,60326,287718,62064,9호선,동작구,흑석동,동작구_흑석동
10200,201903,9호선,흑석(중앙대입구),289104,59790,289968,61624,9호선,동작구,흑석동,동작구_흑석동
10201,201902,9호선,흑석(중앙대입구),183627,49205,191859,50712,9호선,동작구,흑석동,동작구_흑석동
10202,201901,9호선,흑석(중앙대입구),214559,56278,224713,58197,9호선,동작구,흑석동,동작구_흑석동

In [ ]:
# 총승하차인원 컬럼 생성 

# 데이터프레임 리스트
station_all = [station_merge19, station_merge20, station_merge21]

# 각 데이터프레임에 대해 합산 컬럼 추가
for df in station_all:
    df['총승하차인원'] = df[['유임승차인원', '무임승차인원', '유임하차인원', '무임하차인원']].sum(axis=1)

station_merge19
station_merge20
station_merge21

,사용월,호선명_x,지하철역,유임승차인원,무임승차인원,유임하차인원,무임하차인원,작업일자,호선명_y,구,동,구_동,총승하차인원,월,분기
0,202112,우이신설선,4.19민주묘지,47280,29715,45573,27003,20220103,우이신설선,강북구,우이동,강북구_우이동,149571,12,67371
1,202111,우이신설선,4.19민주묘지,51474,31567,48888,28506,20211203,우이신설선,강북구,우이동,강북구_우이동,160435,11,67371
2,202110,우이신설선,4.19민주묘지,47136,33743,45146,29650,20211103,우이신설선,강북구,우이동,강북구_우이동,155675,10,67370
3,202109,우이신설선,4.19민주묘지,42324,31747,40940,27938,20211003,우이신설선,강북구,우이동,강북구_우이동,142949,9,67370
4,202108,우이신설선,4.19민주묘지,39970,30537,39142,26783,20210903,우이신설선,강북구,우이동,강북구_우이동,136432,8,67370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10066,0,0,0,0,0,0,0,0,0,중랑구,면목5동,중랑구_면목5동,0,0,0
10067,0,0,0,0,0,0,0,0,0,중랑구,면목7동,중랑구_면목7동,0,0,0
10068,0,0,0,0,0,0,0,0,0,중랑구,묵1동,중랑구_묵1동,0,0,0
10069,0,0,0,0,0,0,0,0,0,중랑구,신내2동,중랑구_신내2동,0,0,0
10070,0,0,0,0,0,0,0,0,0,중랑구,중화1동,중랑구_중화1동,0,0,0

In [152]:
# # 월, 추출

# # '사용월'을 문자열로 변환한 후, 마지막 두 자리로 '월' 추출
# station_merge19['월'] = station_merge19['사용월'].astype(str).str[-2:].astype(int)
# # 결과 확인
# station_merge19[['사용월', '월']].head()
# station_merge19


# station_merge20['월'] = station_merge20['사용월'].astype(str).str[-2:].astype(int)
# # 결과 확인
# station_merge20[['사용월', '월']].head()
# station_merge20


# station_merge21['월'] = station_merge21['사용월'].astype(str).str[-2:].astype(int)
# # 결과 확인
# station_merge21[['사용월', '월']].head()
# station_merge21

# station_merge19 
# station_merge20
# station_merge21

# 데이터프레임 리스트
station_merge_all = [station_merge19, station_merge20, station_merge21]

# 각 데이터프레임에서 '월' 추출 및 '분기' 계산
for df in station_merge_all:
    # '월' 추출
    df['월'] = df['사용월'].astype(str).str[-2:].astype(int)
    
    # '분기' 계산
    df['분기'] = df['월'].apply(lambda x: f"{(x-1)//3 + 1}분기")

# 결과 확인 (각 데이터프레임의 일부만 출력)
for df in station_merge_all:
    print(df[['사용월', '월', '분기']].head())

      사용월   월   분기
0  201912  12  4분기
1  201911  11  4분기
2  201910  10  4분기
3  201909   9  3분기
4  201908   8  3분기
      사용월   월   분기
0  202012  12  4분기
1  202011  11  4분기
2  202010  10  4분기
3  202009   9  3분기
4  202008   8  3분기
      사용월   월   분기
0  202112  12  4분기
1  202111  11  4분기
2  202110  10  4분기
3  202109   9  3분기
4  202108   8  3분기

In [150]:
station_merge21

,사용월,호선명_x,지하철역,유임승차인원,무임승차인원,유임하차인원,무임하차인원,작업일자,호선명_y,구,동,구_동,총승하차인원,월,분기
0,202112,우이신설선,4.19민주묘지,47280,29715,45573,27003,20220103,우이신설선,강북구,우이동,강북구_우이동,149571,12,4분기
1,202111,우이신설선,4.19민주묘지,51474,31567,48888,28506,20211203,우이신설선,강북구,우이동,강북구_우이동,160435,11,4분기
2,202110,우이신설선,4.19민주묘지,47136,33743,45146,29650,20211103,우이신설선,강북구,우이동,강북구_우이동,155675,10,4분기
3,202109,우이신설선,4.19민주묘지,42324,31747,40940,27938,20211003,우이신설선,강북구,우이동,강북구_우이동,142949,9,3분기
4,202108,우이신설선,4.19민주묘지,39970,30537,39142,26783,20210903,우이신설선,강북구,우이동,강북구_우이동,136432,8,3분기
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10066,0,0,0,0,0,0,0,0,0,중랑구,면목5동,중랑구_면목5동,0,0,0분기
10067,0,0,0,0,0,0,0,0,0,중랑구,면목7동,중랑구_면목7동,0,0,0분기
10068,0,0,0,0,0,0,0,0,0,중랑구,묵1동,중랑구_묵1동,0,0,0분기
10069,0,0,0,0,0,0,0,0,0,중랑구,신내2동,중랑구_신내2동,0,0,0분기
10070,0,0,0,0,0,0,0,0,0,중랑구,중화1동,중랑구_중화1동,0,0,0분기

In [151]:
station_merge19.to_csv('all_human19.csv', index=False)
station_merge20.to_csv('all_human20.csv', index=False)
station_merge21.to_csv('all_human21.csv', index=False)
print("csv파일 저장 완료")

st_human19 = pd.read_csv('all_human19.csv')
st_human20 = pd.read_csv('all_human20.csv')
st_human21 = pd.read_csv('all_human21.csv')

st_human19
st_human20
st_human21

csv파일 저장 완료

,사용월,호선명_x,지하철역,유임승차인원,무임승차인원,유임하차인원,무임하차인원,작업일자,호선명_y,구,동,구_동,총승하차인원,월,분기
0,202112,우이신설선,4.19민주묘지,47280,29715,45573,27003,20220103,우이신설선,강북구,우이동,강북구_우이동,149571,12,4분기
1,202111,우이신설선,4.19민주묘지,51474,31567,48888,28506,20211203,우이신설선,강북구,우이동,강북구_우이동,160435,11,4분기
2,202110,우이신설선,4.19민주묘지,47136,33743,45146,29650,20211103,우이신설선,강북구,우이동,강북구_우이동,155675,10,4분기
3,202109,우이신설선,4.19민주묘지,42324,31747,40940,27938,20211003,우이신설선,강북구,우이동,강북구_우이동,142949,9,3분기
4,202108,우이신설선,4.19민주묘지,39970,30537,39142,26783,20210903,우이신설선,강북구,우이동,강북구_우이동,136432,8,3분기
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10066,0,0,0,0,0,0,0,0,0,중랑구,면목5동,중랑구_면목5동,0,0,0분기
10067,0,0,0,0,0,0,0,0,0,중랑구,면목7동,중랑구_면목7동,0,0,0분기
10068,0,0,0,0,0,0,0,0,0,중랑구,묵1동,중랑구_묵1동,0,0,0분기
10069,0,0,0,0,0,0,0,0,0,중랑구,신내2동,중랑구_신내2동,0,0,0분기
10070,0,0,0,0,0,0,0,0,0,중랑구,중화1동,중랑구_중화1동,0,0,0분기

In [153]:
# 년도별 역갯수
station_merge19['지하철역'].nunique()
station_merge20['지하철역'].nunique()
station_merge21['지하철역'].nunique()

539